Repository ddev/ddev, pull requests merged in 2023-11, with the labels that each got.

#4805 fix: implement limit on number of hosts per line in /etc/hosts because Safari has problems with long lines, fixes #2817
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/tests.yml
  go.mod
  go.sum
  pkg/ddevapp/hostname_mgt.go
  vendor/github.com/goodhosts/hostsfile/.gitignore
  vendor/github.com/goodhosts/hostsfile/Makefile
  vendor/github.com/goodhosts/hostsfile/README.md
  vendor/github.com/goodhosts/hostsfile/build.go
  vendor/github.com/goodhosts/hostsfile/hosts.go
  vendor/github.com/goodhosts/hostsfile/hostsline.go
  vendor/github.com/goodhosts/hostsfile/lookup.go
  vendor/github.com/goodhosts/hostsfile/mage/install/install.go
  vendor/github.com/goodhosts/hostsfile/mage/test/test.go
  vendor/github.com/goodhosts/hostsfile/magefile.go
  vendor/github.com/goodhosts/hostsfile/make.bat
  vendor/github.com/goodhosts/hostsfile/os.go
  vendor/github.com/goodhosts/hostsfile/os_windows.go
  vendor/github.com/goodhosts/hostsfile/slice.go
  vendor/github.com/magefile/mage/LICENSE
  vendor/github.com/magefile/mage/mg/color.go
  vendor/github.com/magefile/mage/mg/color_string.go
  vendor/github.com/magefile/mage/mg/deps.go
  vendor/github.com/magefile/mage/mg/errors.go
  vendor/github.com/magefile/mage/mg/fn.go
  vendor/github.com/magefile/mage/mg/runtime.go
  vendor/github.com/magefile/mage/sh/cmd.go
  vendor/github.com/magefile/mage/sh/helpers.go
  vendor/modules.txt
Labels: dependencies, bugfix

#5241 fix: default file/uploads location for Silverstripe
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/silverstripe.go
Labels: bugfix

#5500 docs: implement search priority setting using mkdocs-material
  docs/content/developers/brand-guide.md
  docs/content/developers/building-contributing.md
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/developers/github-selfhosted-setup.md
  docs/content/developers/index.md
  docs/content/developers/project-types.md
  docs/content/developers/release-management.md
  docs/content/developers/remote-config.md
  docs/content/developers/testing-docs.md
  docs/content/developers/writing-style-guide.md
  docs/content/users/configuration/config.md
  docs/content/users/extend/additional-services.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/usage/database-management.md
  docs/content/users/usage/developer-tools.md
  mkdocs.yml
  version-history.md
Labels: documentation

#5496 fix: partial revert of #5383 add -t flag back to mailpit sendmail command
  containers/ddev-php-base/ddev-php-files/etc/php/5.6/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/5.6/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/5.6/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.0/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.0/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.0/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.3/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.3/fpm/php.ini
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/fpm/php.ini
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5501 docs: adds a dark theme compatible svgs, fixes #5492
  README.md
Labels: documentation

#5511 docs: adds a dark theme compatible svgs, fixes #5492 #5501
  README.md
Labels: documentation

#5516 feat: add `TestComposerCreateCmd` to `push-pull-test-platforms`, tests #5499
  .github/workflows/tests.yml
Labels: enhancement

#5515 fix: allow editing for platform.yaml
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
Labels: bugfix

#5514 docs: allow uppercase letters on pr titles.
  .github/workflows/pr-check.yml
Labels: documentation

#5512 build: add monthly contributor report
  .github/workflows/contributors.yml
Labels: maintenance

#5524 build: use latest version of mailpit at image build time
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5519 fix: build new ddev-webserver to get fixed lagoon-sync, rework Acquia for #4760
  containers/ddev-webserver/Dockerfile
  docs/content/users/providers/acquia.md
  docs/content/users/providers/index.md
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example
  pkg/ddevapp/provider.go
  pkg/ddevapp/providerAcquia_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5508 fix: ensure no duplicates for docker networks, fixes #5193
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5528 docs: use make test instead of make testpkg
  docs/content/developers/building-contributing.md
Labels: documentation

#5530 docs: remove the docs about obsolete drush-on-host feature
  docs/content/users/usage/developer-tools.md
Labels: documentation

#5533 fix: internal project network with duplicate check, revert for #5305
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils.go
  pkg/testcommon/testcommon.go
Labels: bugfix

#5538 docs: add instructions how to add colima to the macos login items
  docs/content/users/install/docker-installation.md
Labels: documentation

#5540 ci: revert colima to 0.5.6, use macos-13
  .github/workflows/colima-tests.yml
Labels: maintenance

#5541 test: check for duplicate networks, for #5508
  cmd/ddev/cmd/networks_test.go
Labels: maintenance

#5545 fix: add label for ddev-router, fixes #5542
  pkg/ddevapp/router_compose_template.yaml
Labels: bugfix

#5546 docs: Update list of project types in comments for config.yaml, fixes #5544
  pkg/ddevapp/templates.go
Labels: documentation

#5529 feat: implement `ddev pull upsun` provider integration, fixes #5446
  .github/workflows/tests.yml
  .spellcheckwordlist.txt
  containers/ddev-webserver/Dockerfile
  docs/content/users/providers/upsun.md
  mkdocs.yml
  pkg/ddevapp/config.go
  pkg/ddevapp/dotddev_assets/providers/upsun.yaml
  pkg/ddevapp/providerUpsun_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#5521 feat: replace deb.nodesource.com with n, fixes #5509
  docs/content/users/configuration/config.md
  docs/content/users/extend/customization-extendibility.md
  pkg/ddevapp/config.go
  pkg/ddevapp/nodejs_test.go
  pkg/ddevapp/templates.go
  pkg/nodeps/values.go
Labels: enhancement

#5549 ci: try Colima latest to fix serious docker failures
  .github/workflows/colima-tests.yml
Labels: maintenance

#5552 fix: revert "build: bump actions/github-script from 6 to 7"
  .github/workflows/pr-artifacts-comment.yml
Labels: bugfix

#5553 docs: Remove WSL2 step of installing from store
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5452 fix: add project config validation when using args, fixes #5445
  cmd/ddev/cmd/start.go
  cmd/ddev/cmd/utils.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#5554 build: bump actions/github-script from 6 to 7
  .github/workflows/pr-artifacts-comment.yml
Labels: maintenance

#5558 ci: fix buildkite runner problems with orbstack and rancher
  .buildkite/linux-arm64.yml
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-m1.yml
  .buildkite/macos_container.yml
  .buildkite/test.sh
  .githooks/README.md
Labels: maintenance

#5556 docs: remove 'just' from several places to avoid triggering textlint
  .githooks/README.md
  .github/RELEASE_NOTES_TEMPLATE.md
  CONTRIBUTING.md
  containers/ddev-ssh-agent/README.md
  docs/content/developers/maintainers.md
  docs/content/users/install/performance.md
  docs/content/users/install/shell-completion.md
  docs/content/users/quickstart.md
  pkg/ddevapp/testdata/TestApptypeDetection/magento/README.md
Labels: documentation

#5451 docs: add instructions for testing a PR by installing a downloaded binary in the $PATH
  docs/content/developers/building-contributing.md
Labels: documentation

#5478 docs: improve discussion of tarball to be imported by ddev import-files, fixes #5474
  .spellcheckwordlist.txt
  cmd/ddev/cmd/import-files.go
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
Labels: documentation

#5560 fix: Add linux-docker platform for non-wsl2 docker-ce
  pkg/version/version.go
Labels: bugfix

#5555 fix: add config validation for --all flag, for #5452
  cmd/ddev/cmd/utils.go
Labels: bugfix

#5499 feat: avoid having to remove files in `ddev composer create` #5493
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/composer_test.go
  docs/content/developers/project-types.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/developer-tools.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/utils.go
  pkg/nodeps/utils.go
  pkg/nodeps/utils_test.go
Labels: enhancement

#5562 docs: pacify linter on Zip vs ZIP
  docs/content/developers/building-contributing.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
Labels: documentation

#5561 docs: improve steps for macos buildkite agent
  .buildkite/testbot_maintenance.sh
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#5563 build: bump docker-compose to v2.23.3
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5564 build: install only binary from Upsun, for #5529
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5565 docs: fix indentation for Docker provider list
  docs/content/users/install/docker-installation.md
Labels: documentation

#5489 fix: update shopware to 6.5, quickstart and defaults to 6.5+composer
  docs/content/users/quickstart.md
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/shopware6.go
  pkg/ddevapp/testdata/TestApptypeDetection/shopware6/composer.json
  pkg/ddevapp/testdata/TestApptypeDetection/shopware6/config/README.md
Labels: bugfix

#5570 refactor: order host, port, driver the same both places in Drupal 10 settings file
  pkg/ddevapp/drupal/drupal10/settings.ddev.php
  pkg/ddevapp/drupal/drupal8/settings.ddev.php
  pkg/ddevapp/drupal/drupal9/settings.ddev.php
Labels: maintenance

#5569 docs: mention problems with shopware6 ddev composer create
  docs/content/users/quickstart.md
Labels: documentation

#5571 ci: don't fail tests based on file removal failure
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/composer_test.go
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/debug-download-images_test.go
  cmd/ddev/cmd/debug-testcleanup_test.go
  cmd/ddev/cmd/get_test.go
  cmd/ddev/cmd/homeadditions_test.go
  cmd/ddev/cmd/logs_test.go
  cmd/ddev/cmd/root_test.go
  cmd/ddev/cmd/snapshot_restore_test.go
  cmd/ddev/cmd/snapshot_test.go
  cmd/ddev/cmd/ssh_test.go
  cmd/ddev/cmd/stop_test.go
  pkg/archive/archive_test.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/composer_test.go
  pkg/ddevapp/config_merge_test.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/extra_expose_test.go
  pkg/ddevapp/hooks_test.go
  pkg/ddevapp/list_test.go
  pkg/ddevapp/mailpit_test.go
  pkg/ddevapp/mutagen_test.go
  pkg/ddevapp/network_test.go
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/providerPantheon_test.go
  pkg/ddevapp/providerPlatform_test.go
  pkg/ddevapp/providerUpsun_test.go
  pkg/ddevapp/router_test.go
  pkg/ddevapp/snapshot_test.go
  pkg/ddevapp/utils_test.go
  pkg/dockerutil/docker_compose_version_test.go
  pkg/fileutil/file_hash_test.go
Labels: maintenance

#5574 build: update images to get get php8.3.0 and related new packages
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5576 build: update .gitpod.yml for v1.22.5 release [skip ci]
  .gitpod.yml
Labels: maintenance

#5577 ci: don't set default context to default - fix rancher desktop failures
  .buildkite/macos-rancher-desktop.yml
  .buildkite/test.sh
Labels: maintenance

#5582 docs: add note about needing to restart for global commands to be picked up
  docs/content/users/extend/custom-commands.md
Labels: documentation

#5588 docs: remove search suggestions and share
  mkdocs.yml
Labels: documentation
