Repository ddev/ddev, pull requests merged in 2023-10, with the labels that each got.

#5371 feat: implement Amazee Lagoon provider integration, fixes #3188
  .github/workflows/tests.yml
  .spellcheckwordlist.txt
  cmd/ddev/cmd/pull.go
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.lagoon.yml
  docs/content/users/providers/lagoon.md
  mkdocs.yml
  pkg/ddevapp/config.go
  pkg/ddevapp/dotddev_assets/providers/lagoon.yaml
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/testdata/TestLagoonPull/.lagoon.yml
  pkg/ddevapp/testdata/TestLagoonPull/ddevauthssh.expect
  pkg/ddevapp/testdata/TestLagoonPush/.lagoon.yml
  pkg/ddevapp/testdata/TestLagoonPush/ddevauthssh.expect
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#5396 ci: change technique for PR artifact comment, fixes #5386
  .github/workflows/pr-artifacts-comment.yml
Labels: maintenance

#5403 docs: improve troubleshooting instructions for changing ports
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#5405 refactor: remove support for nodejs version 14
  cmd/ddev/cmd/config_test.go
  docs/content/users/configuration/config.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
  pkg/nodeps/values.go
Labels: maintenance

#5400 fix: update node install method, fixes #5363
  .gitpod/images/Dockerfile
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5388 docs: docker desktop for mac may need extra setting
  docs/content/users/install/docker-installation.md
Labels: documentation

#5398 fix: pass domain/project name to `ddev sequelace`, fixes #5394
  pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
Labels: bugfix

#5379 feat: add ddev_version_constraint to config.yaml, fixes #4630
  cmd/ddev/cmd/config.go
  docs/content/users/configuration/config.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/errors.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
Labels: enhancement

#5410 fix: cleanup ddev-webserver bashrc variables, fixes #5409
  containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5402 fix: command `ddev get --remove` should be run in `.ddev` config folder, for #5342
  cmd/ddev/cmd/get.go
Labels: bugfix

#5413 docs: fix missing manual instructions in WSL2 install, fixes #5364
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5414 ci: use only SHA to find PR number, for #5386 [skip ci]
  .github/workflows/pr-artifacts-comment.yml
Labels: maintenance

#5412 fix: warn about obsolete nodejs_version instead of failing
  docs/content/users/configuration/config.md
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/templates.go
Labels: bugfix

#5416 docs: improve port conflict troubleshooting
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#4950 feat: add ddev dbeaver command, fixes #4947
  .spellcheckwordlist.txt
  cmd/ddev/cmd/commands_test.go
  docs/content/users/usage/commands.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
Labels: enhancement

#5435 fix: revert "fix: make sure Platform.sh environment is not paused before pull/push"
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
Labels: bugfix

#5432 docs: make sure sudo is done early in linux installation, fixes #5327
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5428 build: remove nssm as choco dependency, fixes #5336
  winpkg/chocolatey/ddev.nuspec
Labels: maintenance

#5429 fix: remove auto-restart-containers as no longer valid, fixes #5282
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config-global_test.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_compose_template.yaml
  pkg/ddevapp/ssh_auth.go
  pkg/ddevapp/ssh_auth_compose_template.yaml
  pkg/globalconfig/global_config.go
  pkg/globalconfig/schema.json
Labels: bugfix

#5431 fix: correct global router_mailpit_http_port, fixes #5404
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/globalconfig/global_config.go
  pkg/nodeps/values.go
Labels: bugfix

#5427 fix: remove many of the perf trackers from amplitude, fixes #5338
  pkg/amplitude/amplitude.go
  pkg/config/remoteconfig/messages.go
  pkg/config/remoteconfig/remote_config.go
  pkg/ddevapp/amplitude_project.go
  pkg/ddevapp/instrumentation.go
Labels: bugfix

#5430 feat: support postgres:16, fixes #5335
  docs/content/users/extend/database-types.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/postgres/16/postgresql.conf
  pkg/ddevapp/templates.go
  pkg/nodeps/postgres_values.go
Labels: enhancement

#5426 fix: ddev describe shouldn't show router when disabled, fixes #5291
  cmd/ddev/cmd/describe.go
Labels: bugfix

#5424 fix: always include pre-releases on version constraint checking, fixes feedback on #4630
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#5422 feat: assign label to external docker network, for #5305
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils.go
Labels: enhancement

#5442 ci: apply new rules from golangci-lint v1.55.0
  pkg/ddevapp/config_test.go
  pkg/ddevapp/extra_expose_test.go
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerGit_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/providerLocalfile_test.go
  pkg/ddevapp/providerPantheon_test.go
  pkg/ddevapp/providerPlatform_test.go
  pkg/ddevapp/settings_test.go
  pkg/dockerutil/dockerutils_test.go
  pkg/util/utils.go
Labels: maintenance

#5417 docs: add mkcert tip for Firefox Dev and Flatpak in Linux, fixes #5415
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5436 feat: add output for removed network, for #5305
  pkg/dockerutil/dockerutils.go
Labels: enhancement

#5439 feat: update Bash and PowerShell autocomplete, fixes #2961, fixes #3085
  cmd/ddev_gen_autocomplete/ddev_gen_autocomplete.go
Labels: enhancement

#5438 feat: use the stable release version as part of the HEAD version on homebrew, fixes #5433
  .ci-scripts/bump_homebrew.sh
  .goreleaser.yml
Labels: enhancement

#5443 feat: process pre-start hooks earlier so exec-host hooks can do more
  pkg/ddevapp/ddevapp.go
Labels: enhancement

#5441 fix: don't pull omitted images, fixes #5292
  docs/content/users/configuration/config.md
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5434 fix: add comment required by wordpress for `wp config set` to work, fixes #3940
  pkg/ddevapp/wordpress/wp-config.php
Labels: bugfix

#5440 fix: replace outdated nfs_mount_enabled comments with use_dns_when_possible
  cmd/ddev/cmd/describe.go
  docs/content/users/configuration/config.md
  docs/content/users/extend/customization-extendibility.md
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/instrumentation_test.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestConfigMerge/fulloverridetest/components/.ddev/config.override.yaml
  pkg/ddevapp/testdata/TestConfigMerge/fulloverridetest/components/.ddev/config.yaml
  pkg/ddevapp/testdata/TestConfigMerge/fulloverridetest/expected/.ddev/config.yaml
  pkg/ddevapp/testdata/TestConfigMerge/overridetest/components/.ddev/config.last.yaml
  pkg/ddevapp/testdata/TestConfigMerge/overridetest/components/.ddev/config.yaml
  pkg/ddevapp/testdata/TestConfigMerge/overridetest/expected/.ddev/config.yaml
Labels: bugfix

#5449 ci: improve TestExtraPackages to not use deb.sury.org
  pkg/ddevapp/config_test.go
Labels: maintenance

#5425 fix: make yamlToDict give useful information instead of error in invalid config, fixes #5385
  pkg/util/yamltools.go
Labels: bugfix

#5420 fix: resolve inappropriate creation of .ddev/addon-metadata, fixes #5419
  cmd/ddev/cmd/root.go
Labels: bugfix

#5450 ci: bump ddev-php-base and ddev-webserver for php8.3.0rc3
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5460 build: bump images to v1.22.4 for release
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5444 fix: the web container startup time should be more generous, fixes #5343
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/ddevapp/snapshot.go
Labels: bugfix

#5464 build: update .gitpod.yml for v1.22.4 release [skip ci]
  .gitpod.yml
Labels: maintenance

#5305 fix: make project network external, fixes #5193
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5467 docs: add info about disk space checking on wsl2
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#5456 feat: install shell competions on HEAD
  .ci-scripts/bump_homebrew.sh
  .goreleaser.yml
Labels: enhancement

#5471 fix: we shouldn't show the amplitude warning on every ddev command
  cmd/ddev/cmd/root.go
  cmd/ddev/cmd/start.go
  cmd/ddev/main.go
Labels: bugfix

#5461 fix: remove unnecessary use of fmt.Sprintf
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/get.go
  pkg/ddevapp/ddevapp_test.go
Labels: bugfix

#5472 build: bump docker-compose to v2.23.0
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5481 build: always use the latest go and golangci-lint for gitpod [skip ci]
  .gitpod.yml
  .gitpod/images/Dockerfile
Labels: maintenance

#5473 ci: gather debugging information about possible TestExtraPackages failure
  pkg/ddevapp/config.go
Labels: maintenance

#5480 ci: stop testing no-bind-mounts and use drupal10 by default
  .github/workflows/tests.yml
Labels: maintenance

#5484 docs: specify ddev tap in upgrading instructions for macOS with brew
  docs/content/users/install/ddev-upgrade.md
Labels: documentation

#5458 fix: add correct mimetype for xsl and xslt, fixes #5457
  containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix
