Repository ddev/ddev, pull requests merged in 2023-09, with the labels that each got.

#5314 build: use gsudo.exe directly from gerardog/gsudo, for #4701
  .ci-scripts/nsis_setup.sh
  .github/workflows/pr-build.yml
  winpkg/ddev.nsi
Labels: maintenance

#5323 docs: textlint is complaining about Zip usage - use ZIP
  .ci-scripts/nsis_setup.sh
  .github/workflows/docscheck.yml
  docs/content/users/usage/managing-projects.md
Labels: documentation

#5315 docs: note that the CLI flag `--project-name` is what sets `name` in config.yaml
  docs/content/users/configuration/config.md
Labels: documentation

#5303 docs: add info about mutagen sync slow due to node_modules
  docs/content/users/install/performance.md
  mkdocs.yml
Labels: documentation

#5328 fix: drupal9 and drupal10 shouldn't be used with host-side drush so remove facility
  pkg/ddevapp/drupal/drupal10/settings.ddev.php
  pkg/ddevapp/drupal/drupal9/settings.ddev.php
Labels: bugfix

#5330 docs: add --project-tld to global config
  docs/content/users/usage/commands.md
Labels: documentation

#5329 ci: make github action build dbserver images, fixes #3748
  .github/workflows/push-tagged-dbimage.yml
  containers/ddev-dbserver/Dockerfile
  containers/ddev-dbserver/files/create_base_db.sh
  docs/content/developers/release-management.md
  pkg/ddevapp/drupal.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5334 docs: document bind_all_interfaces project config, fixes #5280
  docs/content/users/configuration/config.md
Labels: documentation

#5333 build: bump images to v1.22.2, fixes #5310
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5353 fix: make host_webserver_port and host_https_port config work again, fixes #5341
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5355 docs: typos in config.md in names of elements simple-formatting etc
  docs/content/users/configuration/config.md
Labels: documentation

#5352 fix: re-add DDEV_MAILHOG_PORT and related env vars, fixes #5351
  cmd/ddev/cmd/config_test.go
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/schema.json
Labels: bugfix

#5357 build: bump images to v1.22.3 for release
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5360 docs: use a stronger password for Magento 2
  docs/content/users/quickstart.md
Labels: documentation

#5369 docs: platform.yaml shouldn't say it is an example
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
Labels: documentation

#5331 feat: replace ngrok flags in `ddev share` with `--ngrok-args`
  .spellcheckwordlist.txt
  cmd/ddev/cmd/share.go
  docs/content/users/configuration/config.md
  docs/content/users/topics/sharing.md
  docs/content/users/usage/commands.md
Labels: enhancement

#5372 test: close xdebug listening port after opening to avoid "listen tcp :9003: bind: address already in use" errors
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#5378 ci: try to make TestDdevXhprofEnabled flake less often
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#5377 ci: remove TestDdevPause because it's flaky and unuseful
  pkg/ddevapp/ddevapp_test.go
  pkg/testcommon/testcommon.go
Labels: maintenance

#5340 feat: output that the container images are being built, fixes #5339
  cmd/ddev/cmd/debug-refresh.go
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_test.go
  pkg/ddevapp/ssh_auth.go
  pkg/ddevapp/utils.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
Labels: enhancement

#5370 feat: provide more user info on ddev start
  pkg/ddevapp/ddevapp.go
Labels: enhancement

#5383 fix: remove test@example.org from BCC in mailpit sendmail_path, fixes #5381
  containers/ddev-php-base/ddev-php-files/etc/php/5.6/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/5.6/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/5.6/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.0/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.0/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.0/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.3/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.3/fpm/php.ini
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/fpm/php.ini
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5382 fix: drupal9+ shouldn't try to configure db if db container omitted
  pkg/ddevapp/drupal.go
Labels: bugfix

#5389 docs: fix suggested PR branch name format
  docs/content/developers/building-contributing.md
Labels: documentation

#5391 ci: don't check error in test because windows can't clean up
  cmd/ddev/cmd/debug-refresh_test.go
Labels: maintenance

#5390 fix: make sure Platform.sh environment is not paused before pull/push
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
Labels: bugfix
