Repository ddev/ddev, pull requests merged in 2023-08, with the labels that each got.

#5212 feat: add `ddev debug testcleanup`, fixes #5210
  cmd/ddev/cmd/debug-testcleanup.go
  cmd/ddev/cmd/debug-testcleanup_test.go
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/users/usage/commands.md
Labels: enhancement

#5223 fix: correct xdebug port detection for colima on linux, fixes #5222
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5216 fix: make traefik monitoring port configurable, not just 9999, fixes #5196
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config-global_test.go
  docs/content/users/configuration/config.md
  docs/content/users/extend/traefik-router.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/healthcheck/router/traefik/traefik_healthcheck.sh
  pkg/ddevapp/router.go
  pkg/ddevapp/router_compose_template.yaml
  pkg/ddevapp/traefik.go
  pkg/ddevapp/traefik_static_config_template.yaml
  pkg/globalconfig/global_config.go
  pkg/nodeps/values.go
Labels: bugfix

#5230 docs: traefik capitalization incorrect
  docs/content/users/usage/commands.md
Labels: documentation

#5221 build: update mkdocs version for readthedocs
  docs/mkdocs-pip-requirements
Labels: maintenance

#5231 fix: php serialize_precision should be -1 in php >= 7.1, fixes #5092
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.1/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.2/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/fpm/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/php.ini
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/cli/php.ini
  containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/fpm/php.ini
  pkg/ddevapp/config_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5119 feat: add Silverstripe project type
  .spellcheckwordlist.txt
  docs/content/users/configuration/config.md
  docs/content/users/quickstart.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/global_dotddev_assets/commands/web/sake
  pkg/ddevapp/silverstripe.go
  pkg/ddevapp/testdata/TestApptypeDetection/silverstripe/vendor/bin/sake
  pkg/nodeps/values.go
Labels: enhancement

#5245 build: update readthedocs config per their email
  .readthedocs.yaml
  docs/mkdocs-pip-requirements
Labels: maintenance

#5247 docs: remove information about obsolete omit-containers=dba config, fixes #5246
  pkg/ddevapp/config.go
Labels: documentation

#5252 docs: update moodle quickstart to use MariaDB 10.6
  docs/content/users/quickstart.md
Labels: documentation

#5249 docs: step-debugging: add firewall tip at top, update Debug Configuration to use PHP Web Page, fixes #5248
  docs/content/users/debugging-profiling/step-debugging.md
Labels: documentation

#5159 docs: add FAQ about migrating between Docker providers
  .spellcheckwordlist.txt
  docs/content/users/install/docker-installation.md
  docs/content/users/usage/faq.md
Labels: documentation

#5258 fix: make GetDockerPlatform() more accurate, fixes #5250
  pkg/version/version.go
Labels: bugfix

#5259 ci: colima no longer needs to be installed on macOS runners on github actions
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/linux-setup.sh
  .github/workflows/macos-colima-setup.sh
  .github/workflows/macos-setup.sh
  .github/workflows/master-build.yml
Labels: maintenance

#5261 docs: explain how to examine data on Amplitude
  docs/content/developers/building-contributing.md
Labels: documentation

#5264 ci: don't install libpq on macOS any more, postgresql is installed
  .github/workflows/macos-colima-setup.sh
Labels: maintenance

#5265 docs: fix yarn commands link
  docs/content/users/usage/commands.md
Labels: documentation

#5263 fix: properly support DDEV_HOST_WEBSERVER_PORT, fixes #1812
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
Labels: bugfix

#5266 fix: add dedicated ddev-traefik-router, fixes #5239, fixes #5209
  .github/workflows/container-tests.yml
  cmd/ddev/cmd/config-global.go
  containers/ddev-nginx-proxy-router/.gitignore
  containers/ddev-nginx-proxy-router/502.html
  containers/ddev-nginx-proxy-router/503.html
  containers/ddev-nginx-proxy-router/Dockerfile
  containers/ddev-nginx-proxy-router/LICENSE
  containers/ddev-nginx-proxy-router/Makefile
  containers/ddev-nginx-proxy-router/Procfile
  containers/ddev-nginx-proxy-router/README.md
  containers/ddev-nginx-proxy-router/docker-entrypoint.sh
  containers/ddev-nginx-proxy-router/etc/nginx/nginx.conf
  containers/ddev-nginx-proxy-router/gen-cert-and-nginx-config.sh.tmpl
  containers/ddev-nginx-proxy-router/healthcheck.sh
  containers/ddev-nginx-proxy-router/nginx.tmpl
  containers/ddev-nginx-proxy-router/test/containertest.sh
  containers/ddev-nginx-proxy-router/testtools/testgen.sh
  containers/ddev-traefik-router/.gitignore
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-traefik-router/LICENSE
  containers/ddev-traefik-router/Makefile
  containers/ddev-traefik-router/README.md
  containers/ddev-traefik-router/test/containertest.sh
  containers/ddev-traefik-router/test/testdata/static_config.yaml
  containers/ddev-traefik-router/traefik_healthcheck.sh
  containers/push-all.sh
  docs/content/developers/building-contributing.md
  docs/content/developers/release-management.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/config.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_compose_template.yaml
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5274 fix: remove cruft from DdevApp
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5276 build: bump docker-compose to 2.20.3
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5242 fix: additional MySQL config on Windows, fixes #3801
  containers/ddev-dbserver/files/docker-entrypoint.sh
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5283 ci: use explicit choices for image name to push [skip ci]
  .github/workflows/push-tagged-image.yml
Labels: maintenance

#5287 docs: fix custom cert issues - default router has changed
  docs/content/users/extend/custom-tls-certificates.md
Labels: documentation

#5284 docs: fix URL in error message, remove warning in NFS docs
  cmd/ddev/cmd/debug-nfsmount.go
  docs/content/users/install/performance.md
Labels: documentation

#5267 codespaces - remove docker-in-docker since it's installed via universal image
  .devcontainer/devcontainer.json
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5257 fix: change codespaces forwarding domain name to app.github.dev
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5289 ci: update devcontainer package since we have new devcontainer stuff
  .github/devcontainers/src/install-ddev/devcontainer-feature.json
  .github/workflows/macos-colima-setup.sh
Labels: maintenance

#5234 fix: import-files should work with any project type
  pkg/ddevapp/apptypes.go
Labels: bugfix

#5281 feat: initial JSON schemas for global config and project/app config, fixes #4511
  pkg/ddevapp/schema.json
  pkg/globalconfig/schema.json
Labels: enhancement

#5279 docs: add next steps to improve guiding new users, enable footer links
  docs/content/index.md
  mkdocs.yml
Labels: documentation

#5207 docs: initial draft for restructuring the CMS quickstarts guide
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
  docs/content/users/usage/index.md
  docs/content/users/usage/managing-projects.md
  mkdocs.yml
Labels: documentation

#5297 docs: fix broken links to provider directory on GitHub
  pkg/ddevapp/dotddev_assets/providers/README.txt
Labels: documentation

#5293 docs: mention alternate docker providers in faq, fixes #5014
  docs/content/users/install/docker-installation.md
  docs/content/users/usage/faq.md
Labels: documentation

#5308 ci: try another technique to get colima running again
  .github/workflows/macos-colima-setup.sh
Labels: maintenance

#5311 docs: fix broken chocolatey link
  docs/content/developers/release-management.md
Labels: documentation

#5309 ci: simplify colima/homebrew setup
  .buildkite/testbot_maintenance.sh
  .github/workflows/colima-tests.yml
  .github/workflows/macos-colima-setup.sh
Labels: maintenance

#5307 docs: mention xdebug_ide_location setting in xdebug troubleshooting section
  docs/content/users/debugging-profiling/step-debugging.md
Labels: documentation

#5302 docs: fix a tab in "CMS Quickstarts"
  docs/content/users/quickstart.md
Labels: documentation

#5290 docs: improve and simplify codespaces guide, use separate script
  .spellcheckwordlist.txt
  docs/content/images/codespaces-creation-log.png
  docs/content/images/codespaces-fresh-install.png
  docs/content/images/codespaces-hello-screen.png
  docs/content/images/codespaces-launch.png
  docs/content/images/codespaces-setting-up.png
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5301 docs: add Ibexa DXP to "CMS Quickstarts"
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#5312 ci: more work to get homebrew sorted out on colima
  .github/workflows/colima-tests.yml
Labels: maintenance

#5104 refactor: use StrictHostKeyChecking=accept-new
  cmd/ddev/cmd/auth-ssh_test.go
  containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.ssh/config
  docs/content/users/extend/in-container-configuration.md
  pkg/ddevapp/ssh_auth_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance
