Repository ddev/ddev, pull requests merged in 2023-12, with the labels that each got.

#5594 ci: make TestMailpit and TestProjectPortOverride more forgiving of Rancher Desktop, fixes #5578
  pkg/ddevapp/mailpit_test.go
  pkg/ddevapp/router_test.go
Labels: maintenance

#5593 fix: rancher desktop docker-platform should not report linux-docker
  pkg/version/version.go
Labels: bugfix

#5605 fix: update outdated link for hostname, fixes #5604 [skip ci]
  pkg/ddevapp/config.go
Labels: bugfix

#5597 fix: don't let people run ddev under rosetta, report no-bind-mounts behavior, fixes #5590
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/os_warnings.go
  pkg/ddevapp/os_warnings_darwin.go
  pkg/globalconfig/performance_mode.go
Labels: bugfix

#5608 fix: php8.3-xdebug and redis, memcached now available
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5603 fix: dont auto start host custom commands, fixes #2688
  cmd/ddev/cmd/commands.go
  pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
  pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
  pkg/ddevapp/global_dotddev_assets/commands/host/mysqlworkbench.example
  pkg/ddevapp/global_dotddev_assets/commands/host/querious
  pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
  pkg/ddevapp/global_dotddev_assets/commands/host/sequelpro
  pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Labels: bugfix

#5614 ci: fix Python conflicts in Colima tests
  .github/workflows/colima-tests.yml
Labels: maintenance

#5616 docs: fix invalid command reference, `pgdump`
  docs/content/users/usage/database-management.md
Labels: documentation

#5612 fix: return MTU 1440 for Gitpod, fixes #5611
  cmd/ddev/cmd/networks_test.go
  pkg/ddevapp/app_compose_template.yaml
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5572 fix: ensure help information respects `--json-output` flag, fixes #5567
  cmd/ddev/cmd/root.go
  cmd/ddev/cmd/root_help_json.go
Labels: bugfix

#5623 fix: do not fail on `apt-get update` for extra packages, for #5620
  pkg/ddevapp/config.go
Labels: bugfix

#5624 ci: enable all ddev-webserver tests for PHP 8.3, for #5238
  containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
Labels: maintenance

#5622 feat: add detail about restore command to snapshot command output, fixes #5621
  cmd/ddev/cmd/snapshot.go
Labels: enhancement

#5625 feat: add toggle arg to xdebug command, fixes #3593
  cmd/ddev/cmd/xdebug_test.go
  docs/content/users/configuration/config.md
  docs/content/users/debugging-profiling/step-debugging.md
  docs/content/users/debugging-profiling/xdebug-profiling.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
Labels: enhancement

#5626 build: bump images to v1.22.6 for release
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5628 build: update .gitpod.yml for v1.22.6 release [skip ci]
  .gitpod.yml
Labels: maintenance

#5629 docs: add more troubleshooting for docker build-time errors
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#5636 ci: rancher desktop test only on master [skip ci]
  .buildkite/macos-rancher-desktop.yml
Labels: maintenance

#5637 docs: update discord link [skip ci]
  .github/ISSUE_TEMPLATE/config.yml
  docs/content/developers/maintainers.md
  docs/content/users/support.md
  docs/content/users/usage/faq.md
  mkdocs.yml
  pkg/ddevapp/testdata/TestApptypeDetection/magento/README.md
Labels: documentation

#5513 docs: update and reorganize readme.md
  README.md
Labels: documentation

#5638 docs: link to experimental CMS quickstarts
  README.md
  docs/content/users/configuration/experimental.md
Labels: documentation

#5645 refactor: add quotes for the hostname error for better visibility
  pkg/ddevapp/config.go
Labels: maintenance

#5592 docs: GitHub Codespaces: Adjust examples to make sure docker is running
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5654 docs: fix typo in sharing.md
  docs/content/users/topics/sharing.md
Labels: documentation

#5657 ci: fix PostgreSQL client for testbot on WSL2
  .buildkite/testbot_maintenance.sh
Labels: maintenance

#5647 fix: disable Content-Type auto-detection for Traefik 2, fixes #5346
  pkg/ddevapp/traefik_config_template.yaml
Labels: bugfix

#5632 fix: global project_tld should default to 'ddev.site', not empty, fixes #4290
  cmd/ddev/cmd/config-global_test.go
  pkg/ddevapp/config.go
  pkg/globalconfig/global_config.go
Labels: bugfix

#5653 fix: update global schema
  pkg/globalconfig/schema.json
Labels: bugfix

#5631 fix: stop warning about empty app type or docroot creation, fixes #5498
  .github/workflows/colima-tests.yml
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/testdata/TestCmdGet/example-repo/tests/test.bats
  docs/content/users/quickstart.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#5642 feat: add mailpit command (alias of launch -m), fixes #5627
  cmd/ddev/cmd/describe.go
  docs/content/users/usage/commands.md
  docs/content/users/usage/developer-tools.md
  pkg/ddevapp/global_dotddev_assets/commands/host/mailpit
Labels: enhancement

#5662 build: revert bump actions/upload-artifact from 3 to 4, for #5648
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
Labels: maintenance
