Repository ddev/ddev, pull requests merged in 2023-07, with the labels that each got.

#5059 test: fix broken Mutagen test
  cmd/ddev/cmd/mutagen-cmd_test.go
Labels: maintenance

#5057 build: bump to new images for v1.22.0-beta1
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: maintenance

#5055 docs: improve descriptions for performance_mode
  pkg/ddevapp/templates.go
  pkg/globalconfig/global_config.go
Labels: documentation

#5062 test: fix broken Mutagen test use-nfsmount
  cmd/ddev/cmd/mutagen-cmd_test.go
Labels: maintenance

#5005 feat: allow multiple upload dirs, fixes #4190, fixes #4796, fixes #5047
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/debug-capabilities.go
  cmd/ddev/cmd/export-db.go
  cmd/ddev/cmd/import-db.go
  cmd/ddev/cmd/import-files.go
  docs/content/users/configuration/config.md
  docs/content/users/extend/custom-commands.md
  docs/content/users/install/performance.md
  docs/content/users/providers/index.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/config.go
  pkg/ddevapp/craftcms.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/dotddev_assets/providers/README.txt
  pkg/ddevapp/drupal.go
  pkg/ddevapp/magento.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/mutagen_config_assets/mutagen.yml
  pkg/ddevapp/php.go
  pkg/ddevapp/provider.go
  pkg/ddevapp/shopware6.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/typo3.go
  pkg/ddevapp/upload_dirs.go
  pkg/ddevapp/utils.go
  pkg/ddevapp/wordpress.go
  pkg/testcommon/testcommon.go
Labels: enhancement

#5061 build: gh codespaces - bump docker-in-docker to v2
  .devcontainer/devcontainer.json
  .devcontainer/setup_test_project.sh
Labels: maintenance

#5060 docs: gh codespaces install docs - update docker-in-docker to v2
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5067 build: publish new devcontainer
  .github/devcontainers/src/install-ddev/devcontainer-feature.json
Labels: maintenance

#5068 docs: update devcontainer publishing
  docs/content/developers/release-management.md
Labels: documentation

#5072 refactor: detect more dependency changes
  .github/pr-labeler.yml
  cmd/ddev/cmd/cmd_version_test.go
  cmd/ddev/cmd/debug-dockercheck.go
  cmd/ddev/cmd/debug-download-images.go
  cmd/ddev/cmd/debug-download-images_test.go
  cmd/ddev/cmd/debug-nfsmount.go
  cmd/ddev/cmd/delete-images.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/router.go
  pkg/docker/images.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/values.go
  pkg/version/version.go
  pkg/versionconstants/versionconstants.go
Labels: maintenance

#5045 docs: improve additional-hostnames.md
  docs/content/users/extend/additional-hostnames.md
Labels: documentation

#5011 fix: avoid `type: php` to detected project type but instead show a warning, fixes #4403, fixes #1919
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/network_test.go
  pkg/nodeps/values.go
Labels: bugfix

#5074 docs: fix spellcheck failure
  docs/content/users/extend/additional-hostnames.md
Labels: documentation

#5049 build: bump mutagen to 0.17.2
  .buildkite/test.sh
  .buildkite/testbot_maintenance.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5066 fix: avoid instrumentation of project if none is loaded, fixes #5065
  cmd/ddev/cmd/root.go
Labels: bugfix

#5079 ci: decrease cache update interval to have more up to date caches [skip ci]
  .github/workflows/colima-tests.yml
  .github/workflows/tests.yml
Labels: maintenance

#5080 ci: implement clean up and update of Homebrew cache [skip ci]
  .github/workflows/colima-tests.yml
  .github/workflows/tests.yml
Labels: maintenance

#5086 ci: fix link to docs in PR Check [skip ci]
  .github/workflows/pr-check.yml
Labels: maintenance

#5087 fix: revert accidental change of upload-dir type, fixes #5076
  cmd/ddev/cmd/config.go
Labels: bugfix

#5088 ci: reduce Homebrew cleanup
  .github/workflows/colima-tests.yml
  .github/workflows/tests.yml
Labels: maintenance

#5084 fix: quote host parameter for HeidiSQL and prevent argument double quoting
  pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
Labels: bugfix

#5085 fix: disable docker CLI hints, fixes #5077
  cmd/ddev/cmd/a.go
Labels: bugfix

#5091 ci: increase cache update interval to one week
  .github/workflows/colima-tests.yml
  .github/workflows/tests.yml
Labels: maintenance

#4877 refactor: avoid calling stop hooks if app is already stopped
  pkg/ddevapp/ddevapp.go
Labels: maintenance

#5096 fix: terminate mutagen sessions on DDEV upgrade, fixes #5040
  cmd/ddev/cmd/root.go
  pkg/ddevapp/mutagen.go
Labels: bugfix

#5105 docs: point to new location of DDEV GitHub Action
  docs/content/users/topics/remote-docker.md
Labels: documentation

#5097 ci: prevent job from failing if cleanup fails
  .github/workflows/colima-tests.yml
  .github/workflows/tests.yml
Labels: maintenance

#5107 fix: ddev-webserver process kill function was incorrect
  containers/ddev-webserver/ddev-webserver-base-scripts/pre-start.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5103 build: revert to upstream Amplitude, fixes #5101
  go.mod
  go.sum
  pkg/amplitude/doc.go
  vendor/github.com/amplitude/analytics-go/amplitude/constants/constants.go
  vendor/modules.txt
Labels: dependencies, maintenance

#5106 fix: solve mutagen failure, restart should check for new version, check composer.json in container, fixes #5089
  cmd/ddev/cmd/restart.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/mutagen.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5115 ci: ensure go modules have a clean state
  .github/workflows/golangci-lint.yml
Labels: maintenance

#5116 ci: minor cleanup for TestPantheonDoMonthlyPush [skip ci]
  pkg/ddevapp/providerPantheon_test.go
Labels: maintenance

#5110 refactor: anonymize user-defined custom commands
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/root.go
  pkg/ddevapp/assets.go
Labels: maintenance

#5124 ci: remove TestPantheonDoMonthlyPush [skip ci]
  pkg/ddevapp/providerPantheon_test.go
Labels: maintenance

#5122 refactor: update settings.php for the Drupal 10 project type, fixes #5121
  pkg/ddevapp/drupal/drupal10/settings.php
Labels: maintenance

#5120 docs: improve “Additional Project Hostnames” intro and add YAML syntax highlighting
  docs/content/users/extend/additional-hostnames.md
Labels: documentation

#5118 docs: rename feature section in readme.md
  README.md
Labels: documentation

#5117 fix: empty global table style should revert to "default"
  pkg/globalconfig/styles.go
Labels: bugfix

#5006 build: bump docker-compose to 2.20.0
  docs/content/users/usage/troubleshooting.md
  pkg/ddevapp/ddevapp.go
  pkg/globalconfig/global_config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5109 refactor: reintroduce removed flags and remove dba from `omit_containers`, fixes ddev#5095
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config.go
  pkg/ddevapp/config.go
  pkg/globalconfig/global_config.go
Labels: maintenance

#5128 fix: fix panic when upload_dirs=false, improve upload_dirs tests, fixes #5126, fixes #5127
  .github/workflows/tests.yml
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/php.go
  pkg/ddevapp/upload_dirs.go
Labels: bugfix

#5134 refactor: revert `upload_dirs=false`, fixes #5131
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  docs/content/users/configuration/config.md
  docs/content/users/usage/cli.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/magento.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/shopware6.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/typo3.go
  pkg/ddevapp/upload_dirs.go
  pkg/ddevapp/wordpress.go
  pkg/testcommon/testcommon.go
Labels: maintenance

#5129 docs: change code refs of Mac M1 to Apple Silicon
  cmd/ddev/cmd/auth-ssh_test.go
  cmd/ddev/cmd/logs_test.go
  cmd/ddev/cmd/ssh_test.go
  cmd/ddev/cmd/xdebug_test.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/hardened_test.go
  pkg/ddevapp/router_test.go
  pkg/nodeps/utils.go
Labels: documentation

#5098 build: clean up Windows installer, fixes #1945
  winpkg/ddev.nsi
Labels: maintenance

#5132 fix: composer create project must restart to fix broken bind mounts, fixes #5031
  cmd/ddev/cmd/composer-create.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/upload_dirs.go
Labels: bugfix

#5136 refactor: start reporting all commands to amplitude
  cmd/ddev/cmd/root.go
Labels: maintenance

#5140 build: bump mysql to 8.0.33 and 5.7.42, fixes #5114
  containers/ddev-dbserver/Makefile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5108 fix: detect Craft CMS version and warn user on type mismatch and introduce new env vars, fixes #4650
  pkg/ddevapp/craftcms.go
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5148 fix: ddev config should not stumble on invalid app type, fixes #5146
  pkg/ddevapp/config.go
Labels: bugfix

#5147 refactor: make many mutagen debug outputs only verbose, fixes #5143
  pkg/ddevapp/mutagen.go
  pkg/util/utils.go
Labels: maintenance

#5145 refactor: make GetDockerPlatform() give more useful information, fixes #5142
  pkg/version/version.go
Labels: maintenance

#5150 fix: repair broken received HTTP*EXPOSE that breaks ports statement
  pkg/ddevapp/router.go
  pkg/globalconfig/global_config.go
Labels: bugfix

#5149 ci: minor improvement to TestDdevNoProjectMount [skip ci]
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#5139 feat: add new disable-upload-dirs-warning configuration
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  docs/content/users/configuration/config.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/upload_dirs.go
Labels: enhancement

#5137 fix: always clean up ddev-global-cache, fixes #5135
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5156 docs: add messages configuration to config.md
  docs/content/users/configuration/config.md
  pkg/globalconfig/global_config.go
Labels: documentation

#5155 docs: add v1.22 to version-history [skip ci]
  version-history.md
Labels: documentation

#5157 ci: stop caching colima and homebrew on colima
  .github/workflows/colima-tests.yml
  .github/workflows/macos-colima-setup.sh
Labels: maintenance

#5154 fix: default_container_timeout should actually work, fixes #5133
  pkg/ddevapp/app_compose_template.yaml
Labels: bugfix

#5163 fix: revert "refactor: start reporting all commands to amplitude"
  cmd/ddev/cmd/root.go
Labels: bugfix

#5166 docs: fix broken link on docker
  docs/content/users/extend/custom-compose-files.md
Labels: documentation

#5165 docs: update outdated reference to Drupal 9 in phpunit section
  docs/content/users/install/phpstorm.md
Labels: documentation

#5170 fix: bad link was output when asking permission on instrumentation
  cmd/ddev/cmd/root.go
Labels: bugfix

#5169 fix: don't report json-formatted commands to Amplitude
  cmd/ddev/cmd/root.go
Labels: bugfix

#5175 fix: don't run MutagenSyncFlush on non-running project during config, fixes #5168
  pkg/ddevapp/apptypes.go
Labels: bugfix

#5176 fix: show docker platform in ddev describe
  cmd/ddev/cmd/describe.go
Labels: bugfix

#5178 fix: correctly return notification and ticker interval, fixes #5177
  pkg/config/remoteconfig/messages.go
Labels: bugfix

#5179 build: bump docker image tags for v1.22.0
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5181 refactor: start with random ticker message, fixes #5180
  pkg/config/remoteconfig/messages.go
Labels: maintenance

#5184 refactor: output debug messages during router startup
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/router.go
Labels: maintenance

#5185 fix: traefik dashboard should not bind all interfaces by default
  pkg/ddevapp/router_compose_template.yaml
Labels: bugfix

#5187 ci: update .textlintrc to fix capitalization and typo
  .textlintrc
Labels: maintenance

#5183 docs: improve docs example on building-contributing.md
  docs/content/developers/building-contributing.md
Labels: documentation

#5192 fix: ddev debug dockercheck logic error and typo
  cmd/ddev/cmd/debug-dockercheck.go
Labels: bugfix

#5202 ci: fix out of space trouble on github actions, fixes #5201
  .github/workflows/codeql.yml
  .github/workflows/tests.yml
Labels: maintenance

#5198 fix: default upload_dirs incorrect for magento2, fixes #5197
  pkg/ddevapp/magento.go
Labels: bugfix

#5205 docs: make a few cases of Bash upper case in the docs
  docs/content/users/extend/in-container-configuration.md
  docs/content/users/install/shell-completion.md
  version-history.md
Labels: documentation

#5199 fix: chmod ugo+rwx /usr/local/bin *after* dirs have been added, fixes #5191
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/hardened_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix
