Repository ddev/ddev, pull requests merged in 2024-04, with the labels that each got.

#6029 fix: clean up missing project if it's gone, fixes #5322
  cmd/ddev/cmd/describe_test.go
  cmd/ddev/cmd/start_test.go
  cmd/ddev/cmd/stop_test.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/utils.go
Labels: bugfix

#6025 fix: handle wildcard hostnames when name resolution not available, fixes #4881
  cmd/ddev/cmd/root.go
  docs/content/users/configuration/config.md
  docs/content/users/usage/troubleshooting.md
  go.mod
  pkg/ddevapp/config.go
  pkg/ddevapp/hostname_mgt.go
Labels: dependencies, bugfix

#6041 test: try to fix sshfs-based failures on TestGetProjectsMissingApp
  .buildkite/macos-colima_vz.yml
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-rancher-desktop.yml
  .buildkite/wsl2-docker-desktop.yml
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#6030 feat: more readable formatting of lists of files, fixes #5985
  pkg/ddevapp/config.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: enhancement

#6037 fix: ddev debug configyaml shouldn't double-report upload_dirs, fixes #6036
  cmd/ddev/cmd/debug-config-yaml.go
  pkg/ddevapp/config.go
Labels: bugfix

#5926 refactor: Use project_list.yaml as source of truth, fixes #5918
  docs/content/users/usage/architecture.md
  pkg/ddevapp/ddevapp.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/schema.json
Labels: maintenance

#6033 fix: shutdown supervisor in healthcheck.sh on fatal error, fixes #5993
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/apache.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/gunicorn.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/php-fpm.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-fpm.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-gunicorn.conf
  containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
  containers/ddev-webserver/ddev-webserver-dev-base-files/etc/supervisor/conf.d/mailhog.conf
  docs/content/users/extend/customization-extendibility.md
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5805 fix: Remove Craft CMS PHP version override
  docs/content/users/quickstart.md
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/craftcms.go
Labels: bugfix

#6050 fix: make sure CGO_ENABLED is normally off, fixes #6046
  .github/workflows/master-build.yml
  .github/workflows/tests.yml
  Makefile
  pkg/version/version.go
  pkg/versionconstants/cgo_false.go
  pkg/versionconstants/cgo_true.go
Labels: dependencies, bugfix

#6043 feat: Improve container errors messages format, fixes #6042
  pkg/dockerutil/dockerutils.go
Labels: enhancement

#6054 fix: Fix spelling for DEBUG_KIT_SAFE_TLD env variable
  pkg/ddevapp/cakephp.go
Labels: bugfix

#5753 feat: copy commands into volume, not into project, for #4416
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/debug-fixcommands.go
  docs/content/users/extend/custom-commands.md
  docs/content/users/extend/custom-compose-files.md
  docs/content/users/usage/architecture.md
  pkg/ddevapp/commands.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/providerLocalfile_test.go
Labels: enhancement

#6059 docs: fix the scroll margin for links with anchors, for #6048
  docs/overrides/partials/header.html
Labels: documentation

#6057 docs: several maintenance items
  docs/content/developers/release-management.md
  docs/content/users/configuration/config.md
  docs/content/users/extend/custom-commands.md
  docs/content/users/install/docker-installation.md
Labels: documentation

#6056 docs: update FAQs on Chrome, large webserver, php-patch-build
  .spellcheckwordlist.txt
  docs/content/users/usage/faq.md
Labels: documentation

#6019 docs: clarify additional compose service configuration
  docs/content/users/extend/custom-compose-files.md
Labels: documentation

#5990 docs: add instruction how to update add-ons
  docs/content/users/extend/additional-services.md
Labels: documentation

#6058 fix: Update defaults for config overrides
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/laravel.go
  pkg/ddevapp/magento.go
  pkg/ddevapp/silverstripe.go
Labels: bugfix

#6062 build: bump all images to v1.23.0
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6024 feat: accept port in `ddev launch`, for #5525
  cmd/ddev/cmd/commands_test.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
Labels: enhancement

#6020 feat: add pint command to laravel projects
  cmd/ddev/cmd/commands_test.go
  pkg/ddevapp/global_dotddev_assets/commands/web/pint
Labels: enhancement

#6063 fix: provide example .ddev/php folder and README, fixes #6052
  pkg/ddevapp/dotddev_assets/php/README.txt
  pkg/ddevapp/dotddev_assets/php/php-example.ini.example
Labels: bugfix

#6064 docs: Improve ddev_version_constraint
  docs/content/users/configuration/config.md
Labels: documentation

#6065 feat: add Docker API version to `ddev version`
  pkg/version/version.go
  pkg/version/version_test.go
Labels: enhancement

#6066 build: bump docker-compose to v2.26.1
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6074 test: Remove docker login from buildkite tests
  .buildkite/macos-colima.yml
  .buildkite/macos-colima_vz.yml
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-lima.yml
  .buildkite/macos-orbstack.yml
  .buildkite/macos-rancher-desktop.yml
  .buildkite/windows10_container.yml
  .buildkite/windows10dockerforwindows.yml
  .buildkite/wsl2-docker-desktop.yml
  .buildkite/wsl2-docker-inside.yml
  docs/content/developers/buildkite-testmachine-setup.md
Labels: maintenance

#6075 test: Fix TestPHPOverrides on Windows
  pkg/ddevapp/config_test.go
Labels: maintenance

#6076 build: fix deprecated goreleaser configs, fixes #6049 [skip ci]
  .goreleaser.yml
Labels: maintenance

#6073 docs: limactl create needs --name=default, fixes #6068
  docs/content/users/install/docker-installation.md
Labels: documentation

#6067 docs: add more examples how to use `ddev nvm`, fixes #6013
  docs/content/users/usage/commands.md
Labels: documentation

#6060 docs: Add drupal9/11 tabs and symfony to quickstart
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#6080 feat: Add symfony cli
  .spellcheckwordlist.txt
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/tests/ddev-webserver/general.bats
  docs/content/users/quickstart.md
  docs/content/users/usage/cli.md
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6084 docs: Replaced --target-db by --database
  docs/content/users/usage/faq.md
Labels: documentation

#6079 build: pin blackfire to working package, fixes #6078
  containers/ddev-webserver/ddev-webserver-base-files/etc/apt/preferences.d/blackfire
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6077 feat: add ddev debug capabilities with corepack, version-history.md, fixes #6051
  cmd/ddev/cmd/debug-capabilities.go
  version-history.md
Labels: enhancement

#6055 feat: Add ddev config --update flag, fixes #6035
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/testdata/TestConfigUpdate/craftcms/.ddev/config.yaml
  cmd/ddev/cmd/testdata/TestConfigUpdate/craftcms/craft
  cmd/ddev/cmd/testdata/TestConfigUpdate/craftcms/vendor/craftcms/cms/src/Craft.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/craftcms/web/index.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal10-composer/.ddev/config.yaml
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal10-composer/web/core/lib/Drupal.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal10-composer/web/index.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal11-composer/.ddev/config.yaml
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal11-composer/web/core/lib/Drupal.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal11-composer/web/index.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal11-git/.ddev/config.yaml
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal11-git/core/lib/Drupal.php
  cmd/ddev/cmd/testdata/TestConfigUpdate/drupal11-git/index.php
  docs/content/users/install/docker-installation.md
  docs/content/users/quickstart.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/config.go
  pkg/testcommon/testcommon.go
Labels: enhancement

#6093 fix: revert additions to php/craftcms expires in nginx-site.conf, fixes #6087
  pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-php.conf
Labels: bugfix

#6094 fix: use ip route show default to get WSL2 addr of windows
  docs/content/users/debugging-profiling/step-debugging.md
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#6089 fix: don't label transient containers and run without healthcheck, fixes #6085
  cmd/ddev/cmd/debug-dockercheck.go
  cmd/ddev/cmd/debug-nfsmount.go
  pkg/ddevapp/commands.go
  pkg/ddevapp/db.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/fileutil/file_hash_test.go
Labels: bugfix

#6095 docs: Updates to the quickstarts
  docs/content/users/quickstart.md
Labels: documentation

#6104 fix: update links for stable documentation
  .ci-scripts/bump_homebrew.sh
  .github/ISSUE_TEMPLATE/bug_report.yml
  CONTRIBUTING.md
  README.md
  docs/content/developers/maintainers.md
  docs/content/developers/release-management.md
  docs/content/users/quickstart.md
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
  pkg/ddevapp/testdata/TestConfigOverrideDetection/.ddev/nginx_full/nginx-site.conf
  pkg/ddevapp/webserver_config_assets/apache-site-php.conf
  pkg/ddevapp/webserver_config_assets/apache_second_docroot_example-site-php.conf
Labels: bugfix

#6098 fix: add Docker filter by label without value, fixes #6088
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#6107 docs: updates to the quickstarts, for #6095
  docs/content/users/quickstart.md
Labels: documentation

#6105 build: Update to latest ddev-webserver prior to v1.23.0 release, fixes #6086
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6112 build: update .gitpod.yml for v1.23.0 release [skip ci]
  .gitpod.yml
Labels: maintenance

#6115 build: update devcontainer-feature.json for v1.23.0 release [skip ci]
  .github/devcontainers/src/install-ddev/devcontainer-feature.json
Labels: maintenance

#6114 docs: remove errant comma in codespaces devcontainer.json
  docs/content/users/install/ddev-installation.md
Labels: documentation

#6119 fix: clean up test project on signal, fixes #6111
  cmd/ddev/cmd/scripts/test_ddev.sh
  pkg/exec/exec.go
Labels: bugfix

#6124 refactor: move php folder permission fix to the end, for #6122
  pkg/ddevapp/config.go
Labels: maintenance

#6134 build: keep ddev-ssh-agent on gitpod, fixes #6132 [skip ci]
  .gitpod.yml
  .gitpod/images/Dockerfile
Labels: maintenance
