Repository ddev/ddev, pull requests merged in 2024-02, with the labels that each got.

#5764 docs: use Stack Overflow email filter for maintainers
  docs/content/developers/maintainers.md
Labels: documentation

#5758 fix: update project schema nodejs_version, for #5400
  pkg/ddevapp/schema.json
Labels: bugfix

#5737 docs: added sql:sanitize to Drupal hook examples.
  docs/content/users/configuration/hooks.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/drupal.go
Labels: documentation

#5765 docs: use zero width non joiner for markdownlint
  docs/content/developers/writing-style-guide.md
  docs/content/users/configuration/config.md
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#5769 test: bump docker-login buildkite plugin to 3.0.0
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-orbstack.yml
  .buildkite/macos-rancher-desktop.yml
  .buildkite/windows10_container.yml
  .buildkite/windows10dockerforwindows.yml
  .buildkite/wsl2-docker-desktop.yml
  .buildkite/wsl2-docker-inside.yml
Labels: maintenance

#5776 test: Revert "test: bump docker-login buildkite plugin to 3.0.0"
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-orbstack.yml
  .buildkite/macos-rancher-desktop.yml
  .buildkite/windows10_container.yml
  .buildkite/windows10dockerforwindows.yml
  .buildkite/wsl2-docker-desktop.yml
  .buildkite/wsl2-docker-inside.yml
Labels: maintenance

#5732 feat: add autocomplete for project name arguments, fixes #4880
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/clean.go
  cmd/ddev/cmd/debug-compose-config.go
  cmd/ddev/cmd/debug-config-yaml.go
  cmd/ddev/cmd/debug-refresh.go
  cmd/ddev/cmd/delete.go
  cmd/ddev/cmd/describe.go
  cmd/ddev/cmd/import-db.go
  cmd/ddev/cmd/logs.go
  cmd/ddev/cmd/mutagen-monitor.go
  cmd/ddev/cmd/mutagen-reset.go
  cmd/ddev/cmd/mutagen-status.go
  cmd/ddev/cmd/mutagen-sync.go
  cmd/ddev/cmd/restart.go
  cmd/ddev/cmd/share.go
  cmd/ddev/cmd/snapshot.go
  cmd/ddev/cmd/ssh.go
  cmd/ddev/cmd/start.go
  cmd/ddev/cmd/stop.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/utils.go
Labels: enhancement

#5779 test: only test macos amd64 on master
  .buildkite/macos-docker-desktop-amd64.yml
Labels: maintenance

#5780 test: CircleCI upgrade to go v1.21
  .ci-scripts/linux_arm64_setup.sh
  .circleci/config.yml
Labels: maintenance

#5686 fix: remove redundant chown in ddev-webserver start.sh, for #4942
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5676 fix: when settings files not set, don't chmod, fixes #5675
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/php.go
Labels: bugfix

#5774 fix: nodejs in web container should be link to /usr/local/bin/node
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/config.go
Labels: bugfix

#5790 build: Use new tag to get new deb.sury.org key (and updated php versions), fixes #5788
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5756 feat: get completion for composer commands
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/composer.go
  cmd/ddev/cmd/composer_test.go
  pkg/exec/exec.go
Labels: enhancement

#5798 build: bump images to v1.22.7 for release, fixes #5633
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5808 docs: Add using current stable version to troubleshooting section
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#5768 docs: Revert "docs: temporarily revert docs on not needing --create-docroot"
  docs/content/users/quickstart.md
Labels: documentation

#5812 test: golangci-lint got pickier, satisfy it
  cmd/ddev/cmd/auth-ssh.go
  cmd/ddev/cmd/auth.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/debug-capabilities.go
  cmd/ddev/cmd/debug-check-db-match.go
  cmd/ddev/cmd/debug-compose-config.go
  cmd/ddev/cmd/debug-config-yaml.go
  cmd/ddev/cmd/debug-dockercheck.go
  cmd/ddev/cmd/debug-download-images.go
  cmd/ddev/cmd/debug-fixcommands.go
  cmd/ddev/cmd/debug-get-volume-db-version.go
  cmd/ddev/cmd/debug-instrumentation-clean.go
  cmd/ddev/cmd/debug-instrumentation-flush.go
  cmd/ddev/cmd/debug-instrumentation.go
  cmd/ddev/cmd/debug-message-conditions.go
  cmd/ddev/cmd/debug-migrate-database.go
  cmd/ddev/cmd/debug-mutagen.go
  cmd/ddev/cmd/debug-nfsmount.go
  cmd/ddev/cmd/debug-refresh.go
  cmd/ddev/cmd/debug-router-nginx-config.go
  cmd/ddev/cmd/debug-test.go
  cmd/ddev/cmd/debug-testcleanup.go
  cmd/ddev/cmd/debug.go
  cmd/ddev/cmd/delete-images.go
  cmd/ddev/cmd/delete.go
  cmd/ddev/cmd/describe.go
  cmd/ddev/cmd/export-db.go
  cmd/ddev/cmd/hostname.go
  cmd/ddev/cmd/import-db.go
  cmd/ddev/cmd/import-files.go
  cmd/ddev/cmd/list.go
  cmd/ddev/cmd/logs.go
  cmd/ddev/cmd/mutagen-logs.go
  cmd/ddev/cmd/mutagen-monitor.go
  cmd/ddev/cmd/mutagen-reset.go
  cmd/ddev/cmd/mutagen.go
  cmd/ddev/cmd/poweroff.go
  cmd/ddev/cmd/pull.go
  cmd/ddev/cmd/push.go
  cmd/ddev/cmd/restart.go
  cmd/ddev/cmd/restore_snapshot.go
  cmd/ddev/cmd/root.go
  cmd/ddev/cmd/service-disable.go
  cmd/ddev/cmd/service-enable.go
  cmd/ddev/cmd/service.go
  cmd/ddev/cmd/snapshot.go
  cmd/ddev/cmd/snapshot_restore.go
  cmd/ddev/cmd/ssh.go
  cmd/ddev/cmd/start.go
  pkg/ddevapp/utils.go
  pkg/testcommon/testcommon.go
  pkg/util/network.go
Labels: maintenance

#5816 feat: support TablePlus application located in setapp directory (#5815)
  pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Labels: enhancement

#5814 fix: follow the zsh naming conventions for completion scripts
  .goreleaser.yml
Labels: bugfix

#5781 docs: show initial and project-checkout Backdrop installation
  docs/content/users/quickstart.md
Labels: documentation

#5785 feat: enable autocompletion for custom commands, fixes #5783
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/global_commands/host/global-host-cmd
  cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/global_commands/web/global-web-cmd
  cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/project_commands/host/project-host-cmd
  cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/project_commands/web/project-web-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/host/autocomplete/global-host-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/host/global-host-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/web/autocomplete/global-web-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/web/global-web-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/host/autocomplete/project-host-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/host/project-host-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/web/autocomplete/project-web-cmd
  cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/web/project-web-cmd
  containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/autocomplete/npm
  pkg/ddevapp/global_dotddev_assets/commands/web/autocomplete/nvm
  pkg/ddevapp/global_dotddev_assets/commands/web/blackfire
  pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
  pkg/ddevapp/global_dotddev_assets/commands/web/xhprof
Labels: enhancement

#5579 build: bump ddev-php-base and ddev-webserver to base on Debian 12 bookworm, replaces #5278
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5831 build: revert implementation of 'head' release, fixes #5830
  .github/workflows/master-build.yml
  .goreleaser.yml
  docs/content/developers/building-contributing.md
Labels: maintenance

#5759 build: filter binaries for deb and rpm on release, fixes #5734
  .goreleaser.yml
Labels: maintenance

#5834 docs: find all DDEV binaries using `which -a ddev`
  docs/content/users/usage/commands.md
  docs/content/users/usage/faq.md
  docs/content/users/usage/troubleshooting.md
  docs/content/users/usage/uninstall.md
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Labels: documentation

#5825 docs: update the section about zsh completions
  docs/content/users/install/shell-completion.md
Labels: documentation

#5833 build: bump traefik to 2.11
  containers/ddev-traefik-router/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5453 refactor: update to Node.js v20 LTS as current default
  .gitpod/images/Dockerfile
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  docs/content/users/usage/commands.md
  pkg/ddevapp/templates.go
  pkg/nodeps/values.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5846 docs: improve buildkite setup for WSL2
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#5842 docs: use PHP 8.3 for the TYPO3 Quickstart
  docs/content/users/quickstart.md
Labels: documentation

#5835 feat: change php default version to 8.2, fixes #5767
  cmd/ddev/cmd/xdebug_test.go
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  docs/content/developers/project-types.md
  docs/content/users/configuration/config.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/extend/customizing-images.md
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/templates.go
  pkg/nodeps/php_values.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#5850 docs: add maintainer docs about remote-config testing
  docs/content/developers/remote-config.md
Labels: documentation

#5851 test: silence docker scout nonsense in buildkite [skip ci]
  .buildkite/test.sh
Labels: maintenance

#5852 docs: don't link check a couple of unstable external urls [skip ci]
  markdown-link-check.json
Labels: documentation

#5854 fix: make `ddev --version` work even if not in project and ~/.ddev/commands not yet created
  pkg/ddevapp/assets.go
Labels: bugfix

#5858 docs: stop checking all stack overflow links
  markdown-link-check.json
Labels: documentation

#5857 docs: mostly warn people off of using xdebug_ide_location
  docs/content/users/configuration/config.md
  docs/content/users/debugging-profiling/step-debugging.md
Labels: documentation

#5853 docs: add auto light / dark mode
  docs/content/assets/extra.css
  mkdocs.yml
Labels: documentation

#5864 docs: buildkite wsl2 setup learning
  .buildkite/testbot_maintenance.sh
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#5869 docs: stop checking link to community.chocolatey.org
  markdown-link-check.json
Labels: documentation

#5848 fix: do not create project network programmatically on `ddev start`, fixes #5810
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5879 test: Minor improvement to TestComposerVersion
  pkg/ddevapp/composer_test.go
Labels: maintenance

#5874 test: Fix TestPantheonPush, broken due to php8.2 default
  pkg/ddevapp/providerPantheon_test.go
Labels: maintenance

#5873 fix: don't panic in app.Describe() if container not found
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5871 fix: ddev start should not continue if web/db containers aren't healthy
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5881 docs: fix 404 link in phpstorm docs
  docs/content/users/debugging-profiling/step-debugging.md
Labels: documentation

#5877 docs: Link to 'Upgrading DDEV' in 'Usage' section
  docs/content/users/usage/index.md
Labels: documentation

#5856 fix: error message 'Error converting to int' on `ddev import-db`
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5878 fix: cache Docker client instead of creating a new one all the time, fixes #5861
  pkg/ddevapp/config_test.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5883 test: exclude TestPHPOverrides on Colima
  pkg/ddevapp/config_test.go
  pkg/ddevapp/hooks_test.go
Labels: maintenance

#5868 fix: don't start 'mutagen daemon run' during ddev stop/delete
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/mutagen.go
Labels: bugfix

#5836 feat: change database default to mariadb:10.11, fixes #5797
  .buildkite/test.sh
  .github/workflows/push-tagged-dbimage.yml
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/debug-migrate-database_test.go
  cmd/ddev/cmd/export-db_test.go
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.0
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.1
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.2
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.3
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.4
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.5
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.6
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.10.7
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.5.5
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.0
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.1
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.2
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.3
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.4
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.5
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.6
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.10.7
  cmd/ddev/cmd/testdata/TestConfigDatabaseVersion/config.yaml.imagespec.5.5
  containers/ddev-dbserver/Dockerfile
  docs/content/users/extend/database-types.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/db.go
  pkg/ddevapp/db_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestConfigMerge/scalartest/components/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.11/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.8/.ddev/config.yaml
  pkg/nodeps/mariadb_values.go
  pkg/nodeps/mariadb_values_darwin_arm64.go
  pkg/nodeps/mariadb_values_linux_arm64.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#5897 test: make sure buildkite leaves docker in sane setup
  .buildkite/test.sh
  .buildkite/testbot_maintenance.sh
  .buildkite/windows10_container.yml
  .buildkite/windows10dockerforwindows.yml
  .buildkite/wsl2-docker-desktop.yml
  .buildkite/wsl2-docker-inside.yml
Labels: maintenance

#5895 docs: point to HEAD version of TestSites array
  docs/content/developers/building-contributing.md
Labels: documentation

#5855 docs: show a warning banner for the latest docs (readthedocs+mkdocs)
  .readthedocs.yaml
  docs/content/developers/maintainers.md
  docs/content/index.md
  docs/content/users/install/ddev-installation.md
  docs/overrides/main.html
  mkdocs.yml
Labels: documentation

#5902 test: more buildkite work, windows not working [skip ci]
  .buildkite/test.sh
Labels: maintenance

#5900 fix: set permissions on /run/php so php-fpm can run
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#5903 docs: update Debugging & Profiling for recent updates to phpstorm ui
  docs/content/images/phpstorm-listen-for-debug-connections.png
  docs/content/users/debugging-profiling/step-debugging.md
Labels: documentation

#5796 docs: add instructions for Grav CMS to quickstart.md
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#5876 docs: fix systemd unit example for casual hosting
  docs/content/users/topics/hosting.md
Labels: documentation

#5905 refactor: point go code to the stable docs
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/root.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/mutagen_config_assets/mutagen.yml
  pkg/ddevapp/router.go
  pkg/ddevapp/templates.go
  pkg/fileutil/files.go
  pkg/globalconfig/global_config.go
Labels: maintenance

#5887 fix: ddev config should not change unspecified options, fixes #5882
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
Labels: bugfix

#5914 docs: mention more Docker providers for macOS
  docs/content/index.md
Labels: documentation
