Repository ddev/ddev, pull requests merged in 2024-05, with the labels that each got.

#6129 build: bump docker-compose to 2.27.0
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6127 docs: Various cleanup items
  docs/content/developers/building-contributing.md
  docs/content/users/extend/additional-services.md
  docs/content/users/install/phpstorm.md
  docs/content/users/usage/managing-projects.md
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#6137 fix: provide sqlite 3.45 for drupal11, fixes #6110
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/drupal.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6144 fix: Add host.docker.internal and customizations to ddev debug test
  cmd/ddev/cmd/scripts/test_ddev.sh
  pkg/ddevapp/dotddev_assets/php/php-example.ini.example
Labels: bugfix

#6151 build: show badges for Gitpod and GitHub Codespaces in PRs
  .github/workflows/pr-artifacts-comment.yml
Labels: maintenance

#6150 docs: install curl for Debian/Ubuntu and WSL2, fixes #5915
  docs/content/users/install/ddev-installation.md
  scripts/install_ddev_wsl2_docker_desktop.ps1
Labels: documentation

#6171 docs: encourage people to use latest stable version
  .github/ISSUE_TEMPLATE/bug_report.yml
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/users/usage/troubleshooting.md
  markdown-link-check.json
Labels: documentation

#6154 fix: show error in `ddev debug refresh`
  cmd/ddev/cmd/debug-refresh.go
Labels: bugfix

#6172 test: Use newer technique to cancel in-progress builds
  .github/workflows/cancel-previous-workflow.yml
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/docscheck.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/pr-check.yml
  .github/workflows/tests.yml
Labels: maintenance

#6153 fix: close global traefik file after creation
  pkg/ddevapp/traefik.go
Labels: bugfix

#6133 fix: getDatabaseBackups() should check error on .downloads deletion
  pkg/ddevapp/provider.go
Labels: bugfix

#6168 fix: check for valid db version in `ddev debug migrate-database`
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/debug-migrate-database.go
  docs/content/users/extend/database-types.md
  pkg/nodeps/values.go
Labels: bugfix

#6170 fix: add timeout for install_nvm.sh
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6177 docs: fix broken anchor links
  docs/content/developers/release-management.md
  docs/content/developers/testing-docs.md
  docs/content/index.md
  docs/content/users/configuration/config.md
  docs/content/users/debugging-profiling/step-debugging.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/install/docker-installation.md
  docs/content/users/install/phpstorm.md
  docs/content/users/quickstart.md
  docs/content/users/usage/architecture.md
  docs/content/users/usage/faq.md
Labels: documentation

#6176 docs: Add info about #ddev-generated for apache-fpm users
  docs/content/users/extend/customization-extendibility.md
Labels: documentation

#6165 feat: set Drupal database to mariadb default on config update, fixes #6160
  pkg/ddevapp/drupal.go
Labels: enhancement

#6175 fix: retrieve Drupal 11 sqlite3 packages from snapshot.debian.org
  pkg/ddevapp/config.go
Labels: bugfix

#6126 build: update hardened/prod healthcheck.sh, for #6033
  containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/healthcheck.sh
Labels: maintenance

#6184 build: bump images to v1.23.1 for release
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6081 fix: Skip hidden directories when creating commands
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/testdata/TestCustomCommands/global_commands/.hiddendir/not-a-command
Labels: bugfix

#6082 feat: Add toggle option for xhprof command, rework xdebug, fixes #5782
  pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
  pkg/ddevapp/global_dotddev_assets/commands/web/xhprof
Labels: enhancement

#6118 feat: Add support for negative default in confirm prompt, fixes #6103
  cmd/ddev/cmd/push.go
  pkg/util/prompt.go
  pkg/util/utils_test.go
Labels: enhancement

#5943 fix: Gitpod and Codespaces can use HTTPS
  pkg/ddevapp/utils.go
Labels: bugfix

#6197 docs: Fix a couple of broken link fragments
  docs/content/developers/release-management.md
  docs/content/developers/testing-docs.md
Labels: documentation

#6198 docs: Fix markdownlint problems by using different headers instead of different links
  docs/content/developers/release-management.md
  docs/content/developers/testing-docs.md
Labels: documentation

#6196 build: fix Codespaces link
  .github/workflows/pr-artifacts-comment.yml
  README.md
Labels: maintenance

#6194 build: fix devcontainers postCreateCommand permissions, fixes #6187
  .devcontainer/devcontainer.json
  .devcontainer/setup_test_project.sh
Labels: maintenance

#6193 fix: do not send autocomplete commands to Amplitude, fixes #6189
  cmd/ddev/cmd/root.go
Labels: bugfix

#6200 build: update .gitpod.yml for v1.23.1 release
  .gitpod.yml
Labels: maintenance

#6214 build: Remove concurrency/cancellation check on pr-build as it's useless [skip ci]
  .github/workflows/pr-check.yml
Labels: maintenance

#6219 test: Update drupal11 test to 11.0.0-beta1
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#6217 fix: PHP CodeSniffer on settings.ddev.php for Drupal 8 - 11
  pkg/ddevapp/drupal/drupal/settings.ddev.php
  pkg/ddevapp/drupal/drupal10/settings.ddev.php
  pkg/ddevapp/drupal/drupal11/settings.ddev.php
  pkg/ddevapp/drupal/drupal8/settings.ddev.php
  pkg/ddevapp/drupal/drupal9/settings.ddev.php
Labels: bugfix

#6218 docs: add link to TYPO3 ddev guides
  docs/content/users/quickstart.md
Labels: documentation

#6213 docs: Add Debugging long mutagen startup time
  docs/content/users/install/performance.md
Labels: documentation

#6211 fix: TYPO3 no longer has typo3cms command, update other out-of-date
  .spellcheckwordlist.txt
  cmd/ddev/cmd/commands_test.go
  docs/content/users/usage/cms-settings.md
  docs/content/users/usage/managing-projects.md
  pkg/ddevapp/global_dotddev_assets/commands/web/typo3cms
  pkg/ddevapp/templates.go
  pkg/ddevapp/typo3.go
  pkg/ddevapp/typo3/AdditionalConfiguration.php
Labels: bugfix

#6208 fix: add more checks for existing approot
  cmd/ddev/cmd/config.go
  pkg/ddevapp/config.go
Labels: bugfix

#6220 docs: add Vite infobox for Laravel quickstart
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#6224 docs: typo in faq "thew"
  docs/content/users/usage/faq.md
Labels: documentation

#6207 docs: Explain how to switch from nvm to `nodejs_version`, fixes #6204
  docs/content/users/configuration/config.md
Labels: documentation

#6223 fix: Improve instructional output on 'ddev config'
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
Labels: bugfix

#6199 fix: do not remove mounted files directory, fixes #6188
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/craftcms.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/magento.go
  pkg/ddevapp/shopware6.go
  pkg/ddevapp/typo3.go
  pkg/ddevapp/upload_dirs.go
  pkg/ddevapp/wordpress.go
Labels: bugfix

#6209 fix: do not validate config in ddev clean, delete -O, stop -U
  cmd/ddev/cmd/clean.go
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/delete.go
  cmd/ddev/cmd/stop.go
  cmd/ddev/cmd/utils.go
  pkg/ddevapp/config.go
Labels: bugfix

#6227 docs: make textlint stop complaining about command line tool
  docs/content/users/usage/developer-tools.md
Labels: documentation

#6136 feat: output the VIRTUAL_HOST if specified in environment variables of a service
  cmd/ddev/cmd/describe.go
  pkg/ddevapp/ddevapp.go
Labels: enhancement

#5813 feat: generalize HOMEDIR management and respect XDG_CONFIG_HOME, fixes #5807
  .buildkite/test.sh
  .spellcheckwordlist.txt
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/config_test.go
  cmd/ddev/cmd/homeadditions_test.go
  cmd/ddev/cmd/mutagen-version.go
  cmd/ddev/cmd/root.go
  cmd/ddev/cmd/root_test.go
  docs/content/users/install/performance.md
  docs/content/users/usage/architecture.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/uninstall.md
  pkg/ddevapp/config.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/mutagen_test.go
  pkg/dockerutil/docker_compose_version_test.go
  pkg/globalconfig/global_config.go
  pkg/testcommon/testcommon.go
  pkg/version/version.go
  scripts/diagnose_mutagen.sh
Labels: enhancement

#6253 fix: ImportDB() and ddev import-db should remove new mariadb-dump line, for #6249
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#6257 fix: Make export-db also remove new mariadb directive in dumpfile , fixes #6249
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/providerLagoon_test.go
Labels: bugfix

#6258 test: Fix test failures on master of Rancher, Colima, Windows
  cmd/ddev/cmd/homeadditions_test.go
  cmd/ddev/cmd/import-db_test.go
  cmd/ddev/cmd/root_test.go
  pkg/ddevapp/hooks_test.go
Labels: maintenance

#6261 fix: tail for mariadb export-db doesn't work on older mariadb
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#6264 test: Skip TestAutocompletionForCustomCmds because of slow mount responses
  cmd/ddev/cmd/autocompletion_test.go
Labels: maintenance

#6265 build: download mkcert from github
  .ci-scripts/generate_artifacts.sh
Labels: maintenance

#6266 build: bump upload-artifact to v4 and fix mkcert.exe in tarball/zipball [skip ci]
  .ci-scripts/generate_artifacts.sh
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
Labels: maintenance

#6267 docs: install mysql-client instead of mariadb on macOS
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#6262 test: Try to fix windows problems with TestPoweroffOnNewVersion
  .buildkite/windows10dockerforwindows.yml
  cmd/ddev/cmd/root_test.go
  cmd/ddev/cmd/start_test.go
  pkg/testcommon/testcommon.go
Labels: maintenance
