Repository ddev/ddev, pull requests merged in 2024-06, with the labels that each got.

#6269 test: Don't use php package in TestExtraPackages
  pkg/ddevapp/config_test.go
Labels: maintenance

#6268 fix: detect Rancher Desktop, fixes #6259
  pkg/version/version.go
Labels: bugfix

#6248 docs: add link to contributor trainings
  docs/content/developers/building-contributing.md
Labels: documentation

#6238 docs: improve FAQ - communication between projects
  docs/content/users/usage/faq.md
Labels: documentation

#6192 fix: Drupal - switch to sendmail transport always in settings.ddev.php
  pkg/ddevapp/drupal/drupal/settings.ddev.php
  pkg/ddevapp/drupal/drupal10/settings.ddev.php
  pkg/ddevapp/drupal/drupal11/settings.ddev.php
  pkg/ddevapp/drupal/drupal9/settings.ddev.php
Labels: bugfix

#6229 docs: Add a small update noting either a subdomain or arbitrary domain.
  docs/content/users/extend/custom-compose-files.md
Labels: documentation

#6247 docs: improve contributing via gitpod
  docs/content/developers/building-contributing.md
Labels: documentation

#6226 docs: Update PHPStorm instructions to include COMPOSE_PROJECT_NAME in manual instructions
  docs/content/users/install/phpstorm.md
Labels: documentation

#6236 build: standardize apt-get usage, remove blackfire from apt sources, for #6235, for #6078
  .github/devcontainers/src/install-ddev/install.sh
  cmd/ddev/cmd/scripts/test_ddev.sh
  containers/ddev-ssh-agent/Dockerfile
  containers/ddev-webserver/Dockerfile
  docs/content/developers/building-contributing.md
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/users/extend/customizing-images.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  docs/content/users/install/shell-completion.md
  docs/content/users/usage/faq.md
  docs/content/users/usage/uninstall.md
  pkg/ddevapp/config.go
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
  pkg/versionconstants/versionconstants.go
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
Labels: dependencies, maintenance

#6271 test: TestCopyIntoVolume should clean up after itself [skip ci]
  pkg/dockerutil/dockerutils_test.go
Labels: maintenance

#6270 refactor: make "waiting for" message more generic
  pkg/ddevapp/ddevapp.go
Labels: maintenance

#6272 build: Use github instead of dl.filippo.io to get mkcert binary
  Makefile
Labels: maintenance

#6239 fix: prevent various Mutagen conflicts between daemons when changing versions or global directory, fixes #6234
  .buildkite/test.sh
  cmd/ddev/cmd/a.go
  cmd/ddev/cmd/mutagen-cmd_test.go
  cmd/ddev/cmd/mutagen-logs.go
  cmd/ddev/cmd/restart.go
  cmd/ddev/cmd/root.go
  cmd/ddev/cmd/root_test.go
  docs/content/users/install/performance.md
  docs/content/users/usage/architecture.md
  docs/content/users/usage/uninstall.md
  pkg/archive/archive.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/hooks_test.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/mutagen_test.go
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils.go
  pkg/exec/exec.go
  pkg/fileutil/file_hash.go
  pkg/fileutil/file_hash_test.go
  pkg/globalconfig/global_config.go
  pkg/testcommon/testcommon.go
Labels: bugfix

#6278 build: bump goreleaser to v2, update its action to v6
  .github/workflows/master-build.yml
  .goreleaser.yml
Labels: maintenance

#6277 docs: fix mutagen example command
  docs/content/users/install/performance.md
Labels: documentation

#6279 refactor: remove backticks from ddev mailpit in ddev describe info text, fixes #6276
  cmd/ddev/cmd/describe.go
Labels: maintenance

#6283 refactor: Update to new amplitude/analytics-go
  go.mod
  go.sum
  vendor/github.com/amplitude/analytics-go/amplitude/constants/constants.go
  vendor/github.com/amplitude/analytics-go/amplitude/plugins/destination/internal/amplitude_http_client.go
  vendor/modules.txt
Labels: dependencies, maintenance

#6285 test: fix TestFileHash on Windows, fixes #6284
  cmd/ddev/cmd/auth-ssh.go
  cmd/ddev/cmd/debug-test.go
  cmd/ddev/cmd/exec_test.go
  pkg/ddevapp/providerLocalfile_test.go
  pkg/ddevapp/ssh_auth_test.go
  pkg/dockerutil/dockerutils.go
  pkg/fileutil/file_hash.go
  pkg/fileutil/file_hash_test.go
  pkg/util/utils.go
Labels: maintenance

#6282 fix: make self-upgrade command respect spaces, fixes #6274
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Labels: bugfix

#6263 feat: don't override ddev-generated built-in project files created by add-on, fixes #6173, fixes #6190
  cmd/ddev/cmd/auth-ssh_test.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/debug-test.go
  pkg/archive/archive.go
  pkg/ddevapp/addons.go
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/assets.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/config.go
  pkg/ddevapp/craftcms.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/django.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/magento.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/shopware6.go
  pkg/ddevapp/ssh_auth_test.go
  pkg/ddevapp/typo3.go
  pkg/ddevapp/wordpress.go
  pkg/dockerutil/dockerutils.go
  pkg/fileutil/embed.go
  pkg/fileutil/files.go
  pkg/fileutil/files_test.go
  pkg/testcommon/testcommon.go
  pkg/util/utils.go
Labels: enhancement

#6288 docs: Update commands.md to add detail for `debug migrate-database`
  docs/content/users/usage/commands.md
  markdown-link-check.json
Labels: documentation

#6242 fix: create `working_dir` for `web` if it doesn't exist, fixes #6158
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#6291 build: Bump mysql to 8.0.36, fixes #6250
  containers/ddev-dbserver/Makefile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6290 fix: Use mariadb repositories for mariadb-client, for #6083
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6296 docs: update first step in project-types.md
  docs/content/developers/project-types.md
Labels: documentation

#6299 build: bump yq to v4.44.1
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6293 feat: add warnings for global commands when they are "unknown", for #5523, for #6275
  cmd/ddev/cmd/commands.go
  pkg/ddevapp/global_dotddev_assets/commands/web/drush
  pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
Labels: enhancement

#6281 fix: Composer post-root-package-install didn't work with Mutagen enabled
  cmd/ddev/cmd/composer-create.go
Labels: bugfix

#6304 test: Fix TestAcquiaPush and TestLagoonPush, add mariadb-old clients, fixes #6295
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6305 fix: Don't terminate mutagen sessions on upgrade/version change
  cmd/ddev/cmd/root.go
Labels: bugfix

#6310 docs: update instructions for cleaning up old `ddev` binaries
  docs/content/users/install/ddev-upgrade.md
  docs/content/users/usage/faq.md
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#6309 fix: Support MySQL 5.5 and 5.6 on ddev-webserver by using MySQL 5.7 clients
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  pkg/ddevapp/config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6312 build: prepare images for v1.23.2
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6315 build: use $XDG_CONFIG_HOME in Gitpod for v1.23.2 release, for #6228 [skip ci]
  .gitpod.yml
  .gitpod/images/Dockerfile
Labels: maintenance

#6195 feat: add `--skip-hooks` global flag to avoid running hooks, fixes #2129, fixes #6185
  cmd/ddev/cmd/root.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/hooks_test.go
Labels: enhancement

#6322 docs: Remove stray info about packages from hooks docs
  docs/content/users/configuration/hooks.md
Labels: documentation

#6320 docs: Add FAQ about checking in .ddev
  docs/content/users/usage/faq.md
Labels: documentation

#6319 docs: suggestion ddev --version, move mkcert -install to later
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Labels: documentation

#6325 docs: update the link to upgrade DDEV in faq.md
  docs/content/users/usage/faq.md
Labels: documentation

#6324 fix: generated gitignore is not working correctly
  pkg/ddevapp/config.go
  pkg/ddevapp/utils.go
Labels: bugfix

#6327 refactor: error handling for PR artifact comment [skip ci]
  .github/workflows/pr-artifacts-comment.yml
Labels: maintenance

#6336 docs: pacify textlint on mysql/https
  .github/workflows/docscheck.yml
  docs/content/users/topics/sharing.md
  docs/content/users/usage/database-management.md
Labels: documentation

#6330 docs: revisit WSL Docker Desktop setup instructions
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/developers/scripts/windows_buildkite_start.ps1
  pkg/ddevapp/config_test.go
Labels: documentation

#6333 fix: autodownload yarn from corepack, and set cache-folder, fixes #6332
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
  pkg/ddevapp/app_compose_template.yaml
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6341 docs: windows-wsl2-dd needs apt install for ngrok
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#6340 build: check docker-compose 2.28.1
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6329 fix: use real path to global config location, fixes #6328
  cmd/ddev/cmd/config-global.go
  pkg/ddevapp/list.go
  pkg/fileutil/files.go
Labels: bugfix

#6347 test: stop running nightly tests [skip ci]
  .github/workflows/tests.yml
Labels: maintenance

#6314 test: Attempt to debug TestProcessHooks intermittent failures, fixes #6313
  pkg/ddevapp/hooks_test.go
Labels: maintenance

#6346 fix: Drupal 10 and Drupal 11 settings have migrated, set state_cache
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/drupal/backdrop/settings.ddev.php
  pkg/ddevapp/drupal/backdrop/settings.php
  pkg/ddevapp/drupal/drupal/settings.ddev.php
  pkg/ddevapp/drupal/drupal/settings.php
  pkg/ddevapp/drupal/drupal10/settings.ddev.php
  pkg/ddevapp/drupal/drupal10/settings.php
  pkg/ddevapp/drupal/drupal11/settings.ddev.php
  pkg/ddevapp/drupal/drupal11/settings.php
  pkg/ddevapp/drupal/drupal6/settings.ddev.php
  pkg/ddevapp/drupal/drupal6/settings.php
  pkg/ddevapp/drupal/drupal7/settings.ddev.php
  pkg/ddevapp/drupal/drupal7/settings.php
  pkg/ddevapp/drupal/drupal8/settings.ddev.php
  pkg/ddevapp/drupal/drupal8/settings.php
  pkg/ddevapp/drupal/drupal9/settings.ddev.php
  pkg/ddevapp/drupal/drupal9/settings.php
Labels: bugfix

#6334 build: use IPv4 inside a container, mariadb-client 11.4 for the webserver
  .goreleaser.yml
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/debug-migrate-database.go
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/gai.conf
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/templates.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6303 fix: pass all valid options to nested commands in `ddev composer create`, fixes #6300, fixes #6246, for #5058
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/composer.json
  cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/test-ddev-require-dev/composer.json
  cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/test-ddev-require/composer.json
  docs/content/users/quickstart.md
  docs/content/users/usage/developer-tools.md
Labels: bugfix

#6348 build: enable building windows arm64 binaries, fixes #6344
  .ci-scripts/generate_artifacts.sh
  .circleci/config.yml
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .goreleaser.yml
  Makefile
  docs/content/developers/building-contributing.md
  docs/content/developers/release-management.md
  pkg/nodeps/mariadb_values_arm64.go
  pkg/nodeps/mariadb_values_linux_arm64.go
  pkg/nodeps/mysql_values_arm64.go
  pkg/nodeps/mysql_values_linux_arm64.go
Labels: maintenance

#6354 docs: Fix textlint usage, make textlint work on PRs
  .github/workflows/docscheck.yml
  .textlintignore
  .textlintrc
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/developers/release-management.md
  docs/content/users/configuration/config.md
  docs/content/users/extend/additional-services.md
  docs/content/users/providers/index.md
  docs/content/users/usage/commands.md
  version-history.md
Labels: documentation

#6255 docs: Joomla Quickstart
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#6256 docs: Initial draft for adding a quickstart for Sulu, fixes #6230
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation
