Repository ddev/ddev, pull requests merged in 2024-11, with the labels that each got.

#6673 test: tests.yml needs to check out full depth [skip ci]
  .github/workflows/colima-tests.yml
  .github/workflows/tests.yml
Labels: maintenance

#6645 feat: add `ddev debug match-constraint`
  cmd/ddev/cmd/debug-capabilities_test.go
  cmd/ddev/cmd/debug-match-constraint.go
  cmd/ddev/cmd/debug-match-constraint_test.go
  docs/content/users/usage/commands.md
Labels: enhancement

#6644 feat: add `ddev cd` command, fixes #6639
  cmd/ddev/cmd/cd.go
  cmd/ddev/cmd/cd_test.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
Labels: enhancement

#6693 test: run full tests that are sometimes short-circuited
  .github/workflows/tests.yml
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: maintenance

#6697 test: Try to get lima and colima sane with LIMA_SSH_PORT_FORWARDER
  .buildkite/macos-colima.yml
  .buildkite/macos-colima_vz.yml
  .buildkite/macos-lima.yml
Labels: maintenance

#6684 docs: note that setting a nodejs version always downloads something
  docs/content/users/configuration/config.md
Labels: documentation

#6674 docs: Add Contao recipe to Quickstarts
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#6698 docs: use apache-fpm for Kirby CMS
  docs/content/users/quickstart.md
Labels: documentation

#6695 feat: add WordPress WP_ENVIRONMENT_TYPE support to wp-config-ddev.php
  pkg/ddevapp/wordpress/wp-config-ddev.php
Labels: enhancement

#6676 docs: rearrange documentation on making PRs
  CONTRIBUTING.md
  docs/content/developers/building-contributing.md
Labels: documentation

#6691 build: Remove unsupported PHP versions by default, fixes #5984
  containers/ddev-php-base/Dockerfile
  containers/ddev-php-base/generic-files/usr/local/bin/install_php_extensions.sh
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
  containers/ddev-webserver/tests/ddev-webserver/test.sh
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/nodeps/php_values.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6704 fix: match snapshot using full filename, fixes #6694
  pkg/ddevapp/snapshot.go
  pkg/ddevapp/snapshot_test.go
Labels: bugfix

#6687 fix: escape dollar sign $ properly in .env, for #6406, fixes #6683
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/dotenv-set.go
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/busybox/install.yaml
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/envfile.go
  pkg/ddevapp/testdata/TestPHPConfig/.ddev/.env
  pkg/ddevapp/testdata/TestPHPConfig/phpinfo.php
Labels: bugfix

#6710 build: fix static errors from golangci-lint
  pkg/ddevapp/provider.go
  pkg/globalconfig/global_config_test.go
Labels: maintenance

#6708 test: Fix TestGetAllURLs failure on tb-wsldd-16
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#6707 fix: not-included PHP version should work with webimage_extra_packages
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#6711 fix: use TARGETARCH instead of TARGETPLATFORM in user Dockerfiles
  pkg/ddevapp/config.go
Labels: bugfix

#6712 refactor: use `n install --cleanup`
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6678 feat: allow files and symlinks in `ddev auth ssh`, fixes #5465, fixes #6677
  cmd/ddev/cmd/auth-ssh.go
  docs/content/users/usage/commands.md
Labels: enhancement

#6724 fix: Improve clarity in explanation by removing awkward 'normally', fixes #6723
  pkg/ddevapp/hostname_mgt.go
Labels: bugfix

#6713 docs: Update schema.json to include cakephp project type
  pkg/ddevapp/schema.json
Labels: documentation

#6721 docs: fix 8.3 typo and adding PHP version strategy
  docs/content/users/extend/customization-extendibility.md
Labels: documentation

#6717 fix: make "Shopware Update" work with nginx, fixes #6656
  pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
Labels: bugfix

#6718 fix: Move the custom php8.0-xdebug build from ddev-webserver to user Dockerfile
  containers/ddev-php-base/Dockerfile
  containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config.go
  pkg/ddevapp/hooks_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6692 feat: add dynamic timeout for scripts on start
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/log-stderr.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/n-install.sh
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6732 test: ignore TestCmdVersion when running in IDE without make [skip ci]
  cmd/ddev/cmd/cmd_version_test.go
Labels: maintenance

#6716 fix: don't require go and make for ordinary homebrew installation, fixes #6156, fixes #6623
  .github/workflows/master-build.yml
  .goreleaser.yml
  Makefile
  docs/content/developers/building-contributing.md
  docs/content/developers/release-management.md
  scripts/install_ddev_head.sh
Labels: bugfix

#6741 fix: get composer/git to stop complaining about safe dir
  containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.gitconfig
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6745 build: add timeout to `docker-compose build`
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
Labels: maintenance

#6738 fix: Move sqlite3 3.45 installation into ddev-webserver, fixes #6735
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6747 build: add more timeouts for `apt-get update`, remove custom `php8.0-xdebug`, for #6745
  .github/workflows/container-tests.yml
  cmd/ddev/cmd/scripts/test_ddev.sh
  containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
  containers/ddev-php-base/generic-files/usr/local/bin/install_php_extensions.sh
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6749 fix: Deprecate and hide ddev service commands, fixes #6298
  cmd/ddev/cmd/service-disable.go
  cmd/ddev/cmd/service-enable.go
  cmd/ddev/cmd/service.go
Labels: bugfix

#6756 fix: use correct path for Windows in custom configs
  pkg/ddevapp/config.go
  pkg/fileutil/files.go
Labels: bugfix

#6763 docs: update how to create project types
  docs/content/developers/project-types.md
  docs/content/users/configuration/config.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/templates.go
Labels: documentation

#6761 fix: Set correct DATABASE_URL for CakePHP project using Postgres, fixes #6760
  pkg/ddevapp/cakephp.go
Labels: bugfix

#6762 docs: explain how to update/remove/override `vendor/bin/composer`, for #6604
  docs/content/users/configuration/config.md
  mkdocs.yml
Labels: documentation

#6740 docs: Remove random docs stanzas and tweaks
  docs/content/developers/release-management.md
  docs/content/users/configuration/config.md
  docs/content/users/debugging-profiling/step-debugging.md
  docs/content/users/extend/additional-services.md
  docs/content/users/extend/custom-compose-files.md
  docs/content/users/extend/customizing-images.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  docs/content/users/install/phpstorm.md
  docs/content/users/install/shell-completion.md
  docs/content/users/usage/faq.md
Labels: documentation

#6739 fix: remove nginx proxy router, fixes #5940
  .github/workflows/container-tests.yml
  .github/workflows/push-tagged-image.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config-global_test.go
  cmd/ddev/cmd/debug-router-nginx-config.go
  cmd/ddev/cmd/debug-router-nginx-config_test.go
  containers/push-all.sh
  docs/content/developers/building-contributing.md
  docs/content/users/configuration/config.md
  docs/content/users/extend/custom-tls-certificates.md
  docs/content/users/extend/traefik-router.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/troubleshooting.md
  pkg/ddevapp/router.go
  pkg/ddevapp/router_compose_template.yaml
  pkg/ddevapp/router_test.go
  pkg/ddevapp/testdata/TestRouterConfigOverride/router-compose.extras.yaml
  pkg/ddevapp/traefik_test.go
  pkg/docker/images.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/schema.json
  pkg/globalconfig/types/types.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6770 fix: Update old mutagen warning
  pkg/ddevapp/mutagen.go
Labels: bugfix

#6779 build: do not run `.buildkite/test.sh` if we want to skip
  .buildkite/macos-colima.yml
  .buildkite/macos-colima_vz.yml
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-lima.yml
  .buildkite/macos-orbstack.yml
  .buildkite/macos-rancher-desktop.yml
  .buildkite/test.sh
  .buildkite/windows10_container.yml
  .buildkite/windows10dockerforwindows.yml
  .buildkite/wsl2-docker-desktop.yml
  .buildkite/wsl2-docker-inside.yml
Labels: maintenance

#6776 docs: add note about XHGui
  .spellcheckwordlist.txt
  docs/content/users/debugging-profiling/xhprof-profiling.md
Labels: documentation

#6775 refactor: Improve nginx config for Laravel, fixes #6774, fixes #6751
  pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
Labels: maintenance

#6772 build: always use /usr/local/bin/composer, fixes #6771
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/composer.go
  cmd/ddev/cmd/composer_test.go
  containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
  containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
  docs/content/users/configuration/config.md
  pkg/ddevapp/composer.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6764 build: add missing php8.4 extensions, use PECL for php8.4-xdebug, fixes #6465
  cmd/ddev/cmd/xdebug_test.go
  containers/ddev-php-base/Dockerfile
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/mods-available/xdebug.ini
  containers/ddev-php-base/generic-files/etc/php-packages.yaml
  containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6750 fix: Move drupal11 to its own project type, make "drupal" an alias for latest drupal, fixes #6635
  .buildkite/test.sh
  .circleci/config.yml
  .github/workflows/tests.yml
  .travis.yml
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  docs/content/users/configuration/config.md
  docs/content/users/quickstart.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/composer_test.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/global_dotddev_assets/commands/web/drush
  pkg/ddevapp/hardened_test.go
  pkg/ddevapp/mutagen_test.go
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerGit_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/providerLocalfile_test.go
  pkg/ddevapp/providerPantheon_test.go
  pkg/ddevapp/providerPlatform_test.go
  pkg/ddevapp/providerUpsun_test.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/settings_test.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestDetectAppType/backdrop/core/scripts/backdrop.sh
  pkg/ddevapp/testdata/TestDetectAppType/cakephp/bin/cake.php
  pkg/ddevapp/testdata/TestDetectAppType/craftcms/craft
  pkg/ddevapp/testdata/TestDetectAppType/drupal10/web/core/lib/Drupal.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal10/web/index.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal11/web/core/lib/Drupal.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal11/web/index.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal6/misc/ahah.js
  pkg/ddevapp/testdata/TestDetectAppType/drupal7/docroot/index.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal7/docroot/misc/ajax.js
  pkg/ddevapp/testdata/TestDetectAppType/drupal8/web/core/lib/Drupal.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal8/web/index.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal9/web/core/lib/Drupal.php
  pkg/ddevapp/testdata/TestDetectAppType/drupal9/web/index.php
  pkg/ddevapp/testdata/TestDetectAppType/laravel/artisan
  pkg/ddevapp/testdata/TestDetectAppType/magento/README.md
  pkg/ddevapp/testdata/TestDetectAppType/magento2/SECURITY.md
  pkg/ddevapp/testdata/TestDetectAppType/magento2/pub/index.php
  pkg/ddevapp/testdata/TestDetectAppType/shopware6/composer.json
  pkg/ddevapp/testdata/TestDetectAppType/silverstripe/vendor/bin/sake
  pkg/ddevapp/testdata/TestDetectAppType/typo3/typo3/.gitmanaged
  pkg/ddevapp/testdata/TestDetectAppType/wordpress/wp-settings.php
  pkg/nodeps/values.go
  pkg/testcommon/testcommon.go
Labels: bugfix

#6785 test: use Wordpress for testing Windows
  .buildkite/test.sh
  pkg/ddevapp/hardened_test.go
Labels: maintenance

#6782 docs: Update version-history.md for v1.24 [skip buildkite]
  version-history.md
Labels: documentation

#6778 fix: Update amplitude reporting for v1.24, fixes #6619
  ampli.json
  pkg/ddevapp/amplitude_project.go
  third_party/ampli/ampli.go
Labels: bugfix

#6786 build: bump Xdebug to 3.4.0 and docker-compose to v2.31.0
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6792 test: Exclude Colima from TestHardenedStart [skip ci]
  pkg/ddevapp/hardened_test.go
Labels: maintenance

#6780 build: Bump drush 8 version to 8.5.0
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance
