Repository ddev/ddev, pull requests merged in 2024-08, with the labels that each got.

#6447 docs: show actual running context in `install.yaml` for add-ons
  docs/content/users/extend/additional-services.md
Labels: documentation

#6433 feat: add `ddev_version_constraint` for add-ons, remove `#ddev-nodisplay`, fixes #5969
  cmd/ddev/cmd/get.go
  cmd/ddev/cmd/get_test.go
  cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdGetDdevVersionConstraint/invalid_constraint_recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdGetDdevVersionConstraint/project/.gitmanaged
  cmd/ddev/cmd/testdata/TestCmdGetDdevVersionConstraint/valid_constraint_recipe/install.yaml
  docs/content/users/configuration/config.md
  docs/content/users/extend/additional-services.md
  pkg/ddevapp/addons.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/utils.go
Labels: enhancement

#6420 feat: add support for `n install auto`, add `N_PREFIX` cache, replace node repo with `n`, fixes #6418
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/n-install.sh
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
  docs/content/users/configuration/config.md
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/nodejs_test.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestNodeJSVersions/.nvmrc
  pkg/ddevapp/testdata/TestNodeJSVersions/package.json
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6453 docs: promote drupal 11 now that it's released, for #6452
  docs/content/users/quickstart.md
Labels: documentation

#6454 test: Update tests for Drupal11 to latest tarballs, fixes #6452
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#6449 docs: update magento1 and backdrop quickstarts, fixes #6448
  docs/content/users/quickstart.md
Labels: documentation

#6442 docs: store magento2 credentials in the global config, for #5932, for #6380
  docs/content/users/quickstart.md
Labels: documentation

#6459 test: mysql-client 9.0 in homebrew is broken, use 8.0
  .buildkite/testbot_maintenance.sh
  docs/content/developers/buildkite-testmachine-setup.md
Labels: maintenance

#6434 feat: add aliases for custom commands, `art` alias for `artisan`, `ddev aliases` command, fixes #6443
  cmd/ddev/cmd/aliases.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/commands_test.go
  docs/content/users/extend/custom-commands.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/artisan
Labels: enhancement

#6455 feat: add `log-stderr.sh` command, for #6451, for #6420
  .buildkite/test.sh
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/log-stderr.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/n-install.sh
  pkg/ddevapp/ddevapp.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6422 fix: show containers we're waiting for and better error message on timeout/unhealthy
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
Labels: bugfix

#6460 build: bump images to v1.23.4 and docker-compose to v2.29.1
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6464 docs: add readable tab anchors
  mkdocs.yml
Labels: documentation

#6466 docs: Remove unnecessary and failing links to Travis CI
  docs/content/users/topics/remote-docker.md
Labels: documentation

#6470 test: minor updates to avoid use of literals 80 and 443
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/testcommon/testcommon_test.go
Labels: maintenance

#6467 docs: add instruction how to brew upgrade ddev head
  docs/content/developers/building-contributing.md
Labels: documentation

#6485 ci: add new check from golangci-lint
  cmd/ddev/cmd/debug-mutagen.go
  cmd/ddev/cmd/debug-nfsmount.go
  pkg/ddevapp/addons.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
  pkg/exec/exec.go
  pkg/util/debug.go
Labels: maintenance

#6478 fix: drupal class_loader_auto_detect no longer needed
  pkg/ddevapp/drupal/drupal10/settings.ddev.php
  pkg/ddevapp/drupal/drupal11/settings.ddev.php
  pkg/ddevapp/drupal/drupal9/settings.ddev.php
Labels: bugfix

#6479 docs: mention using docker builder for offline
  docs/content/users/usage/offline.md
Labels: documentation

#6468 feat: automatic timezone detection from `$TZ` env or `/etc/localtime` symlink, fixes #6458
  docs/content/users/configuration/config.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/templates.go
Labels: enhancement

#6490 feat: output snapshot list as a table, fixes #6116
  cmd/ddev/cmd/snapshot.go
  cmd/ddev/cmd/snapshot_restore.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/snapshot.go
Labels: enhancement

#6494 fix: Lets Encrypt traefik formatting was broken, fixes #6486
  docs/content/users/configuration/config.md
  docs/content/users/topics/hosting.md
  docs/content/users/topics/index.md
  docs/content/users/topics/remote-docker.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/traefik.go
  pkg/ddevapp/traefik_config_template.yaml
Labels: bugfix

#6471 docs: ddev debug test should suggest current stable [skip ci]
  cmd/ddev/cmd/debug-test.go
Labels: documentation

#6414 feat: adds support to ephemeral ports for 80/443, fixes #5326
  .github/workflows/tests.yml
  cmd/ddev/cmd/auth-ssh_test.go
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/composer_test.go
  cmd/ddev/cmd/debug-nfsmount_test.go
  cmd/ddev/cmd/debug-router-nginx-config_test.go
  cmd/ddev/cmd/describe_test.go
  cmd/ddev/cmd/exec_test.go
  cmd/ddev/cmd/get_test.go
  cmd/ddev/cmd/list_test.go
  cmd/ddev/cmd/mutagen-cmd_test.go
  cmd/ddev/cmd/restart_test.go
  cmd/ddev/cmd/ssh_test.go
  docs/content/users/usage/troubleshooting.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/hooks_test.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_test.go
  pkg/ddevapp/traefik_test.go
  pkg/dockerutil/dockerutils.go
  pkg/netutil/netutil.go
Labels: enhancement

#6502 docs: clearer statement about `ddev start` before offline, for #6499
  docs/content/users/usage/offline.md
Labels: documentation

#6504 test: Improve several tests, make sure containers get removed
  pkg/archive/archive_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/dockerutil/dockerutils_test.go
  pkg/fileutil/files_test.go
Labels: maintenance

#6507 fix: Make sure that we actually wait for bound ports to be released
  pkg/ddevapp/router.go
Labels: bugfix

#6506 test: Rancher Desktop and other problems when non-default ports used
  cmd/ddev/cmd/ssh_test.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/router_test.go
Labels: maintenance

#6496 fix: flush mutagen after deletion of .downloads directory
  cmd/ddev/cmd/commands.go
  pkg/ddevapp/addons.go
  pkg/ddevapp/envfile_test.go
  pkg/ddevapp/provider.go
  pkg/fileutil/files.go
  pkg/fileutil/files_test.go
  pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/one.txt
  pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/subdir/subdir-three.txt
  pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/subdir/subdir2/subdir-four.txt
  pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/two.txt
Labels: bugfix

#6482 refactor: Refactor `ddev get` to `ddev add-on` and into sub-commands, fixes #6146
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/addon-list.go
  cmd/ddev/cmd/addon-remove.go
  cmd/ddev/cmd/addon.go
  cmd/ddev/cmd/addon_test.go
  cmd/ddev/cmd/get.go
  cmd/ddev/cmd/get_test.go
  cmd/ddev/cmd/scripts/test_ddev.sh
  cmd/ddev/cmd/service-enable.go
  cmd/ddev/cmd/testdata/TestCmdAddon/ddev-memcached.tar.gz
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/docker-compose.example.yaml
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/file-with-no-ddev-generated.txt
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/globalextras/nosig.txt
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/globalextras/okfile.txt
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/projectextras/okfile.txt
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/projectextras/somefiles/nosig.txt
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/tests/test.bats
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/tests/testdata/.gitmanaged
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/project/.platform.app.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/project/.platform/local/.gitignore
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/project/.platform/local/README.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/project/.platform/local/project.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/project/.platform/routes.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/project/.platform/services.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/extra/has-ddev-generated.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/extra/no-ddev-generated.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/junk_darwin_amd64.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/junk_darwin_arm64.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/junk_linux_amd64.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/junk_linux_arm64.txt
  cmd/ddev/cmd/testdata/TestCmdAddonComplex/recipe/junk_windows_amd64.txt
  cmd/ddev/cmd/testdata/TestCmdAddonDdevVersionConstraint/invalid_constraint_recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonDdevVersionConstraint/project/.gitmanaged
  cmd/ddev/cmd/testdata/TestCmdAddonDdevVersionConstraint/valid_constraint_recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonDependencies/dependency_recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonDependencies/depender_recipe/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonDependencies/project/.gitmanaged
  docs/content/users/extend/additional-services.md
  docs/content/users/extend/database-types.md
  docs/content/users/providers/platform.md
  docs/content/users/quickstart.md
  docs/content/users/usage/architecture.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/addons.go
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
  pkg/ddevapp/global_dotddev_assets/commands/host/phpmyadmin
Labels: maintenance

#6514 docs: fix link for advanced add-ons, for #6482
  docs/content/users/extend/additional-services.md
Labels: documentation

#6509 test: fix TestExtraPortExpose with correct URL
  pkg/ddevapp/extra_expose_test.go
  pkg/ddevapp/hooks_test.go
  pkg/ddevapp/router.go
  pkg/netutil/netutil.go
Labels: maintenance
