Repository ddev/ddev, pull requests merged in 2024-01, with the labels that each got.

#5670 fix: make sure wsl v2 is used, not wsl v1, fixes #5667 [skip ci]
  docs/content/users/install/ddev-installation.md
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
Labels: bugfix

#5716 docs: temporarily revert docs on not needing --create-docroot
  docs/content/users/quickstart.md
Labels: documentation

#5719 docs: fix gitpod PR link
  docs/content/developers/building-contributing.md
Labels: documentation

#5661 fix: Add correct mime types for Javascript
  containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/mods-available/mime.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5668 fix: remove CRAFT_WEB_URL, fixes #5665
  pkg/ddevapp/craftcms.go
Labels: bugfix

#5695 fix: remove --json-output flag from `logs` command, fixes #962
  cmd/ddev/cmd/logs.go
Labels: bugfix

#5701 docs: Overhaul Shell Completion & Autocomplete documentation
  docs/content/users/install/shell-completion.md
Labels: documentation

#5702 feat: allow global host commands to be run from anywhere, for #4416
  .spellcheckwordlist.txt
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/testdata/TestCustomCommands/global_commands/host/testhostglobal-noproject
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Labels: enhancement

#5707 fix: use init option to prevent zombie ddev-router, for #5705
  pkg/ddevapp/router_compose_template.yaml
Labels: bugfix

#5714 fix: acli output has changed, capture the output file correctly, fixes #5697
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
Labels: bugfix

#5715 docs: expand docs on PHP extension installation, including pecl
  docs/content/users/extend/customizing-images.md
Labels: documentation

#5718 docs: fix localdev foundation -> DDEV foundation, for #4848
  .spellcheckwordlist.txt
  docs/content/developers/release-management.md
  docs/content/users/code-of-conduct.md
  docs/content/users/usage/faq.md
  mkdocs.yml
  winpkg/chocolatey/ddev.nuspec
  winpkg/ddev.nsi
Labels: documentation

#5721 fix: make xhprof faster, fixes #5712
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof/xhprof_prepend.php
  docs/content/users/debugging-profiling/xhprof-profiling.md
  pkg/ddevapp/dotddev_assets/xhprof/xhprof_prepend.php
Labels: bugfix

#5728 feat: Platform.sh specific app pull, fixes #5727
  docs/content/users/providers/platform.md
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
Labels: enhancement

#5733 docs: Update Drupal 9 & 10 CMS Quickstarts
  docs/content/users/debugging-profiling/xhprof-profiling.md
  docs/content/users/quickstart.md
Labels: documentation

#5738 feat: add WSL2 support to tableplus command
  pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Labels: enhancement

#5741 feat: add environment and name to TablePlus command
  pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Labels: enhancement
