Repository ddev/ddev, pull requests merged in 2024-12, with the labels that each got.

#6777 docs: make installing a Downloaded Binary in the $PATH clearer
  docs/content/developers/building-contributing.md
  docs/content/images/github-action-pr-comment.png
Labels: documentation

#6789 fix: do not run project validation for `ddevcd`, for #6743
  cmd/ddev/cmd/debug-cd.go
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.zsh
  pkg/globalconfig/global_config.go
Labels: bugfix

#6788 fix: add validation to web_extra_exposed_ports, fixes #6417
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#6787 build: traefik: bump image, add timezone, show custom configs, update healthcheck, fixes #6463
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-traefik-router/traefik_healthcheck.sh
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_compose_template.yaml
  pkg/ddevapp/ssh_auth.go
  pkg/dockerutil/dockerutils.go
  pkg/util/utils.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6797 build: bump images to v1.24.0 for release
  containers/ddev-php-base/Dockerfile
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/mods-available/xdebug.ini
  containers/ddev-php-base/generic-files/etc/php-packages.yaml
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6725 feat: add Symfony project type
  containers/ddev-webserver/tests/ddev-webserver/test.sh
  docs/content/developers/project-types.md
  docs/content/users/configuration/config.md
  docs/content/users/quickstart.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/global_dotddev_assets/commands/web/console
  pkg/ddevapp/schema.json
  pkg/ddevapp/symfony.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestDetectAppType/symfony/bin/console
  pkg/ddevapp/testdata/TestDetectAppType/symfony/src/Kernel.php
  pkg/nodeps/values.go
Labels: enhancement

#6796 refactor: make `ddev auth ssh` flags mutually exclusive, fixes #6795
  cmd/ddev/cmd/auth-ssh.go
  docs/content/users/usage/commands.md
Labels: maintenance

#6794 fix: Change traefik log level to ERROR and limit accessLog
  containers/ddev-traefik-router/test/testdata/.static_config.yaml
  docs/content/users/extend/traefik-router.md
  pkg/ddevapp/global_dotddev_assets/traefik/README.md
  pkg/ddevapp/global_dotddev_assets/traefik/static_config.loglevel.yaml.example
  pkg/ddevapp/testdata/TestTraefikStaticConfig/extraPlugin/expectation.yaml
  pkg/ddevapp/testdata/TestTraefikStaticConfig/logChange/expectation.yaml
  pkg/ddevapp/testdata/TestTraefikStaticConfig/logChange/static_config.log_change.yaml
  pkg/ddevapp/traefik_static_config_template.yaml
Labels: bugfix

#6799 docs: Remove twitter, add bluesky [skip ci]
  .spellcheckwordlist.txt
  docs/content/developers/maintainers.md
  docs/content/users/support.md
  mkdocs.yml
Labels: documentation

#6798 test: Skip TestWriteableFilesDirectory on Rancher [skip ci]
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#6805 fix: show system databases in DBeaver, add more Windows binaries, fixes #6730, fixes #6654
  pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
Labels: bugfix

#6801 fix: improve `ddev debug test`
  cmd/ddev/cmd/scripts/test_ddev.sh
Labels: bugfix

#6804 build: extend default locales with es_ES, es_MX, pt_PT and pt_BR
  containers/ddev-webserver/Dockerfile
  docs/content/users/extend/customizing-images.md
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6813 test: Stop testing for NFS capability
  .buildkite/sanetestbot.sh
  .github/workflows/sanetestbot.sh
  Makefile
  docs/content/users/install/performance.md
Labels: maintenance

#6819 docs: use shortlink for discord access
  .github/ISSUE_TEMPLATE/config.yml
  containers/ddev-dbserver/README.md
  containers/ddev-gitpod-base/README.md
  containers/ddev-nginx-proxy-router/README.md
  containers/ddev-php-base/README.md
  containers/ddev-ssh-agent/README.md
  containers/ddev-traefik-router/README.md
  containers/ddev-webserver/README.md
  containers/image_readme_template.md
  containers/test-ssh-server/README.md
  docs/content/developers/maintainers.md
  docs/content/users/extend/additional-services.md
  docs/content/users/extend/custom-compose-files.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/providers/index.md
  docs/content/users/support.md
  docs/content/users/usage/architecture.md
  docs/content/users/usage/faq.md
  mkdocs.yml
Labels: documentation

#6815 fix: remove python leftovers, for #6733
  .spellcheckwordlist.txt
  containers/ddev-webserver/Dockerfile
  docs/content/users/usage/commands.md
  pkg/ddevapp/config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6814 feat: add CLI completion for sake for Silverstripe CMS 6+ (plus some docs changes)
  docs/content/users/quickstart.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/autocomplete/sake
Labels: enhancement

#6817 refactor: pre-download sqlite3 3.45.1 for Drupal 11, fixes #6807
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6821 fix: correct panic on ddev describe on gitpod
  cmd/ddev/cmd/describe.go
Labels: bugfix

#6826 test: Remove a couple of tests from lima/colima/rancher execution
  pkg/ddevapp/config_test.go
  pkg/ddevapp/hardened_test.go
Labels: maintenance

#6824 fix: show correct warning for Dockerfiles in `web-build` and `db-build`
  pkg/ddevapp/config.go
Labels: bugfix

#6822 docs: update magento2, pimcore, sulu quickstarts
  docs/content/users/quickstart.md
Labels: documentation

#6831 test: Add configuration verification tests for mariadb and mysql
  containers/ddev-dbserver/Makefile
  containers/ddev-dbserver/files/etc/my.cnf
  containers/ddev-dbserver/test/basic_database.bats
  containers/ddev-dbserver/test/custom_config.bats
  containers/ddev-dbserver/test/database_config.bats
  containers/ddev-dbserver/test/testdata/custom_config/mysql/collation.cnf
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.0.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.1.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.11.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.2.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.3.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.4.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.5.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.6.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.7.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.8.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_11.4.ini
  containers/ddev-dbserver/test/testdata/database_config/mariadb_5.5.ini
  containers/ddev-dbserver/test/testdata/database_config/mysql_5.5.ini
  containers/ddev-dbserver/test/testdata/database_config/mysql_5.6.ini
  containers/ddev-dbserver/test/testdata/database_config/mysql_5.7.ini
  containers/ddev-dbserver/test/testdata/database_config/mysql_8.0.ini
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6836 docs: how to add unsupported PHP versions without `ddev config`, fixes #6835
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/extend/customizing-images.md
Labels: documentation

#6843 docs: Remove run-ddev-on-old-mac from faq
  docs/content/users/usage/faq.md
Labels: documentation

#6810 fix: don't copy Dockerfiles to `*imageBuild` folder, add examples to assets, fixes #6757
  docs/content/users/extend/customizing-images.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/dotddev_assets/db-build/Dockerfile.example
  pkg/ddevapp/dotddev_assets/db-build/README.txt
  pkg/ddevapp/dotddev_assets/web-build/Dockerfile.example
  pkg/ddevapp/dotddev_assets/web-build/README.txt
  pkg/ddevapp/dotddev_assets/web-entrypoint.d/README.txt
Labels: bugfix

#6837 fix: mount OpenSSH certificate for `auth ssh`, fixes #6832
  cmd/ddev/cmd/auth-ssh.go
Labels: bugfix

#6839 build: reorganize `ddev-webserver` packages, add `vim` alternative, fixes #6840
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6784 feat: accept all args in `ddev composer create`, add `create-project` alias, fixes #6766
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/config.go
  pkg/ddevapp/ddevapp.go
Labels: enhancement

#6842 feat: Add pager to database output
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/global_dotddev_assets/commands/db/mysql
Labels: enhancement

#6834 fix: add CI to instrumentation tags
  ampli.json
  pkg/ddevapp/amplitude_project.go
  pkg/ddevapp/instrumentation.go
  pkg/ddevapp/instrumentation_test.go
  third_party/ampli/ampli.go
Labels: bugfix

#6849 build: bump go-pretty and x/crypto, fixes #6844
  go.mod
  go.sum
  vendor/github.com/jedib0t/go-pretty/v6/table/render.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_init.go
  vendor/github.com/jedib0t/go-pretty/v6/table/row.go
  vendor/github.com/jedib0t/go-pretty/v6/table/table.go
  vendor/github.com/jedib0t/go-pretty/v6/table/writer.go
  vendor/github.com/jedib0t/go-pretty/v6/text/align.go
  vendor/github.com/jedib0t/go-pretty/v6/text/ansi.go
  vendor/github.com/jedib0t/go-pretty/v6/text/direction.go
  vendor/github.com/jedib0t/go-pretty/v6/text/string.go
  vendor/github.com/jedib0t/go-pretty/v6/text/wrap.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/text/width/kind_string.go
  vendor/golang.org/x/text/width/tables10.0.0.go
  vendor/golang.org/x/text/width/tables11.0.0.go
  vendor/golang.org/x/text/width/tables12.0.0.go
  vendor/golang.org/x/text/width/tables13.0.0.go
  vendor/golang.org/x/text/width/tables15.0.0.go
  vendor/golang.org/x/text/width/tables9.0.0.go
  vendor/golang.org/x/text/width/transform.go
  vendor/golang.org/x/text/width/trieval.go
  vendor/golang.org/x/text/width/width.go
  vendor/modules.txt
Labels: dependencies, maintenance

#6855 fix: remove nfs setup script from install_ddev.sh [skip ci]
  scripts/install_ddev.sh
Labels: bugfix

#6850 docs: add Laravel Installer quickstart
  docs/content/users/quickstart.md
Labels: documentation

#6860 test: Use linkspector instead of markdown-link-check, fixes #6859
  .github/workflows/docscheck.yml
  .linkspector.yml
  Makefile
  markdown-link-check.json
Labels: maintenance

#6862 docs: bump mkdocs/readthedocs dependencies for python 3.13
  .readthedocs.yaml
  docs/content/developers/project-types.md
  docs/content/index.md
  docs/content/users/debugging-profiling/step-debugging.md
  docs/mkdocs-pip-requirements
Labels: documentation

#6864 docs: Update mkdocs installation as docker doesn't work [skip ci]
  Makefile
  docs/content/developers/testing-docs.md
Labels: documentation

#6863 docs: Add link to hostnames article on ddev.com
  docs/content/users/usage/offline.md
Labels: documentation

#6829 docs: Add a quickstart for drupal cms
  docs/content/users/quickstart.md
Labels: documentation

#6846 docs: add CiviCRM Standalone to quickstart.md
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#6848 docs: Add database management examples including how to create empty database
  docs/content/users/usage/database-management.md
Labels: documentation

#6851 build: new `ddev mariadb` command, adjust `~/.my.cnf` to always use `root`, hide some Docker build warnings, fixes #6462
  cmd/ddev/cmd/commands_test.go
  cmd/ddev/cmd/exec.go
  containers/ddev-dbserver/Dockerfile
  containers/ddev-dbserver/files/etc/environment
  containers/ddev-dbserver/files/etc/profile
  containers/ddev-dbserver/files/etc/skel/.my.cnf
  containers/ddev-ssh-agent/Dockerfile
  containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.my.cnf
  docs/content/users/usage/commands.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/global_dotddev_assets/commands/db/mariadb
  pkg/ddevapp/global_dotddev_assets/commands/db/mysql
  pkg/ddevapp/global_dotddev_assets/commands/db/mysqldump.example
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6869 test: Minor updates to linux-setup.sh
  .github/workflows/linux-setup.sh
  .github/workflows/selfhosted-upgrades.sh
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#6866 test: get more disk space on hosted runner, switch to ubuntu 24.04, fixes #6865
  .github/workflows/pr-build.yml
  .github/workflows/push-tagged-dbimage.yml
  .github/workflows/tests.yml
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/providerPantheon_test.go
  pkg/testcommon/testcommon.go
  pkg/testcommon/testcommon_test.go
Labels: maintenance

#6868 test: Add bats test coverage for backdrop quickstart, for #6222
  .github/workflows/quickstart.yml
  Makefile
  docs/content/users/quickstart.md
  docs/tests/backdrop.bats
  docs/tests/common-setup.bash
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance
