Repository ddev/ddev, pull requests merged in 2024-07, with the labels that each got.

#6360 fix: add mysqladmin to web container for mysql, fixes #6355
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  containers/ddev-webserver/tests/ddev-webserver/general.bats
  pkg/ddevapp/ddevapp_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6363 fix: add chmod for /var/log, for #5898
  pkg/ddevapp/config.go
Labels: bugfix

#6365 fix: install extra content in Dockerfile earlier, for #4394
  pkg/ddevapp/config.go
Labels: bugfix

#6359 fix: Check to see if IP address is local to determine whether to add to hosts
  pkg/ddevapp/hostname_mgt.go
  pkg/netutil/netutil.go
Labels: bugfix

#6091 fix: do not explicitly set the backdrop_drupal_compatibility and update_free_access settings, fixes #6090
  pkg/ddevapp/drupal.go
  pkg/ddevapp/drupal/backdrop/settings.ddev.php
  pkg/ddevapp/drupal/backdrop/settings.php
Labels: bugfix

#6369 build: bump images to v1.23.3
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6371 build: Bump gitpod image for DDEV v1.23.3 [skip ci]
  .gitpod.yml
Labels: maintenance

#6317 fix: Update to Traefik v3, make Let's Encrypt work with Traefik, fixes #6183, for #5940, fixes #4632
  .spellcheckwordlist.txt
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-traefik-router/test/containertest.sh
  containers/ddev-traefik-router/test/testdata/.static_config.yaml
  docs/content/developers/release-management.md
  docs/content/users/configuration/config.md
  docs/content/users/extend/custom-tls-certificates.md
  docs/content/users/extend/traefik-router.md
  docs/content/users/topics/hosting.md
  pkg/ddevapp/config.go
  pkg/ddevapp/global_dotddev_assets/traefik/README.md
  pkg/ddevapp/global_dotddev_assets/traefik/static_config.fail2ban.yaml.example
  pkg/ddevapp/router_compose_template.yaml
  pkg/ddevapp/traefik.go
  pkg/ddevapp/traefik_config_template.yaml
  pkg/ddevapp/traefik_global_config_template.yaml
  pkg/ddevapp/traefik_static_config_template.yaml
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/dockerutil/testdata/TestCopyIntoVolume2/.test.sh
  pkg/dockerutil/testdata/TestCopyIntoVolume2/root.txt
  pkg/dockerutil/testdata/TestCopyIntoVolume2/subdir1/only-the-new-stuff.txt
  pkg/fileutil/files.go
  pkg/globalconfig/global_config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6370 build: Use ENV = in Dockerfile
  containers/ddev-dbserver/Dockerfile
  containers/ddev-nginx-proxy-router/Dockerfile
  containers/ddev-php-base/Dockerfile
  containers/ddev-ssh-agent/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config.go
Labels: maintenance

#6374 build: percona xtrabackup changed install technique
  containers/ddev-dbserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6378 test: stop testing deprecated nginx-proxy [skip ci]
  .github/workflows/tests.yml
Labels: maintenance

#6377 fix: improve installation method for mariadb-client
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6384 fix: Don't warn about Docker Desktop on WSL2, fixes #6339 [skip ci]
  cmd/ddev/cmd/scripts/test_ddev.sh
Labels: bugfix

#6387 docs: stop checking aur.archlinux.org link [skip ci]
  markdown-link-check.json
Labels: documentation

#6385 fix: Install matching postgresql client versions in ddev-webserver, fixes #6139
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/ssh_auth.go
  pkg/ddevapp/testdata/TestWebserverMariaMySQLDBClient/mariadb/users.sql
  pkg/ddevapp/testdata/TestWebserverMariaMySQLDBClient/mysql/users.sql
  pkg/ddevapp/testdata/TestWebserverMariaMySQLDBClient/postgres/users.sql
  pkg/ddevapp/testdata/TestWebserverPostgresDBClient/postgres/users.sql
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6390 fix: omit ddev-router for Gitpod (for DDEV PRs) [skip ci]
  .gitpod.yml
Labels: bugfix

#6391 fix: make `ddev launch` fully compatible with Gitpod and Codespaces, fixes #6389
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
Labels: bugfix

#6382 fix: make composer subcommands ignore invalid flags on any errors, fixes #6380
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/composer-create_test.go
Labels: bugfix

#6395 feat: add ddev/ddev-utilities to the pulled images
  pkg/ddevapp/ddevapp.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6400 ci: update Codespaces link, fixes #6399 [skip ci]
  .github/workflows/pr-artifacts-comment.yml
  README.md
Labels: maintenance

#6343 feat: add global phpmyadmin install command, fixes #6342
  cmd/ddev/cmd/commands_test.go
  pkg/ddevapp/global_dotddev_assets/commands/host/phpmyadmin
Labels: enhancement

#6393 test: stop testing use_docker_compose_from_path, update related docs
  docs/content/users/configuration/config.md
  docs/content/users/extend/additional-services.md
  pkg/dockerutil/docker_compose_version_test.go
  pkg/globalconfig/global_config.go
Labels: maintenance

#6398 fix: Use port 80 to get better headers for Codespaces, fixes #6102
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#6403 docs: correct config used to add extra-packages
  docs/content/users/quickstart.md
Labels: documentation

#6404 docs: Update 'ddev get' example
  docs/content/users/extend/additional-services.md
Labels: documentation

#6407 test: make sure that volumes in buildkite are deleted at test start
  .buildkite/test.sh
Labels: maintenance

#6210 feat: Replace underscores with hyphens in project-name, fixes #6206
  cmd/ddev/cmd/config.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
Labels: enhancement

#6409 docs: remove CircleCI badge as we aren't running their tests
  README.md
Labels: documentation

#6408 build: try out docker-compose v2.29.0
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6202 fix: clear omit_containers, additional_fqdns, additional_hostnames config with empty flag, fixes #6140
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config-global_test.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  docs/content/users/usage/commands.md
Labels: bugfix

#6411 fix: Use turn off innodb_doublewrite to improve import-db performance, fixes #6244
  containers/ddev-dbserver/files/etc/my.cnf
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6415 fix: default_container_timeout should work right, fixes #5133 again
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/snapshot.go
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.intervalandretriesset.yaml
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.intervalset.yaml
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.longtimeout.yaml
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.nohealthcheck.yaml
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.nospec.yaml
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.withlongstartperiod.yaml
  pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.withshortstartperiod.yaml
Labels: bugfix

#6423 test: Skip TestSSHAuth on Colima
  pkg/ddevapp/ssh_auth_test.go
Labels: maintenance

#6426 fix: fail gently if sqlite3 can't be downloaded for drupal11, fixes #6425, for #6419
  pkg/ddevapp/config.go
Labels: bugfix

#6396 docs: improve WSL2 buildkite install instructions
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#6436 docs: Add tip how to setup additional hostnames debug
  docs/content/users/debugging-profiling/step-debugging.md
Labels: documentation

#6427 fix: create mutagen-agents tarball if it doesn't exist, fixes #6421
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/mutagen_test.go
Labels: bugfix

#6439 docs: improve placement of .env for environment variables
  docs/content/users/configuration/config.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/quickstart.md
Labels: documentation
