Repository ddev/ddev, pull requests merged in 2024-10, with the labels that each got.

#6581 fix: remove unused file for router, for #5266
  pkg/ddevapp/assets.go
  pkg/ddevapp/router_Dockerfile_template
Labels: bugfix

#6575 build: add bash-completion to standard packages
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6582 build: fix Docker's InvalidDefaultArgInFrom warning
  containers/ddev-dbserver/Dockerfile
  pkg/ddevapp/config.go
Labels: maintenance

#6567 feat: support postgres:17, fixes #6566
  cmd/ddev/cmd/config_test.go
  docs/content/users/extend/database-types.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/postgres/17/postgresql.conf
  pkg/ddevapp/templates.go
  pkg/nodeps/postgres_values.go
Labels: enhancement

#6406 feat: expand `.ddev/.env.*` files on `ddev start`, add `ddev dotenv`, add variable expansion to `ddev add-on get`, fixes #4430
  Makefile
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/dotenv-get.go
  cmd/ddev/cmd/dotenv-set.go
  cmd/ddev/cmd/dotenv.go
  cmd/ddev/cmd/dotenv_test.go
  cmd/ddev/cmd/scripts/test_ddev.sh
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/bare-busybox/docker-compose.bare-busybox.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/bare-busybox/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/busybox/docker-compose.busybox.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/busybox/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/env_files/.env
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/env_files/.env.busybox.example
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/env_files/.env.example
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/env_files/.env.redis
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/env_files/.env.web
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/project/.gitmanaged
  cmd/ddev/cmd/utils.go
  docs/content/users/extend/additional-services.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/envfile.go
Labels: enhancement

#6546 feat: show warnings from stderr, auto rebuild for web image w/o cache on warnings, fixes #6451, for #5073
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6580 feat: rename refresh to rebuild in `ddev debug refresh`, allow to build different services, add cache flag
  cmd/ddev/cmd/debug-rebuild.go
  cmd/ddev/cmd/debug-rebuild_test.go
  cmd/ddev/cmd/debug-refresh_test.go
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/users/extend/customizing-images.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/troubleshooting.md
  pkg/ddevapp/templates.go
Labels: enhancement

#6568 refactor: exclude web and db from waiting for containers, fixes #6493, for #6422
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/dockerutils.go
Labels: maintenance

#6588 test: Use composer 2.8.0 for TestComposerCreateCmd until composer bug is fixed, for #6586
  cmd/ddev/cmd/composer-create_test.go
Labels: maintenance

#6585 test: fix Windows path in TestCmdAddonComplex
  cmd/ddev/cmd/addon-get_test.go
Labels: maintenance

#6569 refactor: install vim-tiny instead of vim to save 30MB on images
  containers/ddev-php-base/Dockerfile
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/cli/php.ini
  containers/ddev-webserver/Dockerfile
  pkg/ddevapp/config_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6597 build: ddev-webserver Dockerfile should check for bash errors
  containers/ddev-webserver/Dockerfile
Labels: maintenance

#6590 docs: Add link to "omit" DB configuration
  docs/content/users/usage/database-management.md
Labels: documentation

#6596 test: use Packagist package `ddev/ddev-test-composer-create`, fixes #6586
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/composer.json
  cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/test-ddev-require-dev/composer.json
  cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/test-ddev-require/composer.json
  docs/content/developers/maintainers.md
Labels: maintenance

#6587 feat: Create Windows ARM64 installer, for #6344, fixes #5817
  .circleci/config.yml
  .github/RELEASE_NOTES_TEMPLATE.md
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .goreleaser.yml
  Makefile
  docs/content/developers/release-management.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  pkg/ddevapp/hostname_mgt.go
  pkg/globalconfig/global_config_test.go
  winpkg/chocolatey/tools/chocolateyinstall.ps1
  winpkg/ddev.nsi
Labels: enhancement

#6605 docs: wsl2 buildkite-agents no longer need homebrew
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#6603 fix: improve timezone detection, for #6468
  pkg/ddevapp/ddevapp.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: bugfix

#6609 feat: validation for database versions in `schema.json` [skip ci]
  pkg/ddevapp/schema.json
Labels: enhancement

#6564 feat: pass X-Accel-* headers to client, fixes #6563
  pkg/ddevapp/webserver_config_assets/nginx-site-backdrop.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal6.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal7.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal8.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-magento.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-php.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-wordpress.conf
  pkg/ddevapp/webserver_config_assets/nginx_second_docroot_example-site-php.conf
Labels: enhancement

#6600 docs: update `web_environment` usage, fixes #6599
  docs/content/users/debugging-profiling/blackfire-profiling.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/providers/acquia.md
  docs/content/users/providers/index.md
  docs/content/users/providers/lagoon.md
  docs/content/users/providers/pantheon.md
  docs/content/users/providers/platform.md
  docs/content/users/providers/upsun.md
  docs/content/users/usage/cms-settings.md
  pkg/ddevapp/dotddev_assets/providers/README.txt
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
  pkg/ddevapp/dotddev_assets/providers/lagoon.yaml
  pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
  pkg/ddevapp/dotddev_assets/providers/upsun.yaml
  pkg/ddevapp/templates.go
  pkg/globalconfig/global_config.go
Labels: documentation

#6608 docs: remove markdown link check on archive.org
  markdown-link-check.json
Labels: documentation

#6607 docs: sort commands alphabetically, add missing aliases
  docs/content/users/usage/commands.md
Labels: documentation

#6604 fix: use Cmd instead of RawCmd to execute composer and put vendor/bin first in PATH, fixes #6602
  containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
  containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
  containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
  pkg/ddevapp/composer.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6595 feat: Remove 127.0.0.1 from start and restart message, place in one function, fixes #6500
  cmd/ddev/cmd/restart.go
  cmd/ddev/cmd/restart_test.go
  cmd/ddev/cmd/start.go
  cmd/ddev/cmd/start_test.go
Labels: enhancement

#6593 fix: check only for IPv4 in DNS lookup, fixes #6592
  pkg/ddevapp/hostname_mgt.go
  pkg/dockerutil/dockerutils.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/global_config_test.go
  pkg/netutil/netutil.go
Labels: bugfix

#6614 docs: Remove non-working DDEV doc reference in TYPO3 docs
  docs/content/users/quickstart.md
Labels: documentation

#6610 docs: Improve port conflict documentation and provide a link to the issue
  docs/content/users/usage/troubleshooting.md
  pkg/ddevapp/router.go
Labels: documentation

#6611 docs: show results of including composer/composer
  docs/content/users/configuration/config.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/developer-tools.md
Labels: documentation

#6612 fix: don't try to release not-bound ports
  pkg/ddevapp/router.go
  pkg/netutil/netutil.go
Labels: bugfix

#6613 build: push gitpod and codespaces images/packages during release
  .ci-scripts/linux_arm64_setup.sh
  .circleci/linux_docker_buildx_setup.sh
  .github/devcontainers/src/install-ddev/devcontainer-feature.json
  .github/workflows/container-tests.yml
  .github/workflows/master-build.yml
  .github/workflows/push-tagged-dbimage.yml
  .github/workflows/push-tagged-image.yml
  .gitpod.yml
  .gitpod/images/push.sh
  .goreleaser.yml
  containers/containers_shared.mak
  containers/containers_shared.mk
  containers/ddev-dbserver/Makefile
  containers/ddev-dbserver/build_image.sh
  containers/ddev-dbserver/test/basic_database.bats
  containers/ddev-dbserver/test/custom_config.bats
  containers/ddev-dbserver/test/functions.sh
  containers/ddev-gitpod-base/Dockerfile
  containers/ddev-gitpod-base/Makefile
  containers/ddev-gitpod-base/README.md
  containers/ddev-gitpod-base/test/containertest.sh
  containers/ddev-gitpod-base/test/testdata/.gitmanaged
  containers/ddev-nginx-proxy-router/Makefile
  containers/ddev-php-base/Makefile
  containers/ddev-ssh-agent/Makefile
  containers/ddev-traefik-router/Makefile
  containers/ddev-webserver/Makefile
  containers/devcontainers/install-ddev/README.md
  containers/devcontainers/install-ddev/devcontainer-feature.json
  containers/devcontainers/install-ddev/install.sh
  containers/push-all.sh
  containers/test-ssh-server/Makefile
  docs/content/developers/building-contributing.md
  docs/content/developers/release-management.md
Labels: maintenance

#6615 feat: add validation for `ddev dotenv` flags, for #6406
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/dotenv-get.go
  cmd/ddev/cmd/dotenv-set.go
  cmd/ddev/cmd/dotenv_test.go
  cmd/ddev/cmd/utils.go
  pkg/appimport/appimport.go
Labels: enhancement

#6618 build: bump images to v1.23.5 and docker-compose to v2.29.7, fixes #6606
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6620 fix: Some UPSUN environment variables are now PLATFORM_ environment variables
  docs/content/users/providers/upsun.md
  pkg/ddevapp/dotddev_assets/providers/upsun.yaml
  pkg/ddevapp/providerUpsun_test.go
Labels: bugfix

#6622 build: make latest tag same hash, push latest for most
  containers/containers_shared.mk
  containers/ddev-dbserver/build_image.sh
  containers/ddev-gitpod-base/Dockerfile
  containers/ddev-gitpod-base/Makefile
  containers/ddev-nginx-proxy-router/Dockerfile
  containers/ddev-nginx-proxy-router/Makefile
  containers/ddev-php-base/Makefile
  containers/ddev-ssh-agent/Dockerfile
  containers/ddev-ssh-agent/Makefile
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-traefik-router/Makefile
  containers/ddev-webserver/Makefile
  containers/test-ssh-server/Dockerfile
  containers/test-ssh-server/Makefile
Labels: maintenance

#6625 build: disable repo tagging for devcontainers, for #6613 [skip ci]
  .github/workflows/devcontainer-feature-release.yaml
  .github/workflows/master-build.yml
Labels: maintenance

#6632 docs: add docker volumes to ddev uninstall docs
  docs/content/users/usage/uninstall.md
Labels: documentation

#6637 docs: Fix copy-paste error in add-on list docs
  docs/content/users/usage/commands.md
Labels: documentation

#6648 build: try new mutagen 0.18.0
  pkg/testcommon/testcommon_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6652 fix: make drupal detection only detect drupal8+
  pkg/ddevapp/drupal.go
Labels: bugfix

#6529 fix: help mutagen work with Drupal's read-only settings files, fixes #6491
  pkg/ddevapp/drupal.go
  pkg/ddevapp/mutagen.go
Labels: bugfix

#6662 fix: improve `ddev describe` output for HTTP only, fixes #6661
  cmd/ddev/cmd/describe.go
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#6649 refactor: add `drush` and `composer` command aliases, fixes #6642
  cmd/ddev/cmd/composer.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/drush
Labels: maintenance

#6650 fix: validate `--all` flag with args in `ddev delete`, for #6209
  cmd/ddev/cmd/delete.go
Labels: bugfix

#6666 docs: update link to Backdrop documentation, fixes #6573
  pkg/ddevapp/backdrop.go
Labels: documentation

#6626 docs: mention how to use xdebug with drush 13+
  docs/content/users/debugging-profiling/step-debugging.md
  docs/content/users/usage/cms-settings.md
Labels: documentation

#6634 feat: ignore config.*.local.y*ml
  docs/content/users/extend/customization-extendibility.md
  pkg/ddevapp/config.go
Labels: enhancement

#6570 refactor: install limited locales by default, provide configuration for additional locales, for #5984
  containers/ddev-webserver/Dockerfile
  docs/content/users/extend/customizing-images.md
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance
