Repository ddev/ddev, pull requests merged in 2024-03, with the labels that each got.

#5909 docs: Add Pimcore quickstart, fixes #5843
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
Labels: documentation

#5927 docs: Use backticks when referencing custom command annotations, fixes #5820
  .spellcheckwordlist.txt
  docs/content/users/extend/custom-commands.md
Labels: documentation

#5924 docs: update faq with new questions, fix menus
  .spellcheckwordlist.txt
  Makefile
  docs/content/users/providers/index.md
  docs/content/users/topics/index.md
  docs/content/users/usage/faq.md
  mkdocs.yml
Labels: documentation

#5930 docs: fix extraneous '#' in FAQ
  docs/content/users/usage/faq.md
Labels: documentation

#5922 fix: magento2 requires mariadb 10.6, for #5919
  docs/content/users/quickstart.md
  pkg/ddevapp/magento.go
Labels: bugfix

#5934 docs: standardize capitalization of Docker-ce
  docs/content/users/usage/faq.md
Labels: documentation

#5931 docs: use stable URL for 404 [skip ci]
  mkdocs.yml
Labels: documentation

#5580 fix: add nginx support for webp images in hidden directory, sync nginx conf
  pkg/ddevapp/webserver_config_assets/nginx-site-backdrop.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal6.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal7.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal8.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-magento.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-php.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-wordpress.conf
  pkg/ddevapp/webserver_config_assets/nginx_second_docroot_example-site-php.conf
Labels: bugfix

#5916 feat: invoke dbeaver inside wsl2, fixes #5375
  docs/content/users/usage/commands.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
Labels: enhancement

#5923 fix: don't call app.WriteConfig twice
  cmd/ddev/cmd/config.go
Labels: bugfix

#5804 fix: isMagento2App() should detect version 2.4.5+, update test URLs
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/magento.go
Labels: bugfix

#5684 fix: make the primary URL https if the custom cert exists
  cmd/ddev/cmd/restart.go
  cmd/ddev/cmd/start.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/extra_expose_test.go
  pkg/ddevapp/utils.go
Labels: bugfix

#5944 build: use correct key pattern for blackfire, fixes #5929
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5932 docs: Improve magento2 quickstart and remember composer auth
  docs/content/users/quickstart.md
Labels: documentation

#5938 fix: Adds text/javascript MIME type to gzip_types and mod_deflate.conf, fixes #5937
  containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/mods-available/deflate.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/mime.types
  containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5936 fix: Don't kill supervisord when processes exit, for #5906, fixes #5358
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/apache.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/conf.d/supervisor.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/gunicorn.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/php-fpm.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-fpm.conf
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-gunicorn.conf
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/kill_supervisor.py
  docs/content/users/extend/customization-extendibility.md
  pkg/ddevapp/config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#5892 feat: Add native lima Docker provider support
  .buildkite/macos-lima.yml
  .buildkite/test.sh
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/debug-nfsmount_test.go
  docs/content/users/install/docker-installation.md
  pkg/config/remoteconfig/messages.go
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/mailpit_test.go
  pkg/dockerutil/dockerutils.go
  pkg/testcommon/testcommon_test.go
  pkg/version/version.go
Labels: enhancement

#5952 docs: Improve suggestions about WSL2 docker options
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5948 docs: change recommendation for colima to vz
  docs/content/users/install/docker-installation.md
Labels: documentation

#5950 fix: just delete compose orphans, fixes #5755
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5961 docs: explain how to delete snapshots
  docs/content/users/usage/database-management.md
Labels: documentation

#5956 fix: ddev debug test should check to make sure project is in homedir, for #3679
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/users/usage/troubleshooting.md
Labels: bugfix

#5955 docs: be more explicit about where projects go in home dir
  docs/content/users/install/ddev-installation.md
Labels: documentation

#5957 fix: remove mutually exclusive COMPOSE_IGNORE_ORPHANS variable, for #5950
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5959 fix: remove debug code, fixes #5942
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#5965 docs: Use mysql:8.0 instead of mariadb for ExpressionEngine quickstart
  docs/content/users/quickstart.md
Labels: documentation

#5972 docs: update ddev-drupal9-solr to ddev-drupal-solr
  cmd/ddev/cmd/get.go
  docs/content/users/extend/additional-services.md
  docs/content/users/usage/commands.md
  pkg/archive/archive_test.go
Labels: documentation

#5963 feat: Laravel 11 support, fixes #5962
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/envfile.go
  pkg/ddevapp/laravel.go
Labels: enhancement

#5964 fix: Rewrite ComposeCmd() with just dots goroutine, fixes #5913
  cmd/ddev/cmd/debug-refresh.go
  pkg/dockerutil/dockerutils.go
  pkg/util/utils.go
Labels: bugfix

#5901 fix: Build and run with race detection
  .github/workflows/pr-build.yml
  .github/workflows/tests.yml
  Makefile
  go.mod
  go.sum
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/common.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/wrap.go
  vendor/go.opentelemetry.io/otel/.codespellignore
  vendor/go.opentelemetry.io/otel/CHANGELOG.md
  vendor/go.opentelemetry.io/otel/Makefile
  vendor/go.opentelemetry.io/otel/README.md
  vendor/go.opentelemetry.io/otel/internal/global/meter.go
  vendor/go.opentelemetry.io/otel/internal/global/state.go
  vendor/go.opentelemetry.io/otel/version.go
  vendor/go.opentelemetry.io/otel/versions.yaml
  vendor/modules.txt
Labels: dependencies, bugfix

#5983 test: fix broken if for race-detection and add doc on BUILDARGS
  .github/workflows/tests.yml
  Makefile
  docs/content/developers/building-contributing.md
Labels: maintenance

#5981 docs: add tip about using 0.0.0.0 not localhost
  .spellcheckwordlist.txt
  docs/content/users/extend/customization-extendibility.md
Labels: documentation

#5982 test: disable TestPHPConfig on Lima/Colima
  pkg/ddevapp/config_test.go
  pkg/ddevapp/extra_expose_test.go
Labels: maintenance

#5939 build: bump docker-compose to v2.25.0
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5975 test: Check goroutine count on several tests at completion, fixes #5920
  cmd/ddev/cmd/logs_test.go
  cmd/ddev/cmd/mutagen-cmd_test.go
  cmd/ddev/cmd/snapshot_restore_test.go
  cmd/ddev/cmd/snapshot_test.go
  cmd/ddev/cmd/ssh_test.go
  cmd/ddev/cmd/start_test.go
  cmd/ddev/main.go
  pkg/ddevapp/config.go
  pkg/globalconfig/values.go
  pkg/nodeps/values.go
  pkg/testcommon/testcommon.go
  pkg/util/debug.go
Labels: maintenance

#5986 feat: accept full URLs in `ddev launch`, fixes #5685
  cmd/ddev/cmd/commands_test.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
Labels: enhancement

#5999 fix: make `ddev launch` test work on Windows, for #5986
  cmd/ddev/cmd/commands_test.go
Labels: bugfix

#5989 build: show gitpod testing link in PR comment
  .github/workflows/pr-artifacts-comment.yml
Labels: maintenance

#5994 fix: Revert setting 192.168.5.2 for host.docker.internal on colima, fixes #5537
  docs/content/users/debugging-profiling/step-debugging.md
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#5992 build: turn off verbose output of make build [skip ci]
  Makefile
Labels: maintenance

#5995 build: use new go-based platform.sh CLI, fixes #4668
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6005 docs: Fix "webimage_extra_packages" code example
  docs/content/users/extend/customizing-images.md
Labels: documentation

#6007 test: minor updates to buildkite testbot_maintenance.sh [skip ci]
  .buildkite/testbot_maintenance.sh
Labels: maintenance

#6010 feat: add PR build link to test on Codespaces [skip ci]
  .github/workflows/pr-artifacts-comment.yml
Labels: enhancement

#6001 fix: use natural sort for project+database types, fixes #3561
  go.mod
  go.sum
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/config.go
  pkg/nodeps/values.go
  vendor/github.com/maruel/natural/LICENSE
  vendor/github.com/maruel/natural/README.md
  vendor/github.com/maruel/natural/natsort.go
  vendor/modules.txt
Labels: dependencies, bugfix

#6008 docs: stop recommending colima
  docs/content/users/install/docker-installation.md
  docs/content/users/usage/faq.md
Labels: documentation

#6009 fix: hide obsolete ddev config --http-port
  cmd/ddev/cmd/config.go
Labels: bugfix

#6003 build: use the official script to install Upsun
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#5997 feat: remove segment.io support, fixes #5365
  .github/workflows/master-build.yml
  Makefile
  cmd/ddev/cmd/cmd_version.go
  cmd/ddev/cmd/root.go
  cmd/ddev/cmd/root_test.go
  docs/content/developers/release-management.md
  go.mod
  go.sum
  pkg/ddevapp/instrumentation.go
  pkg/nodeps/instrumentation.go
  pkg/versionconstants/versionconstants.go
  vendor/github.com/segmentio/backo-go/.gitmodules
  vendor/github.com/segmentio/backo-go/LICENSE
  vendor/github.com/segmentio/backo-go/README.md
  vendor/github.com/segmentio/backo-go/backo.go
  vendor/github.com/xtgo/uuid/AUTHORS
  vendor/github.com/xtgo/uuid/LICENSE
  vendor/github.com/xtgo/uuid/uuid.go
  vendor/gopkg.in/segmentio/analytics-go.v3/.gitignore
  vendor/gopkg.in/segmentio/analytics-go.v3/.gitmodules
  vendor/gopkg.in/segmentio/analytics-go.v3/History.md
  vendor/gopkg.in/segmentio/analytics-go.v3/License.md
  vendor/gopkg.in/segmentio/analytics-go.v3/Makefile
  vendor/gopkg.in/segmentio/analytics-go.v3/Readme.md
  vendor/gopkg.in/segmentio/analytics-go.v3/alias.go
  vendor/gopkg.in/segmentio/analytics-go.v3/analytics.go
  vendor/gopkg.in/segmentio/analytics-go.v3/config.go
  vendor/gopkg.in/segmentio/analytics-go.v3/context.go
  vendor/gopkg.in/segmentio/analytics-go.v3/error.go
  vendor/gopkg.in/segmentio/analytics-go.v3/executor.go
  vendor/gopkg.in/segmentio/analytics-go.v3/group.go
  vendor/gopkg.in/segmentio/analytics-go.v3/identify.go
  vendor/gopkg.in/segmentio/analytics-go.v3/integrations.go
  vendor/gopkg.in/segmentio/analytics-go.v3/json.go
  vendor/gopkg.in/segmentio/analytics-go.v3/logger.go
  vendor/gopkg.in/segmentio/analytics-go.v3/message.go
  vendor/gopkg.in/segmentio/analytics-go.v3/page.go
  vendor/gopkg.in/segmentio/analytics-go.v3/properties.go
  vendor/gopkg.in/segmentio/analytics-go.v3/screen.go
  vendor/gopkg.in/segmentio/analytics-go.v3/timeout_15.go
  vendor/gopkg.in/segmentio/analytics-go.v3/timeout_16.go
  vendor/gopkg.in/segmentio/analytics-go.v3/track.go
  vendor/gopkg.in/segmentio/analytics-go.v3/traits.go
  vendor/modules.txt
Labels: dependencies, enhancement

#5976 fix: add restart for database commands after ddev start, fixes #5949
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
  pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
  pkg/ddevapp/global_dotddev_assets/commands/host/mysqlworkbench.example
  pkg/ddevapp/global_dotddev_assets/commands/host/querious
  pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
  pkg/ddevapp/global_dotddev_assets/commands/host/sequelpro
  pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Labels: bugfix

#5888 feat: add cakephp project type, fixes #5713
  .spellcheckwordlist.txt
  cmd/ddev/cmd/commands_test.go
  docs/content/users/quickstart.md
  docs/content/users/usage/architecture.md
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/cakephp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/global_dotddev_assets/commands/web/cake
  pkg/ddevapp/testdata/TestApptypeDetection/cakephp/bin/cake.php
  pkg/nodeps/values.go
Labels: enhancement

#6015 build: bump docker-compose to v2.26.0
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6012 feat: provide corepack_enable config, fixes #5987, replaces #5988
  cmd/ddev/cmd/config.go
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
  docs/content/users/configuration/config.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/nodejs_test.go
  pkg/ddevapp/templates.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6017 fix: make TestCmdDebugTest work on trad Windows
  cmd/ddev/cmd/debug-test_test.go
Labels: bugfix

#6016 docs: update dev docs to run mkdocs locally [skip buildkite]
  Makefile
  docs/content/developers/testing-docs.md
Labels: documentation

#5998 fix: alphabetize global config storage and output, fixes #5046
  pkg/ddevapp/ddevapp.go
  pkg/globalconfig/global_config.go
Labels: bugfix

#5991 feat: Add a `drupal` project type that handles Drupal8-11, fixes #4957
  .github/workflows/tests.yml
  cmd/ddev/cmd/composer-create_test.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/list.go
  containers/ddev-webserver/tests/ddev-webserver/test.sh
  docs/content/users/configuration/config.md
  docs/content/users/extend/custom-commands.md
  docs/content/users/project.md
  docs/content/users/quickstart.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/drupal/drupal/settings.ddev.php
  pkg/ddevapp/drupal/drupal/settings.php
  pkg/ddevapp/drupal/drupal11/settings.ddev.php
  pkg/ddevapp/drupal/drupal11/settings.php
  pkg/ddevapp/global_dotddev_assets/commands/web/drush
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerGit_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/providerLocalfile_test.go
  pkg/ddevapp/providerPantheon_test.go
  pkg/ddevapp/providerPlatform_test.go
  pkg/ddevapp/providerUpsun_test.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/settings_test.go
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestApptypeDetection/drupal/core/lib/Drupal.php
  pkg/ddevapp/testdata/TestApptypeDetection/drupal8/core/lib/Drupal.php
  pkg/ddevapp/testdata/TestApptypeDetection/drupal9/core/lib/Drupal.php
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal.conf
  pkg/fileutil/files.go
  pkg/nodeps/values.go
  pkg/testcommon/testcommon.go
Labels: enhancement

#6027 docs: add privacy plugins to not use external fonts, fixes #4982
  mkdocs.yml
Labels: documentation

#6021 docs: update CakePHP docs to include a link and instructions for 3.x
  docs/content/users/quickstart.md
Labels: documentation

#6022 fix: rsync example should create db.sql.gz [skip ci]
  pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example
Labels: bugfix

#6031 fix: revert removal of Colima host.docker.internal setting
  cmd/ddev/cmd/debug-nfsmount_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#6034 test: make circleci setup noninteractive so doesn't hang [skip buildkite]
  .ci-scripts/linux_arm64_setup.sh
  .circleci/config.yml
Labels: maintenance
