Repository ddev/ddev, pull requests merged in 2024-09, with the labels that each got.

#6520 build: fix FromAsCasing warning from Dockerfile, for #6462 [skip ci]
  .gitpod/images/Dockerfile
  containers/ddev-dbserver/Dockerfile
  containers/ddev-nginx-proxy-router/Dockerfile
  containers/ddev-php-base/Dockerfile
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-webserver/Dockerfile
  containers/test-ssh-server/Dockerfile
Labels: maintenance

#6522 test: leave docker desktop context as desktop-linux [skip ci]
  .buildkite/test.sh
Labels: maintenance

#6517 feat: add `--project` flag to `ddev add-on` commands, fixes #6513
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/addon-list.go
  cmd/ddev/cmd/addon-remove.go
  cmd/ddev/cmd/addon_test.go
  cmd/ddev/cmd/get.go
  docs/content/users/usage/commands.md
Labels: enhancement

#6519 feat: add SVG support for ImageMagick
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/ImageMagick-6/policy.xml
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6516 test: apt key expiration management, fixes #5829 [skip buildkite]
  .ci-scripts/linux_arm64_setup.sh
  .github/workflows/linux-setup.sh
  containers/ddev-dbserver/test/functions.sh
  containers/ddev-dbserver/test/image_general.bats
  containers/ddev-dbserver/test/test_dbserver.sh
  containers/ddev-ssh-agent/Dockerfile
  containers/ddev-ssh-agent/test/functions.sh
  containers/ddev-ssh-agent/test/image_general.bats
  containers/ddev-ssh-agent/test/test.sh
  containers/ddev-webserver/tests/ddev-webserver/general.bats
  containers/ddev-webserver/tests/ddev-webserver/test.sh
  containers/testscripts/check_key_expirations.sh
Labels: maintenance

#6510 fix: don't touch `.ddev` dir in every `ddev` command, avoid overwriting `.ddev/.gitignore` if unchanged, fixes php-perfect/ddev-intellij-plugin#361
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/root.go
  pkg/ddevapp/assets.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/utils.go
  pkg/dockerutil/dockerutils.go
Labels: bugfix

#6526 test: Fix TestLagoonPush by upgrading lagoon CLI, replaces #6524
  pkg/ddevapp/providerLagoon_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6527 docs: maintainer info about GitHub notifications
  docs/content/developers/maintainers.md
  markdown-link-check.json
Labels: documentation

#6536 test: Use 1password for test secrets [skip buildkite]
  .github/workflows/tests.yml
  cmd/ddev/cmd/auth-ssh.go
  docs/content/developers/secret-management.md
  markdown-link-check.json
  mkdocs.yml
  pkg/ddevapp/providerAcquia_test.go
  pkg/ddevapp/providerLagoon_test.go
  pkg/ddevapp/providerPantheon_test.go
  scripts/read-1password-secrets.sh
Labels: maintenance

#6537 fix: Remove obsolete code that fixed up absolute mountpoints
  pkg/ddevapp/compose_yaml.go
Labels: bugfix

#6540 test: Make forked PRs skip loading secrets
  .github/workflows/tests.yml
Labels: maintenance

#6538 build: bump docker-compose to 2.29.3
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6545 build: Revert "build: bump docker-compose to 2.29.3 (#6538)"
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6547 docs: fix link to ngrok agent config
  docs/content/users/configuration/config.md
Labels: documentation

#6548 build: bump docker-compose to 2.29.5
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6541 build: Use 1password secrets for most push secrets instead of github secrets
  .github/workflows/master-build.yml
  .github/workflows/push-tagged-dbimage.yml
  .github/workflows/push-tagged-image.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  Makefile
  docs/content/developers/release-management.md
Labels: maintenance

#6501 fix: allow overrides for Docker networks, fixes #5706, fixes #6376
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.networks.yaml
Labels: bugfix

#6551 docs: add Magento tools to docs
  .spellcheckwordlist.txt
  docs/content/users/usage/developer-tools.md
Labels: documentation

#6552 fix: ddev debug test - show customizations in .ddev/nginx if they exist [skip ci]
  cmd/ddev/cmd/scripts/test_ddev.sh
Labels: bugfix

#6525 feat: streamline TYPO3 non-composer mode configuration support
  pkg/ddevapp/typo3.go
Labels: enhancement

#6558 test: Remove brew setup for linux from buildkite testbot_maintenance.sh [skip ci]
  .buildkite/testbot_maintenance.sh
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/users/install/ddev-installation.md
Labels: maintenance

#6560 docs: Typo fix, incorrect code section usage
  docs/content/users/configuration/config.md
Labels: documentation

#6561 test: buildkite testbot_maintenance.sh apt upgrade hung on linux, remove it
  .buildkite/testbot_maintenance.sh
Labels: maintenance

#6562 build: change to new gitpod image with current ddev, make codespaces work [skip ci]
  .gitpod.yml
  docs/content/users/install/ddev-installation.md
Labels: maintenance

#6565 feat: Don't force Drush's Xdebug environment variable to 1
  pkg/ddevapp/app_compose_template.yaml
Labels: enhancement
