Repository ddev/ddev, pull requests merged in 2025-07, with the labels that each got.

#7427 docs: add blog and add-on registry to navigation
  mkdocs.yml
Labels: documentation

#7425 build: Use new cooldown to slow dependabot updates [skip ci]
  .github/dependabot.yml
Labels: maintenance

#7419 feat: add `NO_COLOR` variable support, fixes #7058
  cmd/ddev/cmd/config-global.go
  docs/content/users/configuration/config.md
  docs/content/users/extend/in-container-configuration.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp_test.go
  pkg/globalconfig/global_config.go
  pkg/output/output_setup.go
  pkg/util/utils.go
Labels: enhancement

#7433 fix: use `output.UserOut` for JSON output, retry on invalid input in interactive `ddev config`, for #7403
  cmd/ddev/cmd/aliases.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/dotenv-get.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/snapshot.go
  pkg/util/utils.go
Labels: bugfix

#7431 feat: add JSON output to `ddev -v`
  cmd/ddev/cmd/root.go
Labels: enhancement

#7353 docs: add Terminus downgrade tips, fixes #7352
  docs/content/users/providers/pantheon.md
  docs/content/users/usage/developer-tools.md
Labels: documentation

#7385 feat: return real exit code from `ddev exec` and add quiet flag to it, fixes #3518
  cmd/ddev/cmd/exec.go
  docs/content/users/usage/commands.md
Labels: enhancement

#7443 fix: Include ddev-hostname in main build zipballs, fixes #7420
  .github/workflows/main-build.yml
  .github/workflows/pr-build.yml
Labels: bugfix

#7404 feat: Windows Native and WSL2 GUI installer
  .gitignore
  .goreleaser.yml
  Makefile
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  docs/content/users/install/docker-installation.md
  winpkg/ddev.nsi
  winpkg/ddev_lib_test.nsi
  winpkg/ddev_windows_installer.nsi
  winpkg/graphics/ddev-header.bmp
  winpkg/graphics/ddev-install.ico
  winpkg/graphics/ddev-uninstall.ico
  winpkg/graphics/ddev-wizard.bmp
  winpkg/installer_test.go
  winpkg/scripts/check_root_user.sh
  winpkg/scripts/install_temp_sudoers.sh
  winpkg/scripts/mkcert_install.sh
Labels: enhancement

#7445 build: bump github.com/spf13/cobra to latest commit, fixes #7361
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/SECURITY.md
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/modules.txt
Labels: dependencies, maintenance

#7448 fix: avoid mutating input slice in `cmd.prettyCmd()`
  cmd/ddev/cmd/utils.go
Labels: bugfix

#7452 fix: Improve Windows installer behavior (actually exit on errors)
  docs/content/users/install/ddev-installation.md
  winpkg/ddev_windows_installer.nsi
Labels: bugfix

#7451 fix: show errors for custom commands when flags are parsed, fixes #7409
  cmd/ddev/cmd/commands.go
Labels: bugfix

#7449 build: Add a ddev-wsl2 package especially for ddev-hostname.exe, fixes #7428
  .github/workflows/main-build.yml
  .github/workflows/pr-build.yml
  .goreleaser.yml
  Makefile
  docs/content/developers/release-management.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/usage/commands.md
  scripts/ddev-linux-package-postinstall.sh
  scripts/ddev-wsl2-postinstall.sh
  winpkg/ddev_windows_installer.nsi
  winpkg/installer_test.go
Labels: maintenance

#7458 fix: temporarily allow write to `/etc/mysql/conf.d/*` for `db` container restart, fixes #7457
  containers/ddev-dbserver/files/docker-entrypoint.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7456 build: bump images to v1.24.7 for release, docker-compose v2.38.2 (`COMPOSE_BAKE=false`), fixes #7383
  cmd/ddev/cmd/delete_test.go
  containers/ddev-dbserver/README.md
  containers/ddev-php-base/README.md
  containers/ddev-ssh-agent/README.md
  containers/ddev-traefik-router/README.md
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/README.md
  containers/test-ssh-server/README.md
  pkg/ddevapp/ddevapp.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7463 docs: add `.wslconfig` example for mirrored networking mode in WSL2
  docs/content/index.md
Labels: documentation

#7465 docs: minor update to manual ddev instructions and use apt-get
  docs/content/developers/network-test-environments.md
  docs/content/developers/testing-docs.md
  docs/content/users/install/ddev-installation.md
Labels: documentation

#7479 test: add a no-interaction flag to the install command in ibexa bats file
  docs/tests/ibexa.bats
Labels: maintenance

#7478 docs: note about `Flags` annotation with unknown flags, for #7451
  docs/content/users/extend/custom-commands.md
Labels: documentation
