Repository ddev/ddev, pull requests merged in 2025-04, with the labels that each got.

#7184 docs: Add missing `sequelace` command link to `database-management.md`
  docs/content/users/usage/database-management.md
Labels: documentation

#7183 docs: add tip on using per-project API tokens for hosting providers, fixes #7177
  docs/content/users/providers/acquia.md
  docs/content/users/providers/pantheon.md
  docs/content/users/providers/platform.md
  docs/content/users/providers/upsun.md
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
  pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
  pkg/ddevapp/dotddev_assets/providers/upsun.yaml
Labels: documentation

#7186 fix: ignore curl error in `Dockerfile.test` for `ddev debug test`
  cmd/ddev/cmd/scripts/test_ddev.sh
Labels: bugfix

#7148 fix: don't wait for one-off containers from PhpStorm, fixes #7146
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/router.go
  pkg/ddevapp/ssh_auth.go
  pkg/ddevapp/utils.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
Labels: bugfix

#7166 fix: add timeout for netutil::IsPortActive check for WSL2 with "mirrored networking mode" as opposed to default "NAT mode", fixes #6245
  pkg/netutil/netutil.go
Labels: bugfix

#7050 fix: nginx.conf should let index.php handle 404 errors for media files
  pkg/ddevapp/webserver_config_assets/nginx-site-backdrop.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-cakephp.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal11.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal6.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal7.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal8.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-magento.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-silverstripe.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-symfony.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
  pkg/ddevapp/webserver_config_assets/nginx-site-wordpress.conf
  pkg/ddevapp/webserver_config_assets/nginx_second_docroot_example-site-php.conf
Labels: bugfix

#7061 docs: Explain corp vpn and proxy, fixup FAQ, fixes #7048
  .spellcheckwordlist.txt
  docs/content/developers/network-test-environments.md
  docs/content/users/usage/faq.md
  docs/content/users/usage/networking.md
  mkdocs.yml
Labels: documentation

#7049 build: stop installing chocolatey, fixes #6636, fixes #6344 [skip buildkite]
  .github/RELEASE_NOTES_TEMPLATE.md
  Makefile
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  docs/content/users/install/docker-installation.md
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
  winpkg/ddev.nsi
Labels: maintenance

#7182 fix: XHGui launch command support custom ports, fixes #7181
  cmd/ddev/cmd/xhgui_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/xhprof_xhgui.go
Labels: bugfix

#7192 test: fix for magento2 quickstart and bats test, fixes #7191
  docs/content/users/quickstart.md
  docs/tests/magento2.bats
Labels: maintenance

#7197 docs: fix minor typo in the Grav quickstart
  docs/content/users/quickstart.md
Labels: documentation

#7062 fix: make `ddev config` work with project name from `config.*.yaml`, fixes #7060
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/templates.go
Labels: bugfix

#7200 docs: Improve buildkite windows setup script run [skip buildkite]
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#7077 fix: make sure mutagen agents file is fresh on upgrade, add shasum testing, test shasum for mutagen+docker-compose
  cmd/ddev/cmd/addon-get.go
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/ddevapp/mutagen.go
  pkg/dockerutil/docker_compose_version_test.go
  pkg/dockerutil/dockerutils.go
  pkg/fileutil/files.go
  pkg/fileutil/files_test.go
  pkg/testcommon/testcommon.go
  pkg/util/network.go
  pkg/util/network_test.go
Labels: bugfix

#7203 test: make the drupal cms bats test a bit more robust and trustworthy
  docs/tests/drupal.bats
Labels: maintenance

#7199 feat: add DDEV_APPROOT variable to web container and updates documentation, fixes #7198
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/app_compose_template.yaml
Labels: enhancement

#7207 build: switch to official percona release for xtrabackup, fixes #6963
  containers/ddev-dbserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7216 fix: disable xdebug trigger for xdebug and xhprof status checks, fixes #6191, fixes php-perfect/ddev-intellij-plugin#414
  pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
  pkg/ddevapp/xhprof_xhgui.go
Labels: bugfix

#7219 fix: Use fast checkpoint during postgresql backup, fixes #7098
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#7218 feat: add new envs `DDEV_PRIMARY_URL_PORT`, `DDEV_PRIMARY_URL_WITHOUT_PORT` and `DDEV_SCHEME`, fixes #7214
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/nodeps/utils.go
  pkg/nodeps/utils_test.go
Labels: enhancement

#7071 feat: support prepend.Dockerfile* files for multi-stage builds
  docs/content/users/extend/customizing-images.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/dotddev_assets/db-build/README.txt
  pkg/ddevapp/dotddev_assets/web-build/README.txt
Labels: enhancement

#7212 docs: Improvements to Zscaler instructions, fixes #7209, fixes #7211 [skip buildkite]
  docs/content/users/usage/networking.md
Labels: documentation

#7224 test: Add TestUploadDirs to verify upload_dirs, fixes #7109
  pkg/ddevapp/ddevapp_test.go
Labels: maintenance

#7228 refactor: check for docroot/index.* on start, fixes #7157
  pkg/ddevapp/ddevapp.go
  pkg/util/utils.go
Labels: maintenance

#7231 docs: use ddev composer create-project everywhere, fixes #6920
  cmd/ddev/cmd/composer-create-project.go
  docs/content/users/quickstart.md
  docs/tests/cakephp.bats
  docs/tests/contao.bats
  docs/tests/craftcms.bats
  docs/tests/drupal.bats
  docs/tests/frankenphp.bats
  docs/tests/grav.bats
  docs/tests/ibexa.bats
  docs/tests/kirby.bats
  docs/tests/laravel.bats
  docs/tests/magento2.bats
  docs/tests/moodle.bats
  docs/tests/pimcore.bats
  docs/tests/processwire.bats
  docs/tests/shopware.bats
  docs/tests/silverstripe.bats
  docs/tests/statamic.bats
  docs/tests/sulu.bats
  docs/tests/symfony.bats
  docs/tests/typo3.bats
  docs/tests/wordpress.bats
Labels: documentation

#7234 refactor: Add retries to util.Download(), both the SHASUM and the target file
  go.mod
  go.sum
  pkg/util/network.go
  vendor/github.com/hashicorp/go-cleanhttp/LICENSE
  vendor/github.com/hashicorp/go-cleanhttp/README.md
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/doc.go
  vendor/github.com/hashicorp/go-cleanhttp/handlers.go
  vendor/github.com/hashicorp/go-retryablehttp/.gitignore
  vendor/github.com/hashicorp/go-retryablehttp/.go-version
  vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: dependencies, maintenance

#7226 test: add timeout to buildkite maintenance, fixes #7176
  .buildkite/test.sh
  .buildkite/testbot_maintenance.sh
Labels: maintenance

#7237 docs: wrap quotes around commands that use the caret symbol
  docs/content/users/quickstart.md
  docs/tests/drupal.bats
  docs/tests/shopware.bats
Labels: documentation
