Repository ddev/ddev, pull requests merged in 2025-08, with the labels that each got.

#7480 docs: explain how to make `build` stage in `docker-compose.*.yaml` work offline
  docs/content/users/extend/custom-compose-files.md
Labels: documentation

#7483 feat: parallel `docker-compose pull`, improve `ddev debug download-images`, fixes #7163
  cmd/ddev/cmd/debug-download-images.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp.go
  pkg/dockerutil/composeutils.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/util/yamltools.go
Labels: enhancement

#7501 test: ngrok broke their installation moving to bookworm, fix it
  .github/workflows/linux-setup.sh
  docs/content/developers/scripts/wsl2-test-runner-setup.sh
Labels: maintenance

#7500 build: use ddev/ddev-utilities instead of busybox, fixes #7499
  .buildkite/sanetestbot.sh
  .github/workflows/nfstest.sh
  .github/workflows/sanetestbot.sh
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/developers/scripts/windows_buildkite_setup.sh
  docs/content/developers/scripts/windows_github_agent_setup.sh
  docs/content/users/install/docker-installation.md
  pkg/ddevapp/db.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/poweroff.go
  pkg/dockerutil/dockerutils_test.go
  pkg/fileutil/file_hash_test.go
  pkg/globalconfig/global_config_test.go
  pkg/versionconstants/versionconstants.go
  scripts/debian_ubuntu_linux_ddev_nfs_setup.sh
  scripts/macos_ddev_nfs_setup.sh
  scripts/windows_ddev_nfs_setup.sh
Labels: dependencies, maintenance

#7474 fix: Update obsolete WSL2 install scripts to reflect new ddev-wsl2 and not needing ddev.exe, fixes #7464 [skip ci]
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
Labels: bugfix

#7513 ci: enforce conventional commits format for PR titles [skip buildkite]
  .github/pr-labeler.yml
  .github/workflows/pr-check.yml
  docs/content/developers/building-contributing.md
Labels: maintenance

#7476 docs(wsl): add `wsl --update` command for Windows
  docs/content/users/install/ddev-installation.md
Labels: documentation

#7515 ci(pr-check): loosen start and middle rules for message [skip ci], for #7513
  .github/workflows/pr-check.yml
Labels: maintenance

#7502 feat(sponsorship): add ability to download sponsorship data and other generic data, for #6892
  .spellcheckwordlist.txt
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/debug-gob-decode.go
  cmd/ddev/cmd/debug-gob-decode_test.go
  cmd/ddev/cmd/debug-remote-data.go
  cmd/ddev/cmd/debug-remote-data_test.go
  cmd/ddev/cmd/debug.go
  cmd/ddev/cmd/start.go
  cmd/ddev/cmd/start_test.go
  cmd/ddev/cmd/testdata/TestDebugGobDecode/create_test_files.go
  cmd/ddev/cmd/testdata/TestDebugGobDecode/test-amplitude-cache.gob
  cmd/ddev/cmd/testdata/TestDebugGobDecode/test-generic.gob
  cmd/ddev/cmd/testdata/TestDebugGobDecode/test-remote-config.gob
  cmd/ddev/cmd/testdata/TestDebugGobDecode/test-sponsorship-data.gob
  docs/content/developers/remote-config.md
  docs/content/users/usage/commands.md
  pkg/config/remoteconfig/config.go
  pkg/config/remoteconfig/downloader/jsonc_downloader.go
  pkg/config/remoteconfig/global.go
  pkg/config/remoteconfig/internal/messages.go
  pkg/config/remoteconfig/internal/remote_config.go
  pkg/config/remoteconfig/messages.go
  pkg/config/remoteconfig/remote_config.go
  pkg/config/remoteconfig/remoteconfig_test.go
  pkg/config/remoteconfig/sponsorship.go
  pkg/config/remoteconfig/state.go
  pkg/config/remoteconfig/storage/file_storage.go
  pkg/config/remoteconfig/storage/github_storage.go
  pkg/config/remoteconfig/storage/sponsorship_storage.go
  pkg/config/remoteconfig/types/remote_config.go
  pkg/config/remoteconfig/types/remote_config_storage.go
  pkg/config/remoteconfig/types/sponsorship.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/remote_config.go
  pkg/globalconfig/schema.json
Labels: enhancement

#7517 chore: revert 3 github copilot commits that it (I) shouldn't have done [skip ci]
  comments
  pulls/7511/comments.md
  pulls/7511/reviews/1
Labels: maintenance

#7512 fix(ddev-hostname): sudo can't find ddev-hostname in linuxbrew, fixes #7510
  docs/content/developers/buildkite-testmachine-setup.md
  pkg/ddevapp/hostname_mgt.go
  pkg/hostname/hostname.go
Labels: bugfix

#7507 fix(traefik): improve router port discovery and optimize YAML writes, fixes ddev/ddev-mongo#24
  cmd/ddev/cmd/root_test.go
  cmd/ddev/cmd/start_test.go
  cmd/ddev/cmd/testdata/TestCmdStartOptionalProfiles/docker-compose.busybox.yaml
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_test.go
  pkg/fileutil/embed.go
Labels: bugfix

#7520 build(direnv): Make direnv .envrc idempotent so it doesn't do all that work all the time
  .envrc
  docs/content/developers/testing-docs.md
Labels: maintenance

#7525 build(mariadb): turn off innodb_use_native_aio for mariadb:10.6
  containers/ddev-dbserver/files/etc/mysql/version-conf.d/mariadb_10.6.cnf.txt
  containers/ddev-dbserver/test/testdata/database_config/mariadb_10.6.ini
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7528 fix(testddevexportdb): postgres:14 output dump statement was suddenly more than 80 characters from end
  pkg/ddevapp/ddevapp_test.go
Labels: bugfix

#7511 feat: replace `docker run` in `ddev auth ssh` with Docker API and accept stdin
  cmd/ddev/cmd/auth-ssh.go
  cmd/ddev/cmd/auth-ssh_test.go
  pkg/ddevapp/mutagen.go
  pkg/dockerutil/dockerutils.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
Labels: enhancement

#7540 docs: fiddle with sponsorship title [skip ci]
  pkg/config/remoteconfig/messages.go
Labels: documentation

#7543 fix: add mutagen sync flush after XHProf enable to prevent intermittent test failures
  pkg/ddevapp/xhprof_xhgui.go
Labels: bugfix

#7545 chore(deps): bump docker-compose to v2.39.2, remove `COMPOSE_BAKE=false`
  go.mod
  go.sum
  pkg/ddevapp/ddevapp.go
  pkg/versionconstants/versionconstants.go
  vendor/github.com/compose-spec/compose-go/v2/dotenv/env.go
  vendor/github.com/compose-spec/compose-go/v2/loader/loader.go
  vendor/github.com/compose-spec/compose-go/v2/loader/reset.go
  vendor/github.com/compose-spec/compose-go/v2/loader/validate.go
  vendor/github.com/compose-spec/compose-go/v2/schema/compose-spec.json
  vendor/github.com/compose-spec/compose-go/v2/template/variables.go
  vendor/github.com/compose-spec/compose-go/v2/transform/canonical.go
  vendor/github.com/compose-spec/compose-go/v2/transform/defaults.go
  vendor/github.com/compose-spec/compose-go/v2/types/command.go
  vendor/github.com/compose-spec/compose-go/v2/types/derived.gen.go
  vendor/github.com/compose-spec/compose-go/v2/types/mapping.go
  vendor/github.com/compose-spec/compose-go/v2/types/project.go
  vendor/github.com/compose-spec/compose-go/v2/types/types.go
  vendor/modules.txt
Labels: dependencies, maintenance

#7566 docs: Fix blog link in main nav
  mkdocs.yml
Labels: documentation

#7567 fix(magerun): use stable branch for autocompletion
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7571 test(buildkite): Minor fixup for buildkite timeout
  .buildkite/test.sh
  .buildkite/testbot_maintenance.sh
Labels: maintenance
