Repository ddev/ddev, pull requests merged in 2025-09, with the labels that each got.

#7569 chore(mkdocs): disable privacy plugin for local builds, for #6027 [skip ci]
  mkdocs.yml
Labels: maintenance

#7560 fix: add missing ephemeral port handling to xhgui service, fixes #7557
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/xhprof_xhgui.go
Labels: bugfix

#7542 fix: report MariaDB/MySQL/PostgreSQL client install failures and refactor timeout logic
  containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
  containers/ddev-php-base/generic-files/usr/local/bin/install_php_extensions.sh
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/log-stderr.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/n-install.sh
  containers/ddev-webserver/ddev-webserver-dev-base-files/etc/sudoers.d/ddev
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/router.go
  pkg/dockerutil/dockerutils.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7581 docs(provider): soften language about use of provider push
  cmd/ddev/cmd/push.go
  docs/content/users/providers/index.md
  pkg/ddevapp/dotddev_assets/providers/README.txt
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
  pkg/ddevapp/dotddev_assets/providers/lagoon.yaml
  pkg/ddevapp/dotddev_assets/providers/pantheon.yaml
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
  pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example
  pkg/ddevapp/dotddev_assets/providers/upsun.yaml
Labels: documentation

#7574 fix: cache `WarningOnce`, reduce `NewApp` calls, handle `GetDockerClient` errors, for #7472
  cmd/ddev/cmd/debug-dockercheck.go
  cmd/ddev/cmd/delete-images.go
  cmd/ddev/cmd/networks_test.go
  cmd/ddev/cmd/pull.go
  cmd/ddev/cmd/push.go
  cmd/ddev/cmd/snapshot_restore.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/mutagen.go
  pkg/ddevapp/router.go
  pkg/ddevapp/utils.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/util/capture.go
  pkg/util/utils.go
  pkg/util/utils_test.go
  pkg/version/version.go
Labels: bugfix

#7588 build: gitignore/CLAUDE.md nitpicks [skip ci]
  .gitignore
  CLAUDE.md
Labels: maintenance

#7596 test(buildkite): buildkite can take a few minutes to pull new images [skip ci]
  .buildkite/test.sh
Labels: maintenance

#7572 feat: provide `host.docker.internal` for all services, fixes #7537
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp_test.go
  pkg/dockerutil/host_docker_internal.go
  pkg/dockerutil/nfs.go
Labels: enhancement

#7606 test(xhgui): add more retries for GetLocalHTTPResponse, for #7543
  cmd/ddev/cmd/xhgui_test.go
  pkg/ddevapp/mailpit_test.go
  pkg/ddevapp/router_test.go
  pkg/ddevapp/xhprof_xhgui_test.go
  pkg/testcommon/testcommon.go
Labels: maintenance

#7586 feat(add-ons): add-on dependencies should be automatically downloaded, fixes #5337
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/cmd_version_test.go
  cmd/ddev/cmd/debug-match-constraint_test.go
  cmd/ddev/cmd/testdata/TestAddonCircular/addon_x/install.yaml
  cmd/ddev/cmd/testdata/TestAddonCircular/addon_x/x-config.yaml
  cmd/ddev/cmd/testdata/TestAddonCircular/addon_y/install.yaml
  cmd/ddev/cmd/testdata/TestAddonCircular/addon_y/y-config.yaml
  cmd/ddev/cmd/testdata/TestAddonCircular/addon_z/install.yaml
  cmd/ddev/cmd/testdata/TestAddonCircular/addon_z/z-config.yaml
  cmd/ddev/cmd/testdata/TestAddonGetPostInstallRuntimeDependencies/mock_redis/docker-compose.redis.yaml
  cmd/ddev/cmd/testdata/TestAddonGetPostInstallRuntimeDependencies/mock_redis/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetPostInstallRuntimeDependencies/mock_redis_commander/docker-compose.redis-commander.yaml
  cmd/ddev/cmd/testdata/TestAddonGetPostInstallRuntimeDependencies/mock_redis_commander/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetPostInstallRuntimeDependencies/post_install_runtime_deps_addon/config.post-install-runtime-deps-addon.yaml
  cmd/ddev/cmd/testdata/TestAddonGetPostInstallRuntimeDependencies/post_install_runtime_deps_addon/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetRuntimeDependencies/php_runtime_deps_addon/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetRuntimeDependencies/php_runtime_deps_addon/php-config.yaml
  cmd/ddev/cmd/testdata/TestAddonGetRuntimeDependencies/post_install_runtime_deps_addon/config.post-install-runtime-deps-addon.yaml
  cmd/ddev/cmd/testdata/TestAddonGetRuntimeDependencies/post_install_runtime_deps_addon/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetRuntimeDependencies/runtime_deps_addon/config.runtime-deps-addon.yaml
  cmd/ddev/cmd/testdata/TestAddonGetRuntimeDependencies/runtime_deps_addon/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetSkipDepsFlag/mock_redis/docker-compose.redis.yaml
  cmd/ddev/cmd/testdata/TestAddonGetSkipDepsFlag/mock_redis/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetSkipDepsFlag/mock_redis_commander/docker-compose.redis-commander.yaml
  cmd/ddev/cmd/testdata/TestAddonGetSkipDepsFlag/mock_redis_commander/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetWithDependencies/mock_redis/docker-compose.redis.yaml
  cmd/ddev/cmd/testdata/TestAddonGetWithDependencies/mock_redis/install.yaml
  cmd/ddev/cmd/testdata/TestAddonGetWithDependencies/mock_redis_commander/docker-compose.redis-commander.yaml
  cmd/ddev/cmd/testdata/TestAddonGetWithDependencies/mock_redis_commander/install.yaml
  cmd/ddev/cmd/testdata/TestAddonWithExtractedDir/extracted_dir_addon/additional-script.sh
  cmd/ddev/cmd/testdata/TestAddonWithExtractedDir/extracted_dir_addon/install.yaml
  cmd/ddev/cmd/testdata/TestAddonWithExtractedDir/extracted_dir_addon/main-config.yaml
  cmd/ddev/cmd/testdata/TestAddonWithExtractedDir/extracted_dir_addon/runtime-config.json
  cmd/ddev/cmd/testdata/TestCmdAddonDdevVersionConstraint/valid_constraint_recipe/install.yaml
  docs/content/users/extend/creating-add-ons.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/addons.go
  pkg/ddevapp/addons_test.go
  pkg/ddevapp/testdata/TestRecursiveDependencies/AddonA/install.yaml
  pkg/ddevapp/testdata/TestRecursiveDependencies/AddonB/install.yaml
  pkg/ddevapp/testdata/TestRecursiveDependencies/AddonC/install.yaml
  pkg/ddevapp/testdata/TestRecursiveDependencies/AddonD/install.yaml
  pkg/github/github.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#7618 docs: fix typo in documentation
  docs/content/users/extend/additional-hostnames.md
Labels: documentation

#7617 fix(ddev-php-base): Remove php8.4-obsolete config, fixes #7616
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/apache2/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/cli/php.ini
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/fpm/php.ini
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7621 docs: remove Prerequisite section
  docs/content/users/install/phpstorm.md
Labels: documentation

#7599 feat: add `ddev npx` command
  cmd/ddev/cmd/commands_test.go
  docs/content/users/usage/cli.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/npx
Labels: enhancement

#7634 chore: update `schema.json`, `global_config.yaml`, `config.yaml` templates
  .github/workflows/tests.yml
  docs/content/users/configuration/config.md
  docs/content/users/extend/creating-add-ons.md
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
  pkg/ddevapp/xhprof_xhgui_test.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/schema.json
Labels: maintenance

#7637 build(aur): add docker-buildx dependency
  .goreleaser.yml
Labels: maintenance

#7658 test: fix TestNetworkAliases, fixes #7657
  pkg/dockerutil/networks_test.go
Labels: maintenance

#7651 feat: enhance PHP addon environment with DockerEnv() integration
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/addon-remove.go
  cmd/ddev/cmd/auth-ssh_test.go
  cmd/ddev/cmd/commands.go
  cmd/ddev/cmd/debug-compose-config.go
  cmd/ddev/cmd/debug-download-images.go
  cmd/ddev/cmd/debug-rebuild.go
  cmd/ddev/cmd/exec.go
  cmd/ddev/cmd/ssh.go
  cmd/ddev/cmd/xhgui.go
  pkg/ddevapp/addons.go
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/ssh_auth.go
Labels: enhancement

#7659 feat: Update AGENTS.md to reference organization-wide patterns
  AGENTS.md
Labels: enhancement

#7653 fix(cakephp): do not override APP_DEFAULT_LOCALE
  pkg/ddevapp/cakephp.go
Labels: bugfix

#7663 fix(hack-postgres): hack postgres client since postgresql-client:18 is misbehaving, for #7661
  pkg/ddevapp/config.go
Labels: bugfix

#7665 fix(postgres): uninstall postgresql-client with its dependencies, for #7663
  pkg/ddevapp/config.go
Labels: bugfix
