Repository ddev/ddev, pull requests merged in 2025-02, with the labels that each got.

#6954 build: run golangci-lint only for changed code in PRs
  .github/workflows/golangci-lint.yml
Labels: maintenance

#6953 build: run linkspector on the main branch, for #6860
  .github/workflows/docscheck.yml
Labels: maintenance

#6952 build: hide extra output from linkspector [skip ci]
  Makefile
Labels: maintenance

#6888 docs: Add info on maintaining and testing quickstarts, fixes #6880
  .github/workflows/quickstart.yml
  docs/content/developers/quickstart-maintenance.md
  mkdocs.yml
Labels: documentation

#6939 fix: trim single quotes, double quotes, and spaces from filepath input, fixes #6938
  cmd/ddev/cmd/import-files.go
  pkg/ddevapp/ddevapp.go
  pkg/util/prompt.go
  pkg/util/utils_test.go
Labels: bugfix

#6960 fix: improve error message for invalid env flag, fixes #6949
  cmd/ddev/cmd/dotenv_test.go
  cmd/ddev/cmd/utils.go
Labels: bugfix

#6956 fix: check snapshot name for valid characters, fixes #6955
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/snapshot_test.go
Labels: bugfix

#6935 feat: Add "generic" webserver type for Node.js and other things like FrankenPHP, fixes #4854, fixes #5655, fixes #4312
  .github/workflows/quickstart.yml
  .spellcheckwordlist.txt
  .vscode/launch.json
  .vscode/settings.json
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/describe.go
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-generic.conf
  containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/healthcheck.sh
  docs/content/users/configuration/config.md
  docs/content/users/extend/custom-commands.md
  docs/content/users/extend/customization-extendibility.md
  docs/content/users/quickstart.md
  docs/content/users/usage/commands.md
  docs/tests/frankenphp.bats
  docs/tests/nodejs.bats
  docs/tests/sveltekit.bats
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/ports.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_test.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
  pkg/ddevapp/typo3.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/netutil/netutil.go
  pkg/nodeps/values.go
  pkg/testcommon/testcommon.go
  pkg/testcommon/testcommon_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6965 test: allow a margin of +2 for ephemeral port checks due to flakiness
  pkg/ddevapp/router_test.go
Labels: maintenance

#6959 fix: add patch command to hardened prod web image, fixes #6958
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6950 feat: bind IP to user-defined ports if not set, fixes #6943
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.ports.yaml
Labels: enhancement

#6967 feat: switch apache mpm_prefork to mpm_event, fixes #6966
  containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
  containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6969 build: remove custom Xdebug 3.4.1
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6968 build: autoload Python and Node deps from Makefile with direnv [skip ci]
  .envrc
  Makefile
Labels: maintenance

#6971 docs: add MySQL 8.4 to supported databases
  docs/content/users/extend/database-types.md
Labels: documentation

#6964 feat: change php-fpm setting 'decorate_workers_output' to 'no'
  containers/ddev-php-base/ddev-php-files/etc/php/7.3/fpm/pool.d/www.conf
  containers/ddev-php-base/ddev-php-files/etc/php/7.4/fpm/pool.d/www.conf
  containers/ddev-php-base/ddev-php-files/etc/php/8.0/fpm/pool.d/www.conf
  containers/ddev-php-base/ddev-php-files/etc/php/8.1/fpm/pool.d/www.conf
  containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/pool.d/www.conf
  containers/ddev-php-base/ddev-php-files/etc/php/8.3/fpm/pool.d/www.conf
  containers/ddev-php-base/ddev-php-files/etc/php/8.4/fpm/pool.d/www.conf
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/tests/ddev-webserver/general.bats
  containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
  containers/ddev-webserver/tests/ddev-webserver/project_type.bats
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#6962 feat: normalize docroot usage in `ddev config`
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  docs/content/developers/quickstart-maintenance.md
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/util/utils.go
Labels: enhancement

#6976 build: remove Xdebug 3.2.2 builds for php8.1 and php8.2
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6981 fix: correct spelling for Xdebug
  .vscode/launch.json
  cmd/ddev/cmd/config.go
  docs/content/users/extend/customizing-images.md
  pkg/ddevapp/ddevapp_test.go
Labels: bugfix

#6980 fix: do not show router URL in `ddev list` if it's stopped
  pkg/ddevapp/list.go
  pkg/ddevapp/router.go
  pkg/globalconfig/global_config.go
Labels: bugfix

#6984 docs: Fix niggling code sample inconsistency in `troubleshooting.md`
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#6985 build: go back to normal blackfire packaging, fixes #6078
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/etc/apt/preferences.d/.gitmanaged
  containers/ddev-webserver/ddev-webserver-base-files/etc/apt/preferences.d/blackfire
  docs/content/users/debugging-profiling/blackfire-profiling.md
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6989 docs: add link for DDEV Add-on Registry, fixes #6383
  docs/content/users/extend/additional-services.md
Labels: documentation

#6996 test: add yes flag to ddev start cmd
  docs/tests/backdrop.bats
  docs/tests/drupal.bats
  docs/tests/processwire.bats
  docs/tests/typo3.bats
  docs/tests/wordpress.bats
Labels: maintenance

#6988 test: grav quickstart bats tests
  docs/tests/grav.bats
Labels: maintenance

#6990 test: quickstart bats test for ibexa
  docs/tests/ibexa.bats
Labels: maintenance

#6991 test: quickstart bats test for moodle
  docs/tests/moodle.bats
Labels: maintenance

#6992 test: bats test for pimcore quickstart
  docs/tests/pimcore.bats
Labels: maintenance

#6993 test: shopware quickstart bats test
  docs/content/users/quickstart.md
  docs/tests/shopware.bats
Labels: maintenance

#6997 test: joomla quickstart bats test
  docs/tests/joomla.bats
Labels: maintenance

#6999 test: figure out why buildkite tests are running for quickstart bats tests
  .buildkite/test.sh
Labels: maintenance

#7000 test: add more joomla specific tests [skip buildkite]
  docs/tests/joomla.bats
Labels: maintenance

#6994 fix: add a mutagen sync at the end of the dotenv cmd
  cmd/ddev/cmd/dotenv-set.go
  pkg/ddevapp/mutagen.go
Labels: bugfix

#6930 fix: handle args with spaces in `ddev exec`, don't panic about invalid syntax in `exec_raw`, fixes #5865
  cmd/ddev/cmd/exec.go
  cmd/ddev/cmd/exec_test.go
  pkg/ddevapp/task.go
  pkg/util/utils.go
Labels: bugfix

#7012 test: run ClearDockerEnv() before tests, fixes #472
  cmd/ddev/cmd/root_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/dockerutil/dockerutils_test.go
Labels: maintenance

#7009 test: Makefile - try again if curl fails to download something it needs
  Makefile
Labels: maintenance

#7014 docs: change code refs to include info about Backdrop config storage options, fixes #7013
  pkg/ddevapp/backdrop.go
Labels: documentation

#6946 refactor: improve docker version checks, set minimum supported docker API to 1.44, fixes #6916
  cmd/ddev/cmd/debug-dockercheck.go
  cmd/ddev/cmd/root.go
  docs/content/users/install/docker-installation.md
  pkg/ddevapp/utils.go
  pkg/dockerutil/dockerutils.go
Labels: maintenance

#6974 docs: Remove gitpod/drupalpod from docs, for #6891 [skip buildkite]
  .github/workflows/pr-artifacts-comment.yml
  .spellcheckwordlist.txt
  README.md
  docs/content/developers/building-contributing.md
  docs/content/developers/release-management.md
  docs/content/developers/writing-style-guide.md
  docs/content/index.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/ddev-upgrade.md
  docs/content/users/install/docker-installation.md
  docs/content/users/install/performance.md
  docs/content/users/topics/sharing.md
Labels: documentation

#7006 fix: wrap args with spaces in `ddev exec` with double quotes instead of using raw, for #6930
  .github/workflows/quickstart.yml
  cmd/ddev/cmd/exec.go
  cmd/ddev/cmd/exec_test.go
Labels: bugfix

#6987 test: contao quickstart bats test
  docs/tests/contao.bats
Labels: maintenance

#6995 test: bats test for the sulu quickstart
  docs/tests/sulu.bats
Labels: maintenance

#7018 fix: bump mutagen to 0.18.1, fixes #7015
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7020 docs: add a note about rootless mode, show context in ddev debug test
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/users/install/docker-installation.md
Labels: documentation

#7016 fix: show router errors on `ddev list` and `ddev describe`, for #6980
  cmd/ddev/cmd/describe.go
  pkg/ddevapp/list.go
  pkg/ddevapp/router.go
Labels: bugfix

#7019 build: bump images to v1.24.3 for release, and docker-compose to v2.33.1
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7001 fix: validate docroot instead of using it blindly, fixes #6998
  cmd/ddev/cmd/composer-create.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/drupal.go
  pkg/ddevapp/magento.go
  pkg/ddevapp/typo3.go
  pkg/ddevapp/upload_dirs.go
  pkg/ddevapp/wordpress.go
Labels: bugfix

#7022 fix: the `#ddev-description` stanza in add-on install actions not showing if it's the first line
  pkg/ddevapp/addons.go
Labels: bugfix

#7023 feat: add `go-version` to `ddev version`, fixes #7021
  pkg/version/version.go
  pkg/version/version_test.go
Labels: enhancement
