Repository ddev/ddev, pull requests merged in 2025-10, with the labels that each got.

#7684 feat: update ddev debug test to emphasize global ddev dir [skip ci]
  cmd/ddev/cmd/scripts/test_ddev.sh
Labels: enhancement

#7693 docs(moodle): update moodle quickstart to have composer_root in root, fixes #7692 [skip buildkite]
  docs/content/users/quickstart.md
  docs/tests/moodle.bats
Labels: documentation

#7687 fix: disable `.env` parsing for `docker-compose pull`, fixes #7671
  cmd/ddev/cmd/addon-get.go
  pkg/dockerutil/docker_compose.go
  pkg/exec/exec.go
Labels: bugfix

#7686 fix: show if DDEV_GITHUB_TOKEN was used in download requests, add DDEV_GLOBAL_DIR env, skip add-on tests without token, fixes #7641
  .buildkite/macos-colima_vz.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-lima.yml
  .buildkite/macos-orbstack.yml
  .buildkite/macos-rancher-desktop.yml
  cmd/ddev/cmd/addon_test.go
  cmd/ddev/cmd/testdata/TestCmdAddon/example-repo/install.yaml
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/ddevapp.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/util/network.go
  pkg/version/version.go
Labels: bugfix

#7690 feat(dockercheck): improve ddev ut dockercheck, fixes #7672
  AGENTS.md
  cmd/ddev/cmd/scripts/test_ddev.sh
  cmd/ddev/cmd/utility-dockercheck.go
  cmd/ddev/cmd/utility-dockercheck_test.go
  pkg/dockerutil/requirements.go
  pkg/dockerutil/requirements_test.go
Labels: enhancement

#7691 fix: improve MOTD and sponsorship message controls, fixes #7468, fixes #7676, fixes #6918
  pkg/config/remoteconfig/messages.go
  pkg/globalconfig/values.go
Labels: bugfix
