Repository ddev/ddev, pull requests merged in 2025-05, with the labels that each got.

#7245 docs: Remove --no-interaction from Pimcore, disable test, fixes #7243
  docs/content/users/quickstart.md
  docs/tests/pimcore.bats
Labels: documentation

#7230 fix: support TYPO3 v14 nginx configuration, fixes #6944
  docs/content/users/quickstart.md
  docs/tests/common-setup.bash
  docs/tests/typo3.bats
  pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
Labels: bugfix

#7244 build: Reject the use of `drud/ddev/ddev` homebrew recipe
  .goreleaser.yml
Labels: maintenance

#7258 fix: add BASE_IMAGE arg before everything else, for #7071
  docs/content/users/extend/customizing-images.md
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#7270 fix: allow status code 429 for linkspector
  .github/workflows/docscheck.yml
  .linkspector.yml
Labels: bugfix

#7269 fix: WSL2 install script should wait longer for DDEV Windows installer to complete [skip ci]
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
Labels: bugfix

#7252 refactor: Make DownloadFile() retry logic more robust, improve curling in Makefile
  .buildkite/testbot_maintenance.sh
  Makefile
  pkg/util/network.go
Labels: maintenance

#7247 fix: correct warning output formatting (Drupal) and don't try to do exec when not running
  pkg/ddevapp/drupal.go
Labels: bugfix

#7260 fix: set `XDEBUG_MODE=off` for `ddev composer create-project`, fixes ddev/ddev-intellij-plugin#414
  cmd/ddev/cmd/composer-create-project.go
Labels: bugfix

#7187 build: remove <1.24 constraint for go, for #7057
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/tests.yml
Labels: maintenance

#7268 fix: support '>,x,X,*' comparisons and extended conditions in version constraint, fixes #7266
  pkg/ddevapp/config_test.go
  pkg/ddevapp/utils.go
Labels: bugfix

#7238 fix: add warning about duplicate usage for global commands, for #6293
  cmd/ddev/cmd/commands.go
Labels: bugfix

#7262 feat: update xhgui config, add link to upstream file
  containers/ddev-xhgui/var/www/xhgui/config/config.php
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#7263 refactor: improve `ddev add-on get` output, add warning exit code annotation
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/testdata/TestCmdAddonActionsOutput/recipe/install.yaml
  docs/content/users/extend/additional-services.md
  pkg/ddevapp/addons.go
Labels: maintenance

#7242 fix: Add path to docroot in wp parameters when not set, fixes #7241
  docs/content/users/usage/cms-settings.md
  docs/content/users/usage/commands.md
  docs/tests/wordpress.bats
  pkg/ddevapp/global_dotddev_assets/commands/web/wp
Labels: bugfix

#7259 fix: replace broken http and https port lookup, fixes #7246
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
Labels: bugfix

#7285 docs: add ddev.com, addon registry, last commit, DeepWiki badges to README.md
  README.md
Labels: documentation

#7277 fix: make xdebug work with WSL2 mirrored mode, fixes #7272
  cmd/ddev/cmd/scripts/test_ddev.sh
  docs/content/index.md
  docs/content/users/install/ddev-installation.md
  pkg/dockerutil/dockerutils.go
  pkg/nodeps/wsl.go
Labels: bugfix

#7236 refactor: Use `.ddev/.env.web` for Craft CMS DDEV settings, fixes #7233
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/craftcms.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/envfile.go
Labels: maintenance

#7288 build: add `make go-mod-update`
  Makefile
Labels: maintenance

#7289 build: bump docker-compose to v2.36.0
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7292 docs: use `composer create-project` in Magento 2 quickstart, for #7231
  docs/content/users/quickstart.md
Labels: documentation

#7284 feat: restart only specified service in `ddev debug rebuild`
  cmd/ddev/cmd/auth-ssh.go
  cmd/ddev/cmd/debug-rebuild.go
  cmd/ddev/cmd/utils.go
  docs/content/users/usage/commands.md
Labels: enhancement

#7291 build: bump images to v1.24.5 for release, fixes #7250
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7283 feat: add shell completion for --service (-s) flag
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/debug-rebuild.go
  cmd/ddev/cmd/exec.go
  cmd/ddev/cmd/logs.go
  cmd/ddev/cmd/ssh.go
  pkg/ddevapp/utils.go
Labels: enhancement

#7295 build: update brew instructions for old formula, fixes #7297
  .goreleaser.yml
Labels: maintenance

#7300 fix: change download timeout to 5 minutes instead of 20s, fixes #7298
  cmd/ddev/cmd/debug-download-images.go
  pkg/ddevapp/ddevapp.go
  pkg/util/network.go
Labels: bugfix

#7286 fix: Make sure env-type settings are populated before start, don't override `.ddev/.gitignore` file, for #7236
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#7301 fix: make TYPO3 nginx config work with TYPO3 v12, fixes #7299, for #7230
  pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
Labels: bugfix

#7311 build: bump docker-compose to v2.36.1
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7302 test: adding quickstarts for typo3 v13 and v12 plus bats tests
  docs/content/users/quickstart.md
  docs/tests/typo3.bats
Labels: maintenance

#7171 feat: make generic webserver work with ephemeral ports
  cmd/ddev/cmd/describe.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_test.go
Labels: enhancement

#7306 fix: add checks for "generic" webserver without 80/443 ports, for #6935, fixes #7313
  cmd/ddev/cmd/describe.go
  cmd/ddev/cmd/start.go
  pkg/ddevapp/router.go
Labels: bugfix

#7314 docs: fix indentation for code block
  docs/content/users/quickstart.md
Labels: documentation

#7315 build: bump images to v1.24.6 for release, fixes #7310
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7321 docs: trailing whitespace on template
  pkg/ddevapp/templates.go
Labels: documentation

#7324 build: update debian-archive-keyring for archived debian repos, fixes #7320
  containers/ddev-dbserver/Dockerfile
  pkg/ddevapp/config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7327 docs: use latest markdownlint, update "here" links
  .github/workflows/docscheck.yml
  docs/content/developers/brand-guide.md
  docs/content/developers/building-contributing.md
  docs/content/users/usage/faq.md
Labels: documentation

#7331 docs: add tip on initial PhpStorm plugin setup
  docs/content/users/install/phpstorm.md
Labels: documentation

#7332 refactor: improve message about missing docroot on `ddev start`
  pkg/ddevapp/ddevapp.go
Labels: maintenance

#7336 fix: make `ddev composer create-project` work with stdin
  cmd/ddev/cmd/composer-create-project.go
  docs/tests/shopware.bats
Labels: bugfix
