Repository ddev/ddev, pull requests merged in 2025-03, with the labels that each got.

#7042 feat: Add live link to Discord
  README.md
Labels: enhancement

#7025 docs: remove the recommendation not to use colima
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/users/install/docker-installation.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/faq.md
  docs/content/users/usage/troubleshooting.md
Labels: documentation

#7027 refactor: use `ddev composer create-project` in the code, for #6920
  cmd/ddev/cmd/composer-create-project.go
  cmd/ddev/cmd/composer-create-project_test.go
  cmd/ddev/cmd/composer.go
  cmd/ddev/cmd/composer_test.go
  docs/content/developers/building-contributing.md
  docs/content/developers/project-types.md
  docs/content/users/install/performance.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/developer-tools.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/backdrop.go
  pkg/ddevapp/drupal.go
Labels: maintenance

#7036 fix: delete traefik images based on the pattern used for ddev-dbserver and use constants for targeting, fixes #6326
  cmd/ddev/cmd/delete-images.go
  pkg/docker/images.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7007 feat: Support docker compose optional profiles, allow `ddev start --profiles=list,of,profiles`, for #6894
  cmd/ddev/cmd/addon-get_test.go
  cmd/ddev/cmd/ssh_test.go
  cmd/ddev/cmd/start.go
  cmd/ddev/cmd/start_test.go
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/bare-busybox/docker-compose.bare-busybox.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/bare-busybox/install.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/busybox/docker-compose.busybox.yaml
  cmd/ddev/cmd/testdata/TestCmdAddonGetWithDotEnv/busybox/install.yaml
  cmd/ddev/cmd/testdata/TestCmdStartOptionalProfiles/docker-compose.busybox.yaml
  docs/content/users/extend/custom-compose-files.md
  docs/content/users/usage/commands.md
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/start_test.go
  pkg/ddevapp/testdata/TestDdevApp_StartOptionalProfiles/docker-compose.busybox.yaml
  pkg/ddevapp/utils.go
  pkg/dockerutil/dockerutils.go
Labels: enhancement

#7045 fix: explicitly ping 127.0.0.1 in Traefik healthcheck to make proxying work, fixes #7044, fixes #6931
  containers/ddev-traefik-router/test/containertest.sh
  containers/ddev-traefik-router/traefik_healthcheck.sh
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7026 fix: remove refreshenv from WSL2 install scripts, fixes #7024 [skip ci]
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
Labels: bugfix

#7037 docs: add Backdrop-specific config considerations.
  docs/content/users/usage/cms-settings.md
Labels: documentation

#7057 build: don't use go 1.24 yet until docker issues resolved, fixes #7051
  .github/workflows/main-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/tests.yml
Labels: maintenance

#7017 test: Run quickstart tests with mutagen enabled [skip buildkite]
  .github/workflows/quickstart.yml
  cmd/ddev/cmd/debug-download-images.go
Labels: maintenance

#7056 docs: Improve troubleshooting docs for hosting
  docs/content/users/topics/hosting.md
Labels: documentation

#7064 build: skip testing with buildkite if diff is not from that branch
  .buildkite/test.sh
Labels: maintenance

#7055 docs: update mkdocs logo, update word/figurative mark svg for dark mode
  docs/content/assets/extra.css
  docs/content/developers/brand-guide.md
  docs/content/developers/logos/1x/Logo.png
  docs/content/developers/logos/1x/Logo_w_text.png
  docs/content/developers/logos/1x/Logo_w_text_dark.png
  docs/content/developers/logos/2x/Logo@2x.png
  docs/content/developers/logos/2x/Logo_w_text@2x.png
  docs/content/developers/logos/2x/Logo_w_text_dark@2x.png
  docs/content/developers/logos/3x/Logo@3x.png
  docs/content/developers/logos/3x/Logo_w_text@3x.png
  docs/content/developers/logos/3x/Logo_w_text_dark@3x.png
  docs/content/developers/logos/4x/Logo@4x.png
  docs/content/developers/logos/4x/Logo_w_text@4x.png
  docs/content/developers/logos/4x/Logo_w_text_dark@4x.png
  docs/content/developers/logos/SVG/Logo_w_text.svg
  docs/content/developers/logos/SVG/Logo_w_text_dark.svg
  docs/content/logo.svg
  mkdocs.yml
Labels: documentation

#7063 build: put both git and ssh in both webserver images, fixes #7054
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/tests/ddev-webserver/general.bats
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7070 build: Use specific binfmt for qemu in push-tagged-image [skip ci]
  .github/workflows/push-tagged-image.yml
Labels: maintenance

#7072 fix: add check for app in `ddev debug test` and run it from approot
  cmd/ddev/cmd/debug-test.go
Labels: bugfix

#7090 test: Fix secret loading [skip buildkite]
  .github/workflows/quickstart.yml
  .github/workflows/tests.yml
Labels: maintenance

#7097 docs: Fix pull request title link in pull request template [skip ci]
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#7082 test: Add quickstart test for magento2 (by @rpkoller) [skip buildkite]
  docs/content/users/quickstart.md
  docs/tests/magento2.bats
Labels: maintenance

#7100 test: Disable link check on freedesktop.org since it will be out for a week
  .linkspector.yml
Labels: maintenance

#7080 docs: add Wordpress special handling info about wp-cli.yml
  docs/content/users/usage/cms-settings.md
Labels: documentation

#7084 docs: add DevDb tip to database management documentation
  .spellcheckwordlist.txt
  docs/content/users/usage/database-management.md
Labels: documentation

#7104 test: use a more robust approach downloading the latest zip file (by @stasadev)
  docs/content/users/quickstart.md
  docs/tests/joomla.bats
Labels: maintenance

#7103 test: Bats test for CakePHP composer quickstart
  docs/content/users/quickstart.md
  docs/tests/cakephp.bats
Labels: maintenance

#7101 test: bats tests for expression engine and adjustments to its quickstart
  docs/content/users/quickstart.md
  docs/tests/ee.bats
Labels: maintenance

#7099 test: adding kirby quickstart bats test
  docs/tests/kirby.bats
Labels: maintenance

#7096 fix: remove obsolete references to non-traefik router
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/router.go
  pkg/ddevapp/router_compose_template.yaml
  pkg/ddevapp/utils.go
  pkg/globalconfig/global_config.go
Labels: bugfix

#7115 fix: add ddev_nointeractive to common-setup.bash (per @stasadev)
  docs/tests/common-setup.bash
Labels: bugfix

#7102 test: symfony bats tests
  docs/content/users/quickstart.md
  docs/tests/symfony.bats
Labels: maintenance

#7119 docs: Update quickstart.md to remove Drupal CMS zip file instructions
  docs/content/users/quickstart.md
  docs/tests/drupal.bats
Labels: documentation

#7112 test: adding silverstripe quickstart bats test
  docs/tests/silverstripe.bats
Labels: maintenance

#7107 test: craftcms bats test
  docs/content/users/quickstart.md
  docs/tests/craftcms.bats
Labels: maintenance

#7120 docs: ddev debug rebuild is great for debugging [skip buildkite]
  docs/content/users/extend/customizing-images.md
Labels: documentation

#7116 test: bats test for Statamic Composer quickstart [skip buildkite]
  docs/content/users/quickstart.md
  docs/tests/statamic.bats
Labels: maintenance

#7091 test: add OpenMage/Magento 1 quickstart test and split it from Magento 2, for #7094
  docs/content/users/quickstart.md
  docs/tests/openmage.bats
Labels: maintenance

#7089 feat: show config.*.y*ml on ddev start
  pkg/ddevapp/config.go
Labels: enhancement

#7125 fix: make linkspector ignorePatterns work properly, for #6951
  .linkspector.yml
Labels: bugfix

#7075 docs: Add docs about configuring browser for HTTPS certificates
  docs/content/users/install/configuring-browsers.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/index.md
  mkdocs.yml
Labels: documentation

#7126 test: adjust openmage bats test assertions to the now available demo content
  docs/tests/openmage.bats
Labels: maintenance

#7127 build: remove go toolchain, bump docker library to 28.0.2, for #7057
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/swarm/config.go
  vendor/github.com/docker/docker/api/types/swarm/secret.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/service_create.go
  vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go
  vendor/modules.txt
Labels: dependencies, maintenance

#7128 test: improve `ddev debug test`
  cmd/ddev/cmd/scripts/test_ddev.sh
  pkg/amplitude/amplitude.go
Labels: maintenance

#7129 docs: ignore mutagen links in linkspector
  .linkspector.yml
Labels: documentation

#7130 docs: fix example file name
  docs/content/users/extend/custom-compose-files.md
Labels: documentation

#7118 fix: set `NO_PROXY=*` in ddev-router to allow internal connections, use default Traefik config file location
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-traefik-router/test/containertest.sh
  containers/ddev-traefik-router/traefik_healthcheck.sh
  pkg/ddevapp/router_compose_template.yaml
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7069 feat: Integrate XHGui into DDEV, fixes #6894
  .github/workflows/container-tests.yml
  .github/workflows/push-tagged-image.yml
  .goreleaser.yml
  cmd/ddev/cmd/addon-remove.go
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/delete-images.go
  cmd/ddev/cmd/xhgui.go
  cmd/ddev/cmd/xhgui_test.go
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/enable_xhprof
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof/.gitmanaged
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof/xhprof_prepend.php
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/xhgui.collector/xhgui.collector.config.php
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/xhgui.collector/xhgui.collector.php
  containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
  containers/ddev-xhgui/Dockerfile
  containers/ddev-xhgui/Makefile
  containers/ddev-xhgui/README.md
  containers/ddev-xhgui/etc/nginx/http.d/default.conf
  containers/ddev-xhgui/test/containertest.sh
  containers/ddev-xhgui/test/testdata/.gitmanaged
  containers/ddev-xhgui/var/www/xhgui/config/config.php
  docs/content/users/configuration/config.md
  docs/content/users/debugging-profiling/xhprof-profiling.md
  docs/content/users/usage/commands.md
  pkg/config/types/xhprof_mode.go
  pkg/ddevapp/addons.go
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/ports.go
  pkg/ddevapp/router.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestTraefikStaticConfig/extraPlugin/expectation.yaml
  pkg/ddevapp/testdata/TestTraefikStaticConfig/logChange/expectation.yaml
  pkg/ddevapp/xhprof_xhgui.go
  pkg/ddevapp/xhprof_xhgui_test.go
  pkg/docker/images.go
  pkg/dockerutil/dockerutils.go
  pkg/globalconfig/global_config.go
  pkg/globalconfig/schema.json
  pkg/globalconfig/xhprof_mode.go
  pkg/nodeps/values.go
  pkg/version/version.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#7140 refactor: remove solrtail from installed example commands, fixes #7139
  cmd/ddev/cmd/commands_test.go
  pkg/ddevapp/dotddev_assets/commands/host/solrtail.example
  pkg/ddevapp/dotddev_assets/commands/solr/README.txt
  pkg/ddevapp/dotddev_assets/commands/solr/solrtail.example
Labels: maintenance

#7137 fix: don't override `generic` type in `ddev config --update`, fixes #7035
  cmd/ddev/cmd/config.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/apptypes.go
  pkg/ddevapp/apptypes_test.go
Labels: bugfix

#7145 fix: reload app hooks after uninstalling ddev-xhgui add-on, fixes #7144
  pkg/ddevapp/config.go
Labels: bugfix

#7138 fix: make `DDEV_PAGER` optional, update docs for `PAGER`, fixes #7032
  docs/content/users/extend/in-container-configuration.md
  pkg/ddevapp/app_compose_template.yaml
Labels: bugfix

#7143 fix: db warning on `config --update` should only be shown for default db type
  pkg/ddevapp/drupal.go
Labels: bugfix

#7142 fix: remove XHGui volume for `/run/nginx`, for #7069
  containers/ddev-xhgui/Dockerfile
  pkg/ddevapp/app_compose_template.yaml
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7124 feat: add MutagenSync annotation for custom commands, for #7053
  cmd/ddev/cmd/commands.go
  docs/content/users/extend/custom-commands.md
  pkg/ddevapp/global_dotddev_assets/commands/web/artisan
  pkg/ddevapp/global_dotddev_assets/commands/web/cake
  pkg/ddevapp/global_dotddev_assets/commands/web/console
  pkg/ddevapp/global_dotddev_assets/commands/web/craft
  pkg/ddevapp/global_dotddev_assets/commands/web/drush
  pkg/ddevapp/global_dotddev_assets/commands/web/magento
  pkg/ddevapp/global_dotddev_assets/commands/web/npm
  pkg/ddevapp/global_dotddev_assets/commands/web/php
  pkg/ddevapp/global_dotddev_assets/commands/web/sake
  pkg/ddevapp/global_dotddev_assets/commands/web/typo3
  pkg/ddevapp/global_dotddev_assets/commands/web/wp
  pkg/ddevapp/global_dotddev_assets/commands/web/yarn
Labels: enhancement

#7168 docs: Add the xhgui container to the building and contributing page. Add more description to the xhprof profiling page.
  docs/content/developers/building-contributing.md
  docs/content/users/debugging-profiling/xhprof-profiling.md
Labels: documentation

#7076 fix: use `charset=utf8mb4` in DATABASE_URL for Symfony environment variables, fixes #7068
  pkg/ddevapp/symfony.go
Labels: bugfix

#7158 fix: correct status color formatting in `ddev describe` and `ddev list`
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#7172 fix: use correct autoloader for XHGui php-profiler, preinstall it in ddev-webserver, fixes #7170
  cmd/ddev/cmd/xhgui.go
  containers/ddev-webserver/Dockerfile
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof/xhprof_prepend.php
  containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
  docs/tests/typo3.bats
  pkg/ddevapp/config.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#7160 docs: update Craft CMS quickstart, for #7107
  docs/content/users/quickstart.md
  docs/tests/craftcms.bats
Labels: documentation

#7053 feat: backdrop add bee to quickstart
  docs/content/users/quickstart.md
  docs/tests/backdrop.bats
Labels: enhancement

#7161 build: bump XHGui image to 0.23, for #7142
  containers/ddev-xhgui/Dockerfile
  containers/ddev-xhgui/var/www/xhgui/config/config.php
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7175 feat: Implement amplitude tracking for xhprof_mode, fixes #7169
  ampli.json
  pkg/ddevapp/amplitude_project.go
  third_party/ampli/ampli.go
Labels: enhancement

#7150 fix: delete third-party built images on `ddev delete`
  cmd/ddev/cmd/delete_test.go
  cmd/ddev/cmd/testdata/TestDeleteCmd/busybox/busybox/Dockerfile
  cmd/ddev/cmd/testdata/TestDeleteCmd/busybox/docker-compose.busybox.yaml
  cmd/ddev/cmd/testdata/TestDeleteCmd/busybox/install.yaml
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#7133 test: Add OpenMage composer quickstart and tests
  docs/content/users/quickstart.md
  docs/tests/openmage.bats
Labels: maintenance

#7162 build: bump images to v1.24.4 for release, and docker-compose to v2.34.0, fixes #7131
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance
