Repository ddev/ddev, pull requests merged in 2025-06, with the labels that each got.

#7359 docs: update ngrok link
  pkg/ddevapp/templates.go
Labels: documentation

#7368 test: update check for starter page in Silverstripe CMS
  docs/tests/silverstripe.bats
Labels: maintenance

#6983 feat: Support new LTS MariaDB 11.8
  .github/workflows/push-tagged-dbimage.yml
  .goreleaser.yml
  containers/ddev-dbserver/Makefile
  containers/ddev-dbserver/test/testdata/database_config/mariadb_11.8.ini
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
  docs/content/users/configuration/config.md
  docs/content/users/extend/database-types.md
  docs/content/users/usage/database-management.md
  pkg/ddevapp/config.go
  pkg/ddevapp/db_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/schema.json
  pkg/ddevapp/templates.go
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-5.5/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.0/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.1/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.11/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.2/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.3/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.4/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.5/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.6/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.7/.ddev/config.yaml
  pkg/ddevapp/testdata/TestPkgConfigDatabaseVersion/mariadb-version-10.8/.ddev/config.yaml
  pkg/nodeps/mariadb_values.go
  pkg/nodeps/mariadb_values_arm64.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, enhancement

#7381 build: use yaml/go-yaml instead of unmaintained yaml.v3, fixes #7280
  cmd/ddev/cmd/addon-get.go
  cmd/ddev/cmd/config_test.go
  go.mod
  go.sum
  pkg/config/state/storage/yaml/yaml_storage.go
  pkg/ddevapp/addons.go
  pkg/ddevapp/compose_yaml.go
  pkg/ddevapp/config.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/provider.go
  pkg/ddevapp/traefik_test.go
  pkg/globalconfig/global_config.go
  pkg/util/yaml_test.go
  pkg/util/yamltools.go
  vendor/dario.cat/mergo/FUNDING.json
  vendor/dario.cat/mergo/README.md
  vendor/dario.cat/mergo/SECURITY.md
  vendor/go.yaml.in/yaml/v3/LICENSE
  vendor/go.yaml.in/yaml/v3/NOTICE
  vendor/go.yaml.in/yaml/v3/README.md
  vendor/go.yaml.in/yaml/v3/apic.go
  vendor/go.yaml.in/yaml/v3/decode.go
  vendor/go.yaml.in/yaml/v3/emitterc.go
  vendor/go.yaml.in/yaml/v3/encode.go
  vendor/go.yaml.in/yaml/v3/parserc.go
  vendor/go.yaml.in/yaml/v3/readerc.go
  vendor/go.yaml.in/yaml/v3/resolve.go
  vendor/go.yaml.in/yaml/v3/scannerc.go
  vendor/go.yaml.in/yaml/v3/sorter.go
  vendor/go.yaml.in/yaml/v3/writerc.go
  vendor/go.yaml.in/yaml/v3/yaml.go
  vendor/go.yaml.in/yaml/v3/yamlh.go
  vendor/go.yaml.in/yaml/v3/yamlprivateh.go
  vendor/modules.txt
Labels: dependencies, maintenance

#7356 feat: add shell completion for `ddev config` and `ddev config global`
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config.go
Labels: enhancement

#7377 docs: improve xhgui documention, fixes #7376
  docs/content/users/debugging-profiling/xhprof-profiling.md
Labels: documentation

#7375 fix: Remove COMPOSE_CONVERT_WINDOWS_PATHS to make Rancher Desktop (Windows) work
  .buildkite/test.sh
  .buildkite/windows-rancher-desktop.yml
  .buildkite/windows10dockerforwindows.yml
  .ci-scripts/nsis_setup.sh
  cmd/ddev/cmd/auth-ssh.go
  cmd/ddev/cmd/autocompletion_test.go
  cmd/ddev/cmd/composer-create-project.go
  cmd/ddev/cmd/debug-test.go
  cmd/ddev/cmd/debug-test_test.go
  cmd/ddev/cmd/exec_test.go
  cmd/ddev/cmd/root_test.go
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/developers/scripts/windows_buildkite_setup.sh
  docs/content/users/install/docker-installation.md
  docs/content/users/usage/faq.md
  pkg/ddevapp/config_test.go
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/extra_expose_test.go
  pkg/ddevapp/hardened_test.go
  pkg/ddevapp/providerLocalfile_test.go
  pkg/ddevapp/router_test.go
  pkg/ddevapp/ssh_auth_test.go
  pkg/ddevapp/traefik_test.go
  pkg/dockerutil/dockerutils.go
  pkg/dockerutil/dockerutils_test.go
  pkg/dockerutil/testdata/sleepALittle.sh
  pkg/fileutil/file_hash_test.go
  pkg/fileutil/files.go
  pkg/testcommon/testcommon.go
  pkg/testcommon/testcommon_test.go
  pkg/util/utils.go
  pkg/version/version.go
Labels: bugfix

#7378 build: bump ddev-webserver and ddev-traefik-router, for #7282
  containers/ddev-traefik-router/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#7387 test: remove `TestCmdAddon` leftovers in `~/.ddev`
  cmd/ddev/cmd/addon_test.go
Labels: maintenance

#7388 feat: display user-defined `ssh-auth-compose.*.yaml` on `ddev start`
  docs/content/users/usage/architecture.md
  pkg/ddevapp/config.go
Labels: enhancement

#7386 refactor: normalize defaults in `ddev help config` and `ddev help config global`, update docs
  cmd/ddev/cmd/config-global.go
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  docs/content/users/configuration/config.md
  docs/content/users/usage/commands.md
  pkg/config/types/performance_mode.go
  pkg/config/types/xhprof_mode.go
  pkg/ddevapp/schema.json
  pkg/globalconfig/schema.json
Labels: maintenance

#7395 test: use `main` for setup-homebrew action instead of `master`
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/docscheck.yml
  .github/workflows/main-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/quickstart.yml
  .github/workflows/tests.yml
Labels: maintenance

#7396 build: upgrade mapstructure to v2
  go.mod
  go.sum
  pkg/config/state/state_manager.go
  vendor/github.com/go-viper/mapstructure/v2/.editorconfig
  vendor/github.com/go-viper/mapstructure/v2/.envrc
  vendor/github.com/go-viper/mapstructure/v2/.gitignore
  vendor/github.com/go-viper/mapstructure/v2/.golangci.yaml
  vendor/github.com/go-viper/mapstructure/v2/CHANGELOG.md
  vendor/github.com/go-viper/mapstructure/v2/LICENSE
  vendor/github.com/go-viper/mapstructure/v2/README.md
  vendor/github.com/go-viper/mapstructure/v2/decode_hooks.go
  vendor/github.com/go-viper/mapstructure/v2/errors.go
  vendor/github.com/go-viper/mapstructure/v2/flake.lock
  vendor/github.com/go-viper/mapstructure/v2/flake.nix
  vendor/github.com/go-viper/mapstructure/v2/internal/errors/errors.go
  vendor/github.com/go-viper/mapstructure/v2/internal/errors/join.go
  vendor/github.com/go-viper/mapstructure/v2/internal/errors/join_go1_19.go
  vendor/github.com/go-viper/mapstructure/v2/mapstructure.go
  vendor/github.com/go-viper/mapstructure/v2/reflect_go1_19.go
  vendor/github.com/go-viper/mapstructure/v2/reflect_go1_20.go
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/modules.txt
Labels: dependencies, maintenance

#7401 fix: treat argument as literal in `ddevcd` despite leading dash
  cmd/ddev/cmd/debug-cd.go
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
  pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.zsh
Labels: bugfix

#7397 fix: make DdevProjectConfig include overrides, fixes #7154
  cmd/ddev/cmd/addon-get.go
Labels: bugfix

#7392 feat: Improve elevation/escalation for hosts editing, including WSL2, fixes #6440, fixes #5324
  .ci-scripts/generate_artifacts.sh
  .github/workflows/main-build.yml
  .github/workflows/pr-build.yml
  .goreleaser.yml
  Makefile
  cmd/ddev-hostname/ddev-hostname.go
  cmd/ddev-hostname/elevate.go
  cmd/ddev-hostname/elevate_windows.go
  cmd/ddev/cmd/hostname.go
  cmd/ddev/main.go
  docs/content/users/usage/commands.md
  pkg/ddevapp/hostname_mgt.go
  pkg/ddevapp/os_warnings.go
  pkg/fileutil/file_exists.go
  pkg/hostname/hostname.go
  scripts/install_ddev.sh
  winpkg/ddev.nsi
Labels: enhancement

#7402 fix: make xdg-utils optional, use explorer.exe on WSL2 [skip buildkite]
  .goreleaser.yml
  docs/content/users/install/ddev-installation.md
  pkg/ddevapp/global_dotddev_assets/commands/host/launch
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
Labels: bugfix

#7416 ci: use `skip-package-name-checks`, pin `golangci-lint` to v2.2.1, remove `only-new-issues`, for #7415
  .github/workflows/golangci-lint.yml
  .golangci.yml
  pkg/config/remoteconfig/state.go
  pkg/config/remoteconfig/types/remote_config_storage.go
  pkg/config/state/types/state.go
  pkg/config/state/types/state_storage.go
  pkg/config/types/xhprof_mode.go
  pkg/globalconfig/types/types.go
  pkg/globalconfig/xhprof_mode.go
  pkg/util/errcheck.go
Labels: maintenance
