Repository ddev/ddev, pull requests merged in 2025-01, with the labels that each got.

#6877 docs: Update maintained date to 2025 in README [skip ci]
  README.md
Labels: documentation

#6873 fix: Make xhprof-prepend.php mount writable, for #3782
  pkg/ddevapp/app_compose_template.yaml
Labels: bugfix

#6878 docs: Add funding.json to apply for funding via floss.fund [skip ci]
  .well-known/funding-manifest-urls
  funding.json
Labels: documentation

#6881 docs: Stop checking stopwords 'just' and 'simply' [skip ci]
  .textlintrc
Labels: documentation

#6876 refactor: rename branch master to main, fixes #6476
  .buildkite/macos-colima_vz.yml
  .buildkite/macos-docker-desktop-amd64.yml
  .buildkite/macos-docker-desktop-arm64.yml
  .buildkite/macos-lima.yml
  .buildkite/macos-orbstack.yml
  .buildkite/macos-rancher-desktop.yml
  .buildkite/windows10dockerforwindows.yml
  .buildkite/wsl2-docker-desktop.yml
  .buildkite/wsl2-docker-inside.yml
  .ci-scripts/bump_homebrew.sh
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/RELEASE_NOTES_TEMPLATE.md
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/docscheck.yml
  .github/workflows/docspublish.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main-build.yml
  .github/workflows/quickstart.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  .linkspector.yml
  .well-known/funding-manifest-urls
  cmd/ddev/cmd/debug-test.go
  containers/ddev-dbserver/README.md
  containers/ddev-gitpod-base/Dockerfile
  containers/ddev-gitpod-base/README.md
  containers/ddev-nginx-proxy-router/README.md
  containers/ddev-php-base/README.md
  containers/ddev-ssh-agent/README.md
  containers/ddev-traefik-router/README.md
  containers/ddev-webserver/README.md
  containers/image_readme_template.md
  containers/test-ssh-server/README.md
  docs/content/developers/brand-guide.md
  docs/content/developers/building-contributing.md
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/developers/release-management.md
  docs/content/developers/testing-docs.md
  docs/content/users/configuration/config.md
  docs/content/users/debugging-profiling/xhprof-profiling.md
  docs/content/users/extend/additional-services.md
  docs/content/users/extend/custom-commands.md
  docs/content/users/extend/customizing-images.md
  docs/content/users/install/ddev-installation.md
  docs/content/users/install/performance.md
  docs/content/users/providers/index.md
  docs/content/users/usage/commands.md
  docs/content/users/usage/faq.md
  funding.json
  mkdocs.yml
  pkg/ddevapp/dotddev_assets/providers/README.txt
  pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
  pkg/testcommon/testcommon_test.go
  scripts/install_ddev_head.sh
  scripts/install_ddev_wsl2_docker_desktop.ps1
  scripts/install_ddev_wsl2_docker_inside.ps1
  winpkg/chocolatey/ddev.nuspec
Labels: maintenance

#6874 fix: In acquia.yaml, specify default site source for ddev pull acquia.
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
Labels: bugfix

#6852 feat: disable `ddev config` in parent folders of a project, but allow it in subfolders, fixes #6783, fixes #5493
  cmd/ddev/cmd/config.go
  cmd/ddev/cmd/config_test.go
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: enhancement

#6883 fix: Fix Acquia push, Minor cleanup in provider integrations [skip buildkite]
  .github/workflows/tests.yml
  pkg/ddevapp/dotddev_assets/providers/acquia.yaml
  pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
  pkg/ddevapp/dotddev_assets/providers/platform.yaml
  pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example
  pkg/ddevapp/providerPlatform_test.go
  pkg/ddevapp/providerUpsun_test.go
Labels: bugfix

#6887 fix: DB container: Remove MYSQL_PWD, use ARG in mysql/mariadb Dockerfile, remove OPTIMIZE TABLES, fixes #6886
  containers/ddev-dbserver/Dockerfile
  pkg/ddevapp/app_compose_template.yaml
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/hooks_test.go
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6895 test: Quickstart tests for TYPO3 quickstart
  .github/workflows/quickstart.yml
  docs/content/users/quickstart.md
  docs/tests/typo3.bats
Labels: maintenance

#6901 docs: replace GOOS and GOARCH for a DDEV_ alternative, for #6752
  docs/content/users/extend/custom-commands.md
Labels: documentation

#6889 docs: Improve windows buildkite setup workflow
  .buildkite/sanetestbot.sh
  docs/content/developers/buildkite-testmachine-setup.md
  docs/content/developers/scripts/windows_buildkite_setup.sh
  docs/content/developers/scripts/windows_buildkite_start.ps1
  docs/content/developers/scripts/wsl2-test-runner-setup.sh
Labels: documentation

#6904 docs: change the quickstart repo for typo3 to test-typo3
  docs/content/users/quickstart.md
Labels: documentation

#6900 feat: override `PAGER` with `DDEV_PAGER` env variable, for #6842
  pkg/ddevapp/app_compose_template.yaml
Labels: enhancement

#6906 refactor: remove outdated `move-issue` config , fixes #6899
  .github/move.yml
Labels: maintenance

#6897 test: Improve WP quickstart and add wordpress bats tests
  .spellcheckwordlist.txt
  docs/content/users/quickstart.md
  docs/tests/wordpress.bats
Labels: maintenance

#6893 test: Add bats test coverage for Drupal Core and Drupal CMS quickstarts
  docs/content/users/quickstart.md
  docs/tests/common-setup.bash
  docs/tests/drupal.bats
Labels: maintenance

#6902 fix: provide a dummy ddev command inside container, allow web commands there, fixes #6574
  containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
  containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/ddev
  containers/ddev-webserver/tests/ddev-webserver/general.bats
  pkg/ddevapp/global_dotddev_assets/commands/web/drush
  pkg/ddevapp/global_dotddev_assets/commands/web/pint
  pkg/ddevapp/global_dotddev_assets/commands/web/sake
  pkg/ddevapp/global_dotddev_assets/commands/web/typo3
  pkg/ddevapp/global_dotddev_assets/commands/web/wp
  pkg/versionconstants/versionconstants.go
Labels: dependencies, bugfix

#6905 build: bump docker-compose to 2.32.4
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6907 test: add force flag to the remove cmd and a fixed dl link to the latest version of Drupal CMS
  docs/content/users/quickstart.md
  docs/tests/drupal.bats
Labels: maintenance

#6909 fix: remove noise from `docker-compose` on build and reformat `ddev start` output, for #6905
  pkg/ddevapp/ddevapp.go
  pkg/ddevapp/mutagen.go
  pkg/dockerutil/dockerutils.go
  pkg/util/utils.go
Labels: bugfix

#6914 test: some tests should skip skippable testsites
  .github/workflows/tests.yml
  cmd/ddev/cmd/describe_test.go
  pkg/ddevapp/ddevapp_test.go
  pkg/ddevapp/settings_test.go
Labels: maintenance

#6913 fix: update Drupal 7 settings.ddev.php and settings.php to match Drupal 7.103
  pkg/ddevapp/drupal/drupal7/settings.ddev.php
  pkg/ddevapp/drupal/drupal7/settings.php
Labels: bugfix

#6915 build: bump images to v1.24.2 for release
  containers/ddev-php-base/Dockerfile
  containers/ddev-webserver/Dockerfile
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6923 docs: Update Rancher Desktop buildkite agent setup [skip ci]
  docs/content/developers/buildkite-testmachine-setup.md
Labels: documentation

#6919 test: prepare for magento2 quickstarts by providing composer secrets [skip ci]
  .github/workflows/quickstart.yml
Labels: maintenance

#6924 build: rename mailhog.conf to mailpit.conf
  containers/ddev-webserver/ddev-webserver-dev-base-files/etc/supervisor/conf.d/mailpit.conf
  pkg/versionconstants/versionconstants.go
Labels: dependencies, maintenance

#6928 docs: Fix formatting for staging server in Let's Encrypt [skip ci]
  docs/content/users/topics/hosting.md
Labels: documentation

#6936 test: make lima/colima tests work after lima 1.0.4
  .buildkite/test.sh
Labels: maintenance

#6926 fix: don't panic when running project in not allowed location, fixes #6925
  pkg/ddevapp/config.go
  pkg/ddevapp/config_test.go
Labels: bugfix

#6942 docs: add more examples for testing a PR
  docs/content/developers/building-contributing.md
Labels: documentation

#6940 fix: unset JAVA_HOME to prevent mkcert hang
  pkg/ddevapp/ddevapp.go
Labels: bugfix

#6947 feat: Add info about web_extra_exposed_ports and web_extra_daemons to Amplitude instrumentation
  ampli.json
  docs/content/developers/building-contributing.md
  pkg/ddevapp/amplitude_project.go
  third_party/ampli/ampli.go
Labels: enhancement

#6941 fix: allow `ddev config` for existing parent projects, fixes #6937
  cmd/ddev/cmd/config_test.go
  pkg/ddevapp/config.go
Labels: bugfix

#6951 fix: use linkspector for external links, use mkdocs for internal links, for #6860
  .github/workflows/colima-tests.yml
  .github/workflows/container-tests.yml
  .github/workflows/docscheck.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-build.yml
  .github/workflows/tests.yml
  .linkspector.yml
  Makefile
  docs/content/developers/release-management.md
  mkdocs.yml
Labels: bugfix
